yast/yast-yast2

library/general/src/modules/Arch.rb, package/yast2.changes
Treat PowerNV as CHRP for now. The major difference is PowerNV doesn't
have bootloader, firmware parses grub.cfg and doing kexec. But having
bootlaoder (PReP partition) is harmless.
Signed-off-by: Dinar Valeev <dvaleev@suse.com>
=> Add new PowerPC - PowerNV platform

.travis.yml
- removed `rake check:syntax`, not needed anymore, the syntax is checked by rubocop
- use `-s` (silent) make option
The log size has been decreased from [~4600 lines](https://travis-ci.org/yast/yast-yast2/builds/48464147) to [~2500 lines](https://travis-ci.org/yast/yast-yast2/builds/48468523), which is a huge difference (almost half of the original size!).
=> Be less verbose at Travis to have shorter log

.travis.yml
Fixed sending coveralls report at Travis - it failed when the commit author name contained an UTF-8 (non-ASCII) character.
I also moved the locale setting just to the tests to not potentially influence the other commands (to be compatible with the other Travis scripts).
(BTW locally it works without the `LC_ALL=` setting but failed without it at Travis. It took me some time to figure this out...)
=> Fix Travis locale

library/network/src/modules/SuSEFirewallProposal.rb, library/network/test/susefirewall_proposal_test.rb, package/yast2.changes, package/yast2.spec
- We have found out that there are two firewall proposals: one used in second stage, but the other one used in first stage. I'm sharing the functionality by using SuSEFirewallProposal
- The first stage proposal lives at yast/yast2-network
=> Make iscsi_proposal public

library/network/src/modules/SuSEFirewallProposal.rb, library/network/test/susefirewall_proposal_test.rb, package/yast2.changes, package/yast2.spec
- It's not needed to open any ports in firewall, only enable early initialization (bsc#916376)
- As a side effect, I've fixed functionality to open fallback ports when firewall service does not exist
- If network interfaces are not assigned to any zone (e.g., in initial stage of installation) fallback ports are open in all zones (worked the same way for firewall services)
- Including extensive test case
=> Fixed firewall proposal in installation (iSCSI-related)

library/general/src/modules/Linuxrc.rb, library/general/test/linuxrc_test.rb, package/yast2.changes, package/yast2.spec
- We need to read Linuxrc commandline to find out whether Yast should create pre/post-install snapshots during Upgrade/Installation
- This new functionality enables us to simply call Linuxrc.value_for("disable_snapshots") and it will have the same result independently on the way how it's written on Linuxrc commandline - users don't need to follow strict guidelines and usually do not follow them (matches are case-insensiteve, dots, hyphens and underscores are ignored)
=> Added Linuxrc.value_for

library/general/src/modules/Linuxrc.rb, library/system/src/lib/yast2/fs_snapshot.rb, library/system/test/fs_snapshot_test.rb, package/yast2.changes, package/yast2.spec
- User can define the behavior on Linuxrc commandline disable_snapshots=(single|around|all)
- Also any comma-separated combination is allowed
- Including full-coverage test case
- Thanks to Linuxrc.get_value user can define this as any other Linuxrc parameter (with dots, hyphens, underscores and case insensitive)
- Values behave the very same as the parameter name
=> Implemented possibility to temporarily disable creating filesystem snapshots

library/system/src/lib/yast2/fs_snapshot.rb, library/system/test/fs_snapshot_test.rb, package/yast2.changes, package/yast2.spec
Just call `value_for` instead of `get_value`.
=> Fix value_for typo

package/yast2.changes, package/yast2.spec, scripts/yast2
- FATE#317637, bnc#877447
- Explanation and discussion at http://lists.opensuse.org/yast-devel/2015-06/msg00024.html
- Tested IRL with dud=${path_to}/yast2.rpm - the package is downloaded, used, new message "Starting Installer" is shown and then Installation starts as usually
=> Starting the Installer (YaST2.First-Stage) directly from yast2

library/system/src/lib/yast2/fs_snapshot.rb, library/system/test/fs_snapshot_test.rb
`Yast2::FsSnapshot.create_pre`, as used in https://github.com/yast/yast-update/blob/7aea14b5c5a8632f8bd86855df245ba16b90902f/src/modules/RootPart.rb#L1808, is supposed to receive `cleanup` and `important` parameters (instead of only the description). This commit should fix this issue.
=> Fix create pre fs snapshot

library/general/src/lib/installation/proposal_client.rb
* This documentation was living until now in yast-installation module.
* The missing documentation is taken from http://www.rubydoc.info/github/yast/yast-installation/file/doc/proposal_api.md
=> Add missing documentation to ProposalClient

package/yast2.changes, scripts/yast2
...the same way as the installation script
- The installation script handles the reboot this way: https://github.com/yast/yast-installation/blob/master/startup/YaST2.call#L368, in installed system the support is missing
- No version change (yet), it's needed for online migration, it will be released as part of the "online migration" update later (or sooner if some other urgent issue appears until that)
=> "yast2" script - handle also the reboot flag (bsc#942461)

library/general/src/modules/Mode.rb, library/general/test/mode_test.rb, package/yast2.changes
* To avoid `Mode.autoinst || Mode.autoupgrade` constructions...
* ... or even worst, forgetting about autoupgrade.
BTW, I've added some basic tests to Mode module.
=> Add Mode#auto method

library/network/src/modules/SuSEFirewall.rb, package/yast2.changes, package/yast2.spec
bnc#897129
alternative approach to https://github.com/yast/yast-network/pull/275
notes, see above PR for details I refer to:
- the issue is that when SuSEFirewall#Import is followed by SuSEFirewall#Read than the later overwrites imported data
- keep_install_network should address only network setup (setup which can be done by yast2-network or <networking /> section in case of AY profile; just my POV)
- keep_install_network can be a bit misleading in above PR. Its semantic is that network configuration used in linuxrc should be transferred to target. In case of firewall it makes no sense - linuxrc do not allow to setup firewall and in the above PR it is used to force AY setup.
- in my POV, SuSEFirewall should take care of protecting imported data.
=> Firewall keeps imported data

scripts/yast2
The migration module creates the snapshots explicitly, avoid too many
snapshots created during the online migration.
https://bugzilla.suse.com/show_bug.cgi?id=944019
=> Disable snapshots when running the "migration" module (bsc#944019)

library/packages/src/modules/PackagesUI.rb, library/packages/test/Makefile.am, library/packages/test/packages_ui_test.rb, package/yast2.changes, package/yast2.spec
...in the confirmation dialog to make it better readable.
- 3.1.150
The original layout:
After applying this patch:
=> Properly format the package license (bsc#819311)

library/general/src/modules/Arch.rb, package/yast2.changes, package/yast2.spec
This is a semantic backport of f493b696a1c48cfdcfe1fbd4fc14fe1a1a976d2a
from master.
=> Add AArch64

package/yast2.changes, package/yast2.spec, scripts/yast2
https://bugzilla.suse.com/show_bug.cgi?id=880701
The actual bug seems to be between Qt and Harfbuzz. Telling Qt to use an
older Harfbuzz solves the problem.
Using that for all languages risks breaking other languages with complex
scripts (Indic?) so let's limit this to Arabic.
=> Fixed clipped labels in Arabic on some widgets

library/packages/src/modules/PackageCallbacks.rb, package/yast2.changes, package/yast2.spec
Replace "Skip" with "Ignore" when some problem occurs when fetching packages.
=> Replace "Skip" with "Ignore"

library/wizard/src/modules/Progress.rb, package/yast2.changes, package/yast2.spec
- 3.1.156
require "yast"
Yast.import "Wizard"
Yast.import "Progress"
Yast::Wizard.CreateDialog
Yast::Progress.New("Initializing Boot Loader Configuration", " ", 1, [], [], "")
Yast::UI.UserInput
Yast::Wizard.CloseDialog
The tricky part is that you have to test it in a low-res screen (less than 800x600) to force usage of the simple Wizard implementation in the `Wizard` module. In the full Wizard UI the problem does not happen.
=> Fixed clipped dialog label (bsc#948381)

library/cwm/src/modules/CWM.rb, library/general/src/Makefile.am, library/general/src/lib/ui/service_status.rb, library/general/test/Makefile.am, library/general/test/service_status_test.rb, package/yast2.changes, package/yast2.spec
Replace `UI::SrvStatusComponent` with `UI:ServiceStatus`. The new class has a much better API, as explained below.
Instead of the service_xx methods, it knows expect an object that complains to the SystemdService API. For non-standard services the user is expected to implement their own class.
Instead of using callbacks, handle_input now returns a meaningful symbol.
See https://github.com/yast/yast-dns-server/pull/52 for code changes in yast-dns-server
This PR also introduces `CWM.save_current_widgets` and `CWM.validate_current_widgets`, needed to implement an "apply" button.
=> SrvStatusComponent -> ServiceStatus

library/network/src/modules/SuSEFirewall.rb, library/network/test/susefirewall_test.rb, package/yast2.changes, package/yast2.spec
* Changes SuSEFirewall to read system's configuration during installation, instead of using `ReadDefaultConfiguration()`. It's should fix [bsc#963585](https://bugzilla.suse.com/show_bug.cgi?id=963585).
* Add a new method `read_and_import` which read the firewall configuration and merges a configuration hash (usually from an AutoYaST profile). In contrast to the regular `Import`, it performs a merge.
=> SuSEFirewall module reads system configuration during autoinstallation

library/general/src/modules/Arch.rb, package/yast2.changes, package/yast2.spec
We treated PowerNV as CHRP platform for a while, for compatibility
reasons.
This introduces board_powernv
Signed-off-by: Dinar Valeev <dvaleev@suse.com>
=> Introduce PowerNV platform

library/mail/src/scrconf/cfg_mail.scr, package/yast2.changes, package/yast2.spec
- Added cfg_mail.scr due to circular dependencies as showed [here](https://build.opensuse.org/request/show/372909)
=> Moved cfg_mail.scr from yast2-mail (FATE#319711)

library/general/src/Makefile.am, library/general/src/scrconf/proc_modules.scr, package/yast2.changes, package/yast2.spec
This is to avoid yast2-sound to depend on yast2-installation.
=> Add proc_modules.scr from yast-installation (bsc#972310)

library/packages/src/Makefile.am, library/packages/src/lib/packages/file_conflict_callbacks.rb, library/packages/src/modules/PackageCallbacks.rb, library/packages/test/Makefile.am, library/packages/test/file_conflict_callbacks_test.rb, package/yast2-rpmlintrc, package/yast2.changes
* [bsc#923590](https://bugzilla.suse.com/show_bug.cgi?id=923590)
* [Trello card](https://trello.com/c/Sty1P76G/100-5-opensuse-923590-p2-yast2-pkg-bindings-yast2-obvious-file-conflicts-not-resolved-missing-file-conflicts-callbacks-in-yast)
A sample repository with testing packages that have file conflicts is [obs://YaST:testing](http://download.opensuse.org/repositories/YaST:/testing/openSUSE_Leap_42.1/).
*Note: The new added file has [100% test code coverage](https://coveralls.io/builds/5581508/source?filename=library%2Fpackages%2Fsrc%2Flib%2Fpackages%2Ffile_conflict_callbacks.rb)* :wink: 
Until now the package installation in YaST ignored possible file conflicts in the installed packages. In contrast `zypper` already supports that check for some time.
File conflicts happen when two …
=> File conflict callbacks

library/packages/src/lib/packages/file_conflict_callbacks.rb, package/yast2.changes, package/yast2.spec
Discussed with Ken, the reasons for the change are:
- Safe default
- Compatible with zypper
=> Make the "Abort" button default in the file conflict popup

library/system/src/lib/yast2/execute.rb
Use a full URL so that YARD can make a link in the rendered docs.
It is especially important because Cheetah.run takes a great variety of
arguments.
=> Link to docs for Cheetah.run

library/network/src/modules/SuSEFirewallServices.rb
Note that in most cases a *service* argument needs a "service:" prefix.
Replacing tabs by spaces fixes `@example` rendering.
This was done to understand the module better as it gets bigger changes in #457 (firewalld).
=> Reviewed and fixed docs for SuSEFirewallServices.

library/general/src/lib/installation/finish_client.rb, package/yast2.changes
Fixes "when" key in FinishClient#info.
I'm not releasing a new version (I'll do that as part of the #465 PR).
=> Fix "when" key in FinishClient#info

.rubocop.yml, library/network/doc/autodocs/Makefile.am, library/network/src/Makefile.am, library/network/src/lib/network/firewalld.rb, library/network/src/modules/CWMFirewallInterfaces.rb, library/network/src/modules/SuSEFirewall.rb, library/network/src/modules/SuSEFirewallServices.rb, library/network/test/Makefile.am, library/network/test/susefirewall_services_test.rb, library/network/test/susefirewall_test.rb, library/network/test/susefirewalld_test.rb, package/yast2.changes, package/yast2.spec
Hi,
This patchset extends the SuSEFirewall2 backend with FirewallD ([website](http://www.firewalld.org/), [OBS package](https://build.opensuse.org/package/show/openSUSE:Factory/firewalld)) support. The goal is for yast2 modules to be able to use either SuSEfirewall2 or FirewallD to perform their regular firewall configurations depending on which one is running on the system. Not all methods have been added to FirewallD since some of them do not appear to be used anymore. If something is missing I will fix it in a subsequent commit as bugs or limitations are being identified by the broader adoption and use of the extended API.
The only known limitation so far is in the testsuite where firewalld tests can't run in parallel with SuSEfirewall2. The reason for that is that they both manipulate …
=> Add FirewallD support to SuSEFirewall2 backend

library/cwm/test/widgets_test.rb, library/general/src/lib/installation/proposal_client.rb, library/general/test/event_dispatcher_test.rb, library/general/test/proposal_client_test.rb, test/test_helper.rb
and also fix an API bug in the process; need to verify that the fix is harmless
Coverage goes down from 56% to 45%, yay!
=> Count test coverage more accurately

library/packages/src/lib/packages/file_conflict_callbacks.rb, library/packages/test/file_conflict_callbacks_test.rb, package/yast2.changes, package/yast2.spec
...when the Progress dialog is not displayed.
Open a new Wizard window and close it at the end, this ensures the original dialog content is restored after finishing the callbacks.
- 3.1.193
=> Fixed displaying the file conflicts callbacks (bsc#983464)

library/control/src/modules/ProductProfile.rb
BTW the package lives in
https://build.opensuse.org/package/show/SUSE:SLE-12:GA/subscription-tools
This is the first real bug I've found with ruby-lint, after thousands of
false positives!!
I was looking why it was not seeing the Pkg namespace as it should, and
noticed a real problem in the last line:
$ ruby-lint -p text library/control/src/modules/ProductProfile.rb
ProductProfile.rb: error: line 52, column 18: undefined constant Pkg
ProductProfile.rb: error: line 64, column 17: undefined constant Pkg
ProductProfile.rb: error: line 81, column 33: undefined method tmpdir on an instance of DirectoryClass
ProductProfile.rb: error: line 86, column 24: undefined constant Pkg
ProductProfile.rb: error: line 95, column 19: undefined constant Pkg
ProductProfile.rb: error: line 138, column 21: …
=> Do not crash if subscription-tools.rpm is missing.

library/wizard/src/modules/Wizard.rb, package/yast2.changes, package/yast2.spec
...instead of the low resolution (22x22) one.
The standalone icon does not look that bad, but when comparing it with the other applications it looks awful, see this screenshot from [bug 985432](https://bugzilla.suse.com/show_bug.cgi?id=985432):
I have tested the fix using the Plasma 5 window switcher, the look obviously depends on the configured style.
This is the original 22x22 icon, it looks a bit fuzzy without much details:
The new 64x64 icon is more sharp with more details:
=> Use a high resolution window icon (64x64) (bsc#985432)

library/general/src/modules/Arch.rb
So far only Arch.aarch64 existed but no 32-bit equivalent.
Will be needed for further yast-bootloader changes.
Signed-off-by: Andreas Färber <afaerber@suse.de>
=> Define Arch.arm

library/types/src/modules/URL.rb, library/types/test/Makefile.am, library/types/test/url_test.rb, package/yast2.changes, package/yast2.spec
Before this patch:
```ruby
url = "cd:/?device=/dev/sr0"
Yast::URL.Build(Yast::URL.Parse(url)) # => "cd://?device=/dev/sr0"
```
After this patch it returns `cd:/?device=/dev/sr0`.
=> Fix cd/dvd URLs reassembling

library/general/src/modules/Popup.rb, library/general/test/popup_test.rb, package/yast2.changes, package/yast2.spec
This patch fixes [bsc#992506](https://bugzilla.suse.com/show_bug.cgi?id=992506). When trying to contact a non-valid SCC/SMT server, YaST didn't escaped the error message.
After this fix, this situation should be handled properly:
The bug was introduced in this older [PR](https://github.com/yast/yast-yast2/pull/442). The reason is that we have two different use cases here:
* I want to show an error and we should escape the content (potentially unsafe).
* I want to show a long message and I don't want the content to be escaped (supposed to be safe).
So now we're escaping in case of showing an error. AutoYaST timed dialogs won't be affected as the implementation is different and does not try to switch to richtext in long error messages.
=> Popup.Error will escape tags when using richtext

library/packages/src/modules/PackageCallbacks.rb, package/yast2.changes, package/yast2.spec
How it looks before:
How looks now:
=> Packages: remove warning Icon from package callbacks.

library/network/src/modules/NetworkInterfaces.rb, library/network/test/network_interfaces_test.rb, package/yast2.changes, package/yast2.spec
During the cleanup of NetworkInterfaces the behaviour of Locate method was changed by error as you can see here: 
https://github.com/yast/yast-yast2/pull/433/files#diff-9e2299f8f1f2334535a5e511b4383b4aR181
This just give the original behavior, fixing also current method tests.
=> Locate returns interface names instead of types (bsc#998717)

library/network/src/modules/NetworkInterfaces.rb, library/network/test/network_interfaces_test.rb, package/yast2.changes, package/yast2.spec
* Network: NetworkInterfaces.Locate returns interface names instead of interface types (bsc#998717).
=> Merge changes from SLE12-SP2 (#494)

package/yast2.changes, package/yast2.spec
https://bugzilla.suse.com/show_bug.cgi?id=999203
The remaining 4 pm files in this package do not participate in build
time tests.
=> Removed build dependency on yast2-perl-bindings (bsc#999203)

package/yast2.changes, package/yast2.spec, scripts/yast2
Remove the restart file (usually `/var/lib/YaST2/restart_yast`) if it already exists before starting the module to  avoid possible infinite loop. Fixes [bug #842910](https://bugzilla.suse.com/show_bug.cgi?id=842910).
The file might be accidentally left in the system when YaST crashes or system shuts down unexpectedly before YaST removes that restart file.
How to reproduce the issue:
```
touch /var/lib/YaST2/restart_yast
yast2 lan
```
=> Restart file cleanup

.gitignore, library/general/src/modules/PackagesProposal.rb, library/general/test/packages_proposal_test.rb, package/yast2.changes, package/yast2.spec
This API enhancement is needed by `yast2-packager` to fix blocked installation after deselecting some default patterns in openQA tests (YaST complains about missing patterns and blocks the installation).
- There are now two kinds of resolvables: *required* and *optional*, the optional ones are stored separately so the software proposal module can only complain for the missing required resolvables. User can deselect the optional resolvables without any problem.
- The API is backward compatible, the added method parameter is optional with the backward compatible default value. We do not have to change the existing code.
- Code cleanup - removed all `Builtins` and `Convert` calls
- Refactoring - more Ruby-like code
- Added unit tests for the `PackagesProposal` module (covers 100% of the …
=> PackagesProposal - Added API for optional resolvables

library/packages/test/file_conflict_callbacks_test.rb, package/yast2.changes, package/yast2.spec
- Fixes a bug revealed by the new yast2-core - a mocked Pkg implementation did not implement all called methods.
Note: The commits are in an unusual order - the first is the changelog to demonstrate the failure in Travis, second commit is the fix to show the fixed state. I'll squash them at merge to not have this issue in `master`.
=> Fix for the new yast2-core

.travis.yml, library/network/src/modules/NetworkInterfaces.rb, library/network/test/data/etc/sysconfig/network/ifcfg-, library/network/test/network_interfaces_helpers_test.rb, library/types/test/url_test.rb, package/yast2.changes, package/yast2.spec
https://bugzilla.suse.com/show_bug.cgi?id=1028081
=> Backported code from the current master

library/packages/src/modules/SlideShow.rb, package/yast2.changes, package/yast2.spec
- https://bugzilla.suse.com/show_bug.cgi?id=1028721
Just applied the same fix already in [ProductLicense](https://github.com/yast/yast-packager/blob/dff498280c3969db2a386e9face338af36e24a4b/src/modules/ProductLicense.rb#L179)
=> SlideShow: escape license in plain text (bsc#1028721).

library/packages/src/modules/SlideShow.rb, package/yast2.changes, package/yast2.spec
It is a backport from #560 where you can see screenshots and more details.
=> SlideShow: escape license in plain text. (backport from SP3)

library/control/src/modules/WorkflowManager.rb, library/control/test/workflow_manager_test.rb, package/yast2.changes, package/yast2.spec
This is an fix up for #559.
I tested the latest SP3 build with my example extension, it revealed some bugs not found by unit tests:
- A conflict between `Yast::Packages` (from `modules/Packages.rb`) and the `::Packages` name space. Fixed by full qualification.
- The `extract` method argument was a `Tempfile` object instead of a `String` - the call was mocked in the test so it was not found. Fixed and improved the test to check also the passed argument type to avoid regressions.
=> Fixed downloading installer extension package (FATE#320772)

library/general/src/scrconf/etc_fstab.scr, library/general/test/agents_test/fstab_agent_test.rb, library/general/test/agents_test/test_root3/etc/fstab, package/yast2.changes, package/yast2.spec
The lines containing just spaces are not handled by the agent and the parser stops ignoring the rest of the file. See [bsc#1030425](https://bugzilla.suse.com/show_bug.cgi?id=1030425) for more details.
This patch defines space and tab at the beginning as a comment so a line containing only spaces is ignored.
The drawback is that a space at the beginning of a valid line makes it a comment as well. But that's actually not a regression, the original code did not handle it as well and the rest of the file was ignored.
With this change it is still not perfect, but at least it parses the other lines so it is still an improvement.
This patch does not fix the upgrade issue completely, the same fix needs to applied at https://github.com/yast/yast-update/blob/master/src/modules/RootPart.rb#L819.
I …
=> [WIP] Fstab agent - handle better white space only lines (bsc#1030425)

library/cwm/src/lib/cwm/custom_widget.rb, library/cwm/src/lib/cwm/rspec.rb, library/cwm/test/abstract_widget_test.rb, library/cwm/test/custom_widget_test.rb, library/cwm/test/widgets_test.rb, package/yast2.changes, package/yast2.spec
to enable stupid but easy test coverage
=> Shared RSpec examples for CWM widgets

library/cwm/src/lib/cwm/abstract_widget.rb, library/cwm/src/lib/cwm/custom_widget.rb, library/cwm/src/lib/cwm/tabs.rb, library/cwm/src/lib/cwm/widget.rb, library/cwm/src/modules/CWM.rb
I needed to understand this for implementing the CWM::TreePager switching. Even the current situation is a bit tricky.
- UITerm: can be passed as is to Yast::UI methods
- WidgetTerm: contains instances of CWM::AbstractWidget
- StringTerm: contains strings which identify the old style hash based CWM widgets
=> Document the 3 kind of Terms used in CWM

library/packages/src/lib/packages/update_messages_view.rb, package/yast2.changes, package/yast2.spec
Ruby gettext cannot extract translatable texts from interpolated strings.
- 3.2.30
=> Translation fix (bsc#1038077)

.gitignore, .travis.yml, Dockerfile, library/packages/test/file_conflict_callbacks_test.rb
- This is basically a copy from `master`
- Only `yastdevel/ruby:sle12-sp2` is used instead of `yastdevel/ruby`
- Testsuite and .gitignore updated
=> Docker sle12 sp2

library/cwm/src/Makefile.am
I wanted to use it in https://github.com/yast/yast-partitioner/pull/5 and found it was missing :-/
=> Include cwm/rspec in the RPM

library/cwm/src/lib/cwm/rspec.rb, package/yast2.changes
- No version change, for using it at Travis commit to YaST:Head is enough
Originally I wanted to put the `if subject.respond_to?(method)` check before the `describe` block so RSpec does not print bogus test results when the method is not defined. But that resulted in a `#let or #subject called without a block` error, so it seems it cannot be improved in that way.
=> Additional "CWM::RadioButtons" tests

library/systemd/test/systemctl_test.rb, package/yast2.changes
Avoid possible timeout error in tests.
See problem with s390: https://build.opensuse.org/package/live_build_log/YaST:storage-ng/yast2/openSUSE_Factory_zSystems_images/s390x.
=> Avoid timeout error

library/general/src/scrconf/run_ifconfig.scr, package/yast2.changes, package/yast2.spec
- Make "inet" section optional, handle additional whitespace characters
- The fix has been confirmed by customer [bsc#811760#c13](https://bugzilla.suse.com/show_bug.cgi?id=811760#c13)
- I grepped all YaST sources, the agent is used only at **one** place in whole YaST, in the `instserver` module - so the change is safe, it cannot break anything else™.
- 3.3.7
=> Improved run_ifconfig.scr parser (bsc#811760)

package/yast2.changes, package/yast2.spec, scripts/yast2-funcs
- Fixes https://bugzilla.suse.com/show_bug.cgi?id=1051664
- The `DMZ` theme has been replaced by `DMZ-White` and `DMZ-Black`.
- Version 4.0.0
=> Fixed the cursor theme in the installation (bsc#1051664)

library/general/src/Makefile.am, library/general/src/lib/ui/text_helpers.rb, library/general/test/Makefile.am, library/general/test/text_helpers_test.rb, package/yast2.changes, package/yast2.spec
I added a wrap_text method to some time ago yast/yast-network#403
https://github.com/yast/yast-network/pull/403/files#diff-72293d1fba24e0701afaa84e81e1af12R734
At that moment we commented that would be better to have it in a common place. 
This bug https://bugzilla.suse.com/show_bug.cgi?id=1055643 remembered me it, so I just take the opportunity to move to a common UI module.
There is a similar method in Rails ActionView https://github.com/rails/rails/blob/0732ea7136da43cf3d84d8ce20dd7105a16e78b0/actionview/lib/action_view/helpers/text_helper.rb#L258 which looks better, but for the this bug I just moved the current functionality.
=> Wrap text (bsc#1055643)

library/control/src/modules/WorkflowManager.rb, library/control/test/workflow_manager_test.rb, library/cwm/src/lib/cwm/dialog.rb, library/cwm/src/modules/CWM.rb, package/yast2.changes, package/yast2.spec
This PR add support to:
* Merge product's workflow (moving the logic from [ProductSelector widget](https://github.com/yast/yast-installation/blob/master/src/lib/installation/dialogs/product_selection.rb#L45).
* Extends CWM::Dialog to support disabling buttons.
=> Merge workflow and add support to disable buttons on CWM::Dialog

library/system/src/lib/yast2/fs_snapshot.rb, library/system/test/fs_snapshot_test.rb, package/yast2.changes, package/yast2.spec
Part of https://trello.com/c/ytK5Yoe4/554-5-storageng-installation-to-root-subvolume
It's needed by other PRs referenced there.
The first commit looks big but it only moves code to avoid tons of `def self.xxx` and `:private_class_method`. So better review in a commit basis.
=> Snapper config

library/systemd/src/lib/yast2/systemctl.rb, library/systemd/src/lib/yast2/systemd_unit.rb, library/systemd/src/modules/systemd_service.rb, library/systemd/src/modules/systemd_socket.rb, library/systemd/src/modules/systemd_target.rb, library/systemd/test/systemd_unit_test.rb, package/yast2.changes, package/yast2.spec
References
- https://trello.com/c/IiJYLiBk/1110-3-speedup-reading-services-state-services-manager 
- [bsc#1045658](https://bugzilla.suse.com/show_bug.cgi?id=1045658)
Changes
- add `SystemdService.find_many` for a speed-up
- `SystemdUnit` fix for units with multiple dots in name
- consistent logging of `systemctl` calls
- better Yardoc
=> Speed up service manager

library/packages/src/modules/PackageCallbacks.rb, library/packages/test/package_callbacks_test.rb, package/yast2.changes, package/yast2.spec
This simple fix should solve [bsc#1054663](https://bugzilla.opensuse.org/show_bug.cgi?id=1054663). This callback is only called when validation fails and it should be ignored if Insecure=1.
Finally, it does not share code with [AutoYaST counterpart](https://github.com/yast/yast-autoinstallation/blob/676f7f03c907d212c483731651f1e5edfed041b5/src/modules/AutoInstall.rb#L326) because requirements are totally different.
=> Handle GPG check during installation

library/systemd/src/lib/yast2/systemd_unit.rb, package/yast2.changes, package/yast2.spec
yast2-dhcp-server and yast2-samba-server log the exact command used by
us in their tests :-(
=> Revert to using separate property options to keep old tests working.

library/cron/src/servers_non_y2/ag_cron, package/yast2.changes, package/yast2.spec
[bsc#1061620](https://bugzilla.suse.com/show_bug.cgi?id=1061620)
https://trello.com/c/EVu9oWwb
BTW the whole ag_cron + Yast::CronClass combo seem to be unused. We may want to drop them.
=> Stop using tmpnam, it is no longer supported in perl 5.26

library/network/src/lib/network/susefirewall.rb, library/network/src/lib/network/susefirewall2.rb, library/network/test/susefirewall_test.rb, library/network/test/susefirewalld_test.rb, package/yast2.changes, package/yast2.spec
This is just an early release of a possible fix for https://bugzilla.novell.com/show_bug.cgi?id=1037214
- [Trello Card](https://trello.com/c/HN5J9P4x)
What I have seen by now is that SuSEFirewallIsInstalled() returns true not only if the package has been Installed but even if it has only be selected in initial Stage.
Currently Lan.Write checks if the FW is installed to proceed with fw configuration.
- https://github.com/yast/yast-network/blob/SLE-12-SP2/src/modules/Lan.rb#L603
```
def Write
...
fw_is_installed = SuSEFirewall4Network.IsInstalled
if fw_is_installed
...
SuSEFirewall4Network.Write
...
```
The network dialog also show you some FW options if it is already installed.
We could do a simple [workaround](https://github.com/yast/yast-network/pull/576) in yast2-network …
=> SuSEFirewallClass: IsInstalled does not return true if Pkg is selected

library/general/src/modules/Linuxrc.rb, library/general/test/linuxrc_test.rb, package/yast2.changes, package/yast2.spec
- bsc#1055279
- Arguments "vnc", "ssh" were expected lower-cased in the function, but the code uses them ALSO upper-cased
- I've fixed it in a way that it just does not matter
- Plus if the argument is unknown, error is raised
- Plus it's covered by unit tests
=> Fixing "disable_remote" function in Linuxrc

library/network/src/lib/y2firewall/firewalld/api.rb, package/yast2.changes, package/yast2.spec
- Avoid to call firewallctl if it is not installed.
- related to https://build.suse.de/package/live_build_log/SUSE:SLE-15:GA:Staging:Y/yast2-nfs-client/standard/x86_64
=> Firewalld API: running? return false if the package is not installed

library/network/src/lib/y2firewall/firewalld.rb, library/network/src/lib/y2firewall/firewalld/zone.rb, library/network/src/modules/NetworkInterfaces.rb, library/network/test/y2firewall/firewalld/zone_test.rb, package/yast2.changes, package/yast2.spec, test/test_helper.rb
- needed in https://github.com/yast/yast-network/pull/586
- trello card: https://trello.com/c/Yw5lJeGN/1092-5-firewall-firewalld-is-the-new-susefirewall-support-for-network-installer
- Removed the knowledge of zones from SuSEFirewall module, and remote the ZONE attribute if empty.
- The zone class will have more responsibilities but by now I have just commit the strictly necessary for current code.
=> Added known zones to firewalld (fate#323460)

library/network/src/modules/NetworkInterfaces.rb, library/network/testsuite/tests/NetworkInterfaces2.out, package/yast2.changes, package/yast2.spec
Replaces https://github.com/yast/yast-yast2/pull/527
The fix replaces ifcfg only type detection by full type detection when building device config cache. type detection based on ifcfg can differ from the reality mainly in situations when the config file contains some unexpected option. E.g. when user leaves `ETHERDEVICE=eth0` in eth device's config file then ifcfg based type detection can report type `vlan` but correct one is `eth`.
=> Use full type detection when building device cache

library/network/src/lib/y2firewall/firewalld/api.rb, package/yast2.changes, package/yast2.spec
Added convenient methods to not fail with query methods ([bsc#1070559](https://bugzilla.suse.com/show_bug.cgi?id=1070559)):
=> Firewalld API: Convenient methods for query commands (bsc#1070559)

library/network/src/lib/y2firewall/firewalld/api.rb, package/yast2.changes, package/yast2.spec
Some packages (dns-server / nfs-client / nfs-server / nis-client / squid) are not building correctly because the output is nil in most of the cases (which means a clear problem of mocking that we should solve when modified) but this will just prevent from crashing
=> Firewalld API: use string command where needed (bsc#1070559)

library/system/src/lib/yast2/column_config_file.rb, library/system/src/lib/yast2/commented_config_file.rb, library/system/src/lib/yast2/etc_fstab.rb, library/system/test/column_config_file_test.rb, library/system/test/commented_config_file_test.rb, library/system/test/data/fstab/demo-fstab, library/system/test/data/fstab/demo-fstab-2-expected, library/system/test/data/fstab/demo-fstab-no-header, library/system/test/data/fstab/demo-sudoers, library/system/test/etc_fstab_entry_test.rb, library/system/test/etc_fstab_test.rb, library/system/test/test_helper.rb, package/yast2.changes, package/yast2.spec
Imported classes from my upstream repository:
https://github.com/shundhammer/ruby-commented-config-file
That repo also contains some more examples (and general-purpose diff classes that I didn't import here and now) and of course some introductory comments.
Those classes are now used for the SLE-12-SP3 yast-nfs-client if it runs in standalone mode (i.e. outside the expert partitioner); see also the related PR against yast-nfs-client here: https://github.com/yast/yast-nfs-client/pull/56
=> Infrastructure for preserving comments in config files

library/system/src/Makefile.am, library/system/test/Makefile.am, package/yast2.changes, package/yast2.spec
Debugging the failing tests for yast2-nfs-client showed that the relevant new files were missing in this yast2 package; it turned out that that package is still using the AutoTools, not simply collecting all *.rb files like most of our other Ruby packages.
This commit now collects those files.
=> Added missing files to Makefile.am

library/network/src/lib/y2firewall/firewalld.rb, package/yast2.changes, package/yast2.spec
* 406c04e4 return empty hash if package has not been installed
=> [Review] Request from 'schubi2' @ 'yast/yast-yast2/review_180112_missing_package'

package/yast2.changes, package/yast2.spec, scripts/yast2
Backport [bsc#1075535](https://bugzilla.suse.com/show_bug.cgi?id=1075535).
=> Fix running GNOME center SLE 12 SP3

library/control/src/modules/ProductFeatures.rb, library/control/test/ProductFeatures_test.rb, package/yast2.changes, package/yast2.spec
quoting first commit message:
In general problem is that system role selection clears overlay before
creating dialog, but it does it when going back and also when going
forward. So result is that when going back it is properly cleared and
then when going forward when different extensions is chosen, it is again
cleared, but with invalid backup. So this change in the end apply backup
only when going back.
=> Fix overlay

library/network/src/Makefile.am, library/network/src/lib/y2firewall/firewalld.rb, library/network/src/lib/y2firewall/firewalld/api.rb, library/network/src/lib/y2firewall/firewalld/api/services.rb, library/network/src/lib/y2firewall/firewalld/api/zones.rb, library/network/src/lib/y2firewall/firewalld/relations.rb, library/network/src/lib/y2firewall/firewalld/service.rb, library/network/src/lib/y2firewall/firewalld/zone.rb, library/network/src/modules/CWMFirewallInterfaces.rb, library/network/src/modules/firewalld_wrapper.rb, library/network/test/cwm_firewall_interfaces_test.rb, library/network/test/y2firewall/firewalld/zone_test.rb, library/network/test/y2firewall/firewalld_test.rb, package/yast2.changes, package/yast2.spec
- [Trello Card](https://trello.com/c/99OkErr6/1093-8-firewall-firewalld-is-the-new-susefirewall-cwm)
The CWMFirewallInterfaces have been maintained and just adapted to work with firewalld, the only big dfiference is that CWMFirewallInterfaces.CreateOpenFirewallWidget will return a empty VBox() if some service is not supported preventing modifications:
=> Replace SuSEFirewall2 by firewalld in CWMFirewallInterfaces

library/packages/src/modules/Product.rb, package/yast2.changes, package/yast2.spec
- This is a workaround for reading the base product in offline migration via SCC, we need to use the `system-installation()` provides for correctly detecting the base products
- We need some functionality from the `yast2-packager` but as we cannot depend on that package (it would introduce a circular dependency) there is a simple `LoadError` check, the `yast2-packager` is included in the inst-sys anyway
- Because the package submission deadline is today we need to merge it ASAP
- The fix up can be done later, we need this feature for the testers (added `FIXME` at least)
- Tested manually in the SLES12-SP3 -> SLES15 offline migration
=> Base product selection fix

library/network/src/lib/y2firewall/firewalld/api.rb, package/yast2.changes, package/yast2.spec
- [Trello Card](https://trello.com/c/99OkErr6/1093-8-firewall-firewalld-is-the-new-susefirewall-cwm)
If the firewall is not running it does not need to be reloaded at all so makes more sense to return true instead of false.
=> Firewalld API: reload & complete_reload return true in offline mode

library/general/src/lib/installation/auto_client.rb, library/general/test/auto_client_test.rb, package/yast2.changes, package/yast2.spec
- The packages default was an [] but it is expected to be redefined as a hash with "install" and/or remove "remove" creating some confusion specially when you are not used to AutoClients
- This PR tries to clarify it a little.
=> Auto client packages modified defaults (bsc#1077987)

library/packages/src/Makefile.am, library/packages/src/lib/y2packager/product.rb, library/packages/src/lib/y2packager/product_reader.rb, library/packages/src/lib/y2packager/product_sorter.rb, library/packages/src/modules/Product.rb, library/packages/test/Makefile.am, library/packages/test/data/products-sles15.yml, library/packages/test/lib/product_reader_test.rb, library/packages/test/lib/product_sorter_test.rb, package/yast2.changes, package/yast2.spec
- Move some code from `yast2-packager` to `yast2` - it is required in `Product.rb` module
- It cannot depend on `yast2-packager` because it would create `yast2` <-> `yast2-packager` circular dependency
- Note: I'm keeping the `Y2Packager` namespace as the `Product` class is currently defined  in `Packages::Product` and `Y2Packager::Product`. These should be unified/merged later.
=> Y2packager integration

library/types/src/modules/Punycode.rb, library/types/test/Makefile.am, library/types/test/punycode_test.rb, package/yast2.changes, package/yast2.spec
Replaces idconv with simpleidn. It's easier to review this changes in a per-commit basis.
=> Idnconv to simpleidn

library/network/src/Makefile.am, library/network/src/lib/y2firewall/helpers/interfaces.rb, library/network/src/modules/CWMFirewallInterfaces.rb, library/network/test/y2firewall/helpers/interfaces_test.rb, package/yast2.changes, package/yast2.spec
- Some yast2-modules handle the ports opening directly instead of through the CWMFirewallInterfaces widget. This helpers are for them.
Needed by https://github.com/yast/yast-services-manager/pull/138
=> Added firewall interfaces helpers

library/packages/src/lib/y2packager/product.rb, library/packages/test/y2packager/product_test.rb, package/yast2.changes, package/yast2.spec
Extend `Y2Packager::Product` to get the list of available translations from libzypp.
PBI: https://trello.com/c/VjEpcE8x/
=> Add product license locales

Dockerfile, library/types/src/modules/URL.rb, library/types/test/url_test.rb, package/yast2.changes, package/yast2.spec
- See L3 bug https://bugzilla.suse.com/show_bug.cgi?id=1077310
- The problem has been tracked down to
`URL.Build(URL.Parse("dvd:/"))` => `"dvd:///"` (OK)
`URL.Build(URL.Parse("hd:/"))` => `"hd://"` (wrong, rejected by libzypp)
- The expected output is `URL.Build(URL.Parse("hd:/"))` => `"hd:///"`
- Use the [same URL schema list as in libzypp](https://github.com/openSUSE/libzypp/blob/d9c97b883ac1561225c4d728a5f6c8a34498d5b9/zypp/Url.cc#L184-L190), i.e. also added `iso` and `dir` schemes
=> Update the URL schemes without host name (bsc#1077310)

library/network/src/lib/y2firewall/firewalld/zone.rb, package/yast2.changes, package/yast2.spec
- https://bugzilla.suse.com/show_bug.cgi?id=1082246
=> Added missing textdomain to zone class for translations (bsc#1082246)

library/general/src/modules/Report.rb, library/general/test/report_test.rb, package/yast2.changes, package/yast2.spec
Part of https://trello.com/c/T5rxuHfg/300-2-sles15-p1-1082542-build4731storage-ng-delete-lvmlv-failed-when-reinstall-on-encrypted-lvm
See it in action in a yast-storage-ng callback:
The same popup using the timeout from `Report`
=> Make possible to use Yast2::Popup from Report

library/packages/src/lib/y2packager/license.rb, library/packages/test/y2packager/license_test.rb, package/yast2.changes, package/yast2.spec
Replace MD5 with SHA1 when determining whether a license was accepted or not,
as requested in [fate#325461](https://fate.suse.com/325461).
=> Use SHA2 instead of MD5

library/packages/src/lib/y2packager/product_upgrade.rb, library/packages/test/y2packager/product_upgrade_test.rb, package/yast2.changes, package/yast2.spec
- Do not use the solver for finding the best product upgrade
- It does not work correctly in the SLES + sle-module-hpc => SLES_HPC case as the solver finds the new SLES and selects the SLES => SLES upgrade.
- Use the only product available or search from the hardcoded list
- This is a quick fix for SLE15-GA, for SLE15-SP1 we should find a better solution (avoid hardcoding)
- See https://bugzilla.suse.com/show_bug.cgi?id=1086734
- Tested manually in a SLES12-SP3 + sle-module-hpc upgrade to SLE15, see the screenshots below
- Additionally I have added also the openSUSE => SLES upgrade support (not tested)
- 4.0.67
Originally the standard SLES product was selected for upgrade as you can see in the license agreement dialog:
With the fix the SLES_HPC product is displayed:
And later the …
=> Do not use the solver for finding the best product upgrade (bsc#1086734)

library/cwm/src/modules/CWMServiceStart.rb
Lingshan just asked about CWMServiceStart and it took me a while to find the modern API, so here's a shortcut.
=> Point users of CWMServiceStart to the replacement API.

package/yast2.changes, package/yast2.spec, scripts/save_y2logs
Kernel messages can show up in /var/log/boot.msg (linuxrc redirects there) and
/var/log/messages (syslog).
Since bsc#1085212 linuxrc can run udev in debug mode. In this case udev logs
into /var/log/udev.log.
=> save_y2logs: save kernel messages and udev log (bsc#1089647, bsc#1085212)

library/packages/src/lib/y2packager/product_reader.rb, package/yast2.changes, package/yast2.spec
- Evaluate *all* `system-installation()` provides, not only the first one
- This allows sharing one installation package between multiple products, eg. have a single `skelcd-foo` providing `system-installation() = foo1` and  `system-installation() = foo2` instead of the duplicated `skelcd-foo1` and `skelcd-foo2` just with different `system-installation()` values.
- Use case: `SLE-HPC` and `SLES_HPC` can share the `skelcd-control-SLES4HPC` package, see
https://bugzilla.suse.com/show_bug.cgi?id=1092965 for the details
- 4.0.74
- Tested manually by Egbert, see https://bugzilla.suse.com/show_bug.cgi?id=1092965#c2
=> Support multiple "system-installation()" provides (bsc#1092965)

library/systemd/src/modules/systemd_service.rb, library/systemd/test/data/apparmor_and_cups_properties, library/systemd/test/systemd_service_test.rb
Retrieve properties properly when services are loaded using `find_many_at_once`.
=> Fix find_many_at_once to retrieve service properties

library/system/src/lib/yast2/system_service.rb, library/system/test/yast2/system_service_test.rb, library/systemd/src/modules/systemd_service.rb, library/systemd/test/systemd_service_test.rb
* SystemService store changes in memory and commit them to the underlying system
when `#save` is called.
* The `#socket` method is moved back to the `SystemdService` class.
=> Add a SystemService#save method

library/network/src/lib/network/susefirewall2.rb
Contributing more as I learn.  Fixed some typos in the comments, made some minor adjustments for readability.
Now **this** is what I call good commenting.
I have just barely begun to study Ruby, have not coded in 30 years (other than html markup and some related), last languages I worked in were Pascal and Assembler, some C.
Yet, this was so well documented that I was able to actually read the lines of code and understand what they were doing, and how they were doing it.
With documentation like this, a relative "newbie" to coding, such as I, would easily be able to work on this kind of code to make fixes.
=> Fix typos and readability

doc/autodocs/Makefile.am, library/commandline/doc/autodocs/Makefile.am, library/control/doc/autodocs/Makefile.am, library/cron/doc/autodocs/Makefile.am, library/cwm/doc/autodocs/Makefile.am, library/desktop/doc/autodocs/Makefile.am, library/gpg/doc/autodocs/Makefile.am, library/log/doc/autodocs/Makefile.am, library/network/doc/autodocs/Makefile.am, library/packages/doc/autodocs/Makefile.am, library/runlevel/doc/autodocs/Makefile.am, library/sequencer/doc/autodocs/Makefile.am, library/system/doc/autodocs/Makefile.am, library/types/doc/autodocs/Makefile.am, library/wizard/doc/autodocs/Makefile.am, library/xml/doc/autodocs/Makefile.am, package/yast2.changes, package/yast2.spec
- Similar fix to https://github.com/yast/yast-country/pull/177, this is an `yast2` specific fix for the updated `yard`.
- Tested manually with the `osc build SLE-12-SP1_Update` (to build agains SP1-Updates), builds fine now.
=> Pass absolute paths to "yard"

library/systemd/src/lib/yast2/system_service.rb, library/systemd/test/yast2/system_service_test.rb
- Avoid to reset or refresh when the changes cannot be applied
=> Fix SystemService#save

library/packages/src/modules/PackageCallbacks.rb, package/yast2.changes, package/yast2.spec
- Do not display "download failed" warning when using unsigned packages.
- Just skip the warning dialog when user ignored signature error
- Added extra logging when signature verification fails
- 4.0.81
=> Do not display "download failed" error (bsc#1096027)

library/systemd/src/lib/yast2/system_service.rb, library/systemd/src/lib/yast2/systemd_unit.rb, library/systemd/src/modules/systemd_service.rb, library/systemd/test/systemd_service_test.rb, library/systemd/test/yast2/system_service_test.rb, package/yast2.changes, package/yast2.spec
`Yast2::SystemService#start_modes`:
* `Yast2::SystemService#start_modes` returns all known modes as there is not enough information
in order to find out which modes are supported.
* When trying to save the start mode, an error is registered if the socket is not found.
Additionally, the socket detection is not done using `TriggeredBy` anymore, as it won't work when the socket is stopped. Currently we are using a *name based* approach that might be not 100% reliable in the future. Some research is needed in order to find a better mechanism which, ideally, works during 1st stage too. This fix should be backported to `SLE-15-GA`.
=> Improve on-demand handling during 1st stage

library/systemd/src/Makefile.am, library/systemd/src/lib/yast2/system_service.rb, library/systemd/src/lib/yast2/systemd_socket_finder.rb, library/systemd/src/modules/systemd_service.rb, library/systemd/src/modules/systemd_socket.rb, library/systemd/test/Makefile.am, library/systemd/test/data/apparmor_and_cups_properties, library/systemd/test/data/cups_service_properties, library/systemd/test/systemd_service_test.rb, library/systemd/test/systemd_socket_test.rb, library/systemd/test/yast2/system_service_test.rb, library/systemd/test/yast2/systemd_socket_finder_test.rb, package/yast2.changes, package/yast2.spec
* Introduce a new `SystemdSocketFinder` which speeds up the detection of
service sockets.
* Does not fetch TriggeredBy anymore as it was not reliable.
* SystemdService.find_many_at_once does not return nil values
=> Improve systemd socket detection

library/systemd/src/lib/yast2/systemctl.rb, package/yast2.changes, package/yast2.spec
> Since systemd by itself has a 30 sec timeout, YaST should add some more
> seconds to allow for systemctl to exit gracefully even if it has a
> timeout and not just kill the systemctl command just one seconds before
> it would time out itself.
See https://bugzilla.suse.com/show_bug.cgi?id=1098910#c3
---
Related to https://trello.com/c/udasbOtt/135-lhf-osdistribution-p4-1098910-yast2-services-manager-internal-error-writing-run-configuration-to-disk
=> Increase the timeout for systemctl command execution

library/cwm/src/modules/CWM.rb, package/yast2.changes, package/yast2.spec
`:next` button was consider the same than `:ok`, and when the dialog used `:ok` it returned `:next`. Now this is avoided because some client code expects `:ok` being returned.
=> Fix return value

library/network/src/lib/y2firewall/firewalld/api/zones.rb, library/network/test/y2firewall/firewalld/api/zones_test.rb, library/network/test/y2firewall/firewalld/api_test.rb, package/yast2.changes, package/yast2.spec
- https://bugzilla.suse.com/show_bug.cgi?id=1108628
With the offline cmd (firewall-offline-cmd), the `--remove-service` call can be used only with the default zone, in other case, it has to be called as `--remove-service-from-zone`
See: https://firewalld.org/documentation/man-pages/firewall-offline-cmd.html
Bug introduced when extending the API:
https://github.com/yast/yast-yast2/pull/819/files#diff-fade9352dfa13333ea0f66a045fe53eaL217
=> Fix firewall-offline-cmd call for removing services from zones (bsc#1108628)

library/control/src/modules/WorkflowManager.rb, library/control/test/workflow_manager_test.rb, library/packages/src/lib/y2packager/product.rb, library/packages/src/lib/y2packager/product_reader.rb, package/yast2.changes, package/yast2.spec
- See https://bugzilla.suse.com/show_bug.cgi?id=1101016
The full functionality depends also on these other pull requests:
- https://github.com/yast/yast-packager/pull/374
- https://github.com/yast/yast-installation/pull/741
- Tested manually with a customized `skelcd-control-SLES` package (Knut, thanks! :wink: ), applied using a DUD with `self_update=` boot parameter pointing to a repository with the new skelcd.
- Also tested an AutoYaST installation
- The extra addon repository is removed at the end
=> Improved self-update to use some packages as an add-on (bsc#1101016)

library/network/src/lib/y2firewall/firewalld/interface.rb, library/network/src/modules/CWMFirewallInterfaces.rb, library/network/test/cwm_firewall_interfaces_test.rb, library/network/test/test_helper.rb, library/network/test/y2firewall/firewalld/interface_test.rb, library/network/test/y2firewall/helpers/interfaces_test.rb, package/yast2.changes, package/yast2.spec
* `Y2Firewall::Firewalld::Interface#zone` returns an object.
* Add unit tests to the class.
=> Return zone object

library/systemd/src/lib/yast2/service_widget.rb, package/yast2.changes, package/yast2.spec
- When changing the label from "Active" to "Inactive" the longer label was not displayed correctly in the ncurses UI.
- Use `HSpacing(1)` instead of `Label(" ")` - if there is lack of space libyui first decreases/removes the spacings, this might be enough without cutting off the labels
- openQA: https://openqa.opensuse.org/tests/765329#step/yast2_dns_server/35
- bugzilla: https://bugzilla.suse.com/show_bug.cgi?id=1110407
- 4.1.20
=> Make the service status label stretchable (bsc#1110407)

library/system/src/clients/view_anymsg.rb, package/yast2.changes, package/yast2.spec
- Log viewer: replace invalid UTF-8 characters from the displayed log to avoid a crash
- The crash can be reproduced with `printf '\255' >> /var/log/messages` command
- See https://bugzilla.suse.com/show_bug.cgi?id=1110549
- Works correctly also with the ANSI color removal
- 4.0.99
=> Log viewer: replace invalid UTF-8 characters (bsc#1110549)

library/network/src/modules/CWMFirewallInterfaces.rb, library/network/test/cwm_firewall_interfaces_test.rb, package/yast2.changes, package/yast2.spec
Since this [PR](https://github.com/yast/yast-yast2/pull/818) was merged, the `firewalld` instance already knows about the supported list of services, so, we can avoid the extra `API` calls made by the widget improving the user experience.
Example from https://github.com/SUSE/yast2-rmt/pull/34
With more services it is probably easiest to appreciate.
=> Check if a service is supported from the list of current ones

library/network/src/modules/CWMFirewallInterfaces.rb, package/yast2.changes, package/yast2.spec
yast2-rmt is extending the class for having these private methods, so why not just public them?
https://github.com/SUSE/yast2-rmt/commit/aa1f4b96b1ca96301515cf7f2d405c5eb1ce7eaa
https://github.com/yast/yast-yast2/blob/5ea19cfc81666603b1919cd05aed0aef986268eb/library/network/src/modules/CWMFirewallInterfaces.rb#L910-L955
=> Make current state methods public

library/packages/src/modules/PackagesUI.rb, package/yast2.changes, package/yast2.spec
For https://trello.com/c/zkLss9CU/460-tw-1115745-p3-yast2-software-management-could-not-load-plug-in-qt-pkg.
=> check return value of OpenDialog to prevent crash

library/system/src/lib/yast2/execute.rb, library/system/test/execute_test.rb, package/yast2.changes, package/yast2.spec
Related to PBI: https://trello.com/c/AzEDChwZ/520-issues-from-yast-audit-systemlog-backtickslog
`Yast::Execute.locally!.stdout(...)`
`Yast::Execute.on_target!.stdout(...)`
`Yast::Execute.stdout(...)`
=> Extend Yast::Execute API

library/systemd/src/lib/yast2/systemctl.rb, package/yast2.changes, package/yast2.spec
Manually tested (yast2 clone_system does not show an error popup anymore).
=> avoid use of shellescape function on non string types (bsc#1119678)

library/control/src/modules/ProductControl.rb, library/control/src/modules/ProductFeatures.rb, package/yast2.changes, package/yast2.spec
Add a `configuration_management` to the control file. Related to https://github.com/yast/yast-installation-control/pull/76.
https://fate.suse.com/322722
=> Add configuration_management section to control file

library/cwm/src/lib/cwm/service_widget.rb, library/systemd/src/lib/yast2/service_widget.rb, library/systemd/test/yast2/service_widget_test.rb, package/yast2.changes
At the time to continue the work (yast/yast-firewall#109) started by @teclator in the yast-firewall module, I realized that the ServiceWidget has not a help text defined yet. In fact, none of modules that already use the new ServiceWidget shows any related help.
That's the reason why I am proposing to add a generic text, vía the `help` widget method, to all of them.
=> Add missing help text for ServiceWidget

library/packages/src/lib/y2packager/release_notes_fetchers/rpm.rb, library/packages/test/y2packager/release_notes_fetchers/rpm_test.rb, package/yast2.changes, package/yast2.spec
- Related to https://bugzilla.suse.com/show_bug.cgi?id=1112866
- The `y2log` did not tell much and  I could not reproduce the problem locally, the release notes were displayed properly. :worried:
- But when checking the code I found a potential issue, the old installed package does not provide the `release-notes` tag so in theory when using the installed package as the first found it would not match.
Running the code in the debugger found these dependencies:
```
[
{"provides"=>"release-notes-sles = 12.3.20170706-1.2"},
{"requires"=>"dejavu-fonts"},
{"requires"=>"google-opensans-fonts"},
{"requires"=>"rpmlib(CompressedFileNames) <= 3.0.4-1"},
{"requires"=>"rpmlib(PayloadFilesHavePrefix) <= 4.0-1"},
{"requires"=>"rpmlib(PayloadIsLzma) <= 4.4.6-1"}
],
[
{"provides"=>"release-notes() = …
```
=> Ignore the old release notes packages (bsc#1112866)

library/cwm/examples/date_time.rb, library/cwm/src/lib/cwm/common_widgets.rb, library/cwm/src/lib/cwm/rspec.rb, library/cwm/src/modules/CWM.rb, package/yast2.changes, package/yast2.spec
- Trello Card: https://trello.com/c/DS4ULBxR/541-finish-implementation-of-input-widgets
This PR adds CWM widgets for `Date` and `Time` fields.
**Note:** It seems that both are now supported in ncurses and this [check](https://github.com/yast/yast-journal/blob/66f6eebee05903264b9893193a0cf574c4541694/src/lib/y2journal/time_helpers.rb#L57) is not needed probably [since](https://github.com/libyui/libyui-ncurses/commit/e1d3e8043130c64ca2217622f607ff274ab81eb6)
<p align="center">
</p>
=> Date and time widgets

library/network/src/lib/y2firewall/firewalld/interface.rb, library/network/src/lib/y2firewall/firewalld/zone.rb, library/network/src/modules/NetworkInterfaces.rb, library/network/test/y2firewall/firewalld/interface_test.rb, library/network/test/y2firewall/firewalld/zone_test.rb, package/yast2.changes, package/yast2.spec
- Do not delete the **ZONE** attribute when empty ("default zone")
- Added methods to `Interface` and `Zone` for changing the current map.
=> Interface zone mapping improvements

library/commandline/test/commandline_test.rb, library/network/test/firewalld_wrapper_test.rb, library/packages/src/lib/y2packager/release_notes_fetchers/rpm.rb, package/yast2.changes, package/yast2.spec
- The `./y2packager/release_notes_fetchers/rpm_test.rb` unit test randomly failed in OBS (see #895).
From a debugging session:
```
(byebug) p = File.join(directory, "**", "RELEASE-NOTES.{#{langs.join(",")}}.#{prefs.format}")
"/tmp/d20190215-22316-ra8tss/**/RELEASE-NOTES.{de_DE,de,en}.txt"
(byebug) Dir.glob(p)
["/tmp/d20190215-22316-ra8tss/usr/share/doc/release-notes/dummy/RELEASE-NOTES.en.txt",
"/tmp/d20190215-22316-ra8tss/usr/share/doc/release-notes/dummy/RELEASE-NOTES.de.txt"]
```
So the glob for the `RELEASE-NOTES.{de_DE,de,en}.txt` files returns `"RELEASE-NOTES.en.txt", "RELEASE-NOTES.de.txt"` files (in this order!). So the order of the files might be different than in the input glob, the code does not expect this and uses the first one (via `.first`).
- The commandline tests always …
=> Fixed evaluating release notes

library/general/src/scrconf/run_ifconfig.scr, library/network/src/modules/NetworkPopup.rb, package/yast2.changes, package/yast2.spec
-   https://bugzilla.suse.com/show_bug.cgi?id=1127138
-   https://trello.com/c/plarcsbX/770-1-sle15-sp1-no-mkdir-is-not-in-usr-sbin
=> Don't use nonexisting programs

library/commandline/test/commandline_test.rb, library/general/src/modules/Report.rb, package/yast2.changes, package/yast2.spec
- It is related to this change: https://github.com/yast/yast-ruby-bindings/pull/227
- It turned out that the `Report.LongError` call did not support the command line mode (as the `Report.Error` does), so after changing that in the global exception handler the popup was displayed even in the command line mode.
- Added a debugging hint into `commandline_test.rb`, running `byebug` is a bit tricky there.
- Switched from `STDOUT` (the default stdout stream) to `$stdout` (the current stdout stream) (Just a minor thing, but it would handle possible stdout redirection better.)
=> Fixed command line error reporting, fixed testsuite

library/packages/src/lib/y2packager/product_reader.rb, library/packages/test/y2packager/product_reader_test.rb, package/yast2.changes, package/yast2.spec
- Upgrading SLE15-SP1 to SLE15-SP1 does not work, "No product to upgrade found"
- https://bugzilla.suse.com/show_bug.cgi?id=1128459
- Do not remove products with different status, they are filtered later when querying the installed or available products
- Added unit test
- Tested manually
=> Fixed removing product duplicates (bsc#1128459)

library/packages/src/lib/y2packager/product_reader.rb, library/packages/test/y2packager/product_reader_test.rb, package/yast2.changes, package/yast2.spec
- https://bugzilla.suse.com/show_bug.cgi?id=1128901
- Ignore the "-_." characters, ignore case (like in https://en.opensuse.org/SDB:Linuxrc#Passing_parameters)
- 4.1.64
=> Process the "specialproduct" value like a linuxrc parameter (bsc#1128901)

library/packages/src/lib/y2packager/product_reader.rb, library/packages/test/y2packager/product_reader_test.rb, package/yast2.changes, package/yast2.spec
- The same products with the available and selected status must be treated as duplicate products.
- Fixes duplicate "Tumbleweed" products offered to install
- Related to the previous fix #908 
- https://bugzilla.suse.com/show_bug.cgi?id=1129257
- 4.1.65
- There are two TW products, one with the `i586` arch and one with the `x86_64` arch. These are considered as duplicates at the beginning. (The libzypp will select the correct architecture automatically when selecting the product, we can ignore it.)
- But after selecting the `x86_64` product to installation the previous change (#908) caused that because of the different status they are not considered as duplicates anymore.
- The fix is to consider the `selected` and `available` states as the same. Similarly for `installed` and `removed`.
=> Fixed evaluating the base product (bsc#1129257)

package/yast2.changes, package/yast2.spec
Add the `tar` dependency to `yast2-logs`.
_Tested manually_
Related to https://bugzilla.suse.com/show_bug.cgi?id=1125142
=> Require `tar` for yast2 logs

Dockerfile
- Experimentally use the Docker image built by OBS (https://build.opensuse.org/package/show/YaST:Head/ci-ruby-container)
- Sources: https://github.com/yast/ci-ruby-container\
- See https://trello.com/c/sVVOXYbx/878-5-build-the-docker-images-for-travis-in-obs
- The image is rebuilt immediately when the RPM packages are built
- Does not wait for publishing the packages, does not wait for full rebuild (only for the needed packages)
- No extra accounts/permissions for the Docker Hub (just use your OBS account)
- The build in OBS is faster (6-7 minutes), that means the new package should be available in the Docker image in less than 15 minutes after merging a PR (for leaf packages)
- No need for extra Jenkins jobs periodically triggering the image rebuilds at the Docker Hub
=> Use the Docker image built by OBS in Travis

package/yast2.changes, package/yast2.spec, scripts/yast2
This will allow us to use YUILoader::loadUI and use logic there instead
of direct loadPlugin calls.
Required to load integration tests framework (poo#36712)
=> Allow not prescribing UI in yast2

library/wizard/src/modules/Wizard.rb, package/yast2.changes, package/yast2.spec
_This is for the SLE-15-SP1 branch. The merge to master will follow._
https://trello.com/c/kUpqSPGu
https://bugzilla.suse.com/show_bug.cgi?id=1133367
In the NCurses UI, the wizard buttons can disappear when the wizard content is too large.
_Notice there are no wizard buttons visible._
Unlike in the Qt UI, the NCurses UI does not have a dedicated Wizard widget; a wizard dialog is pieced together from standard widgets. This includes the outer wizard dialog, the wizard buttons and the framework for the wizard contents which is basically a fancy ReplacePoint where the application later puts the dialog content.
Since all those parts were created equal, in case the UI runs out of screen space because a wizard dialog is overcrowded, it has to cut off widgets somewhere. In the standard algorithm …
=> Make sure the wizard buttons always remain visible in NCurses (SLE-15-SP1 branch)

package/yast2.changes, package/yast2.spec
A fix-up for #929 (which is a merge of #922)
- https://build.suse.de/package/view_file/SUSE:SLE-12-SP3:Update/yast2/yast2.changes?expand=1
- vs https://build.suse.de/package/view_file/SUSE:SLE-12-SP4:Update/yast2/yast2.changes?expand=1
(It diverged with 3.2.46 already)
Accordingly, I've revoked https://build.suse.de/request/show/193644
=> Downgrade to 3.2.46.1 because 3.2.47 is something different in SP4

library/network/src/modules/NetworkInterfaces.rb, package/yast2.changes, package/yast2.spec
It helps to recognize Infiniband devices when only the ifcfg file is present in other case the inteface type is detected as an Ethernet controller.
Referenced bug is about ipoib:
https://trello.com/c/2aiOMbUa/963-also-for-sle-12-sp4-bug-1086454-yast2-breaks-ip-over-ib-interfaces-by-enabling-optional-ib-features-as-default
=> Recognize Infiniband device based on attributes

library/packages/src/modules/PackageSystem.rb, library/packages/test/package_system_test.rb, package/yast2.changes, package/yast2.spec
- https://bugzilla.suse.com/show_bug.cgi?id=1137992#c8
=> PackageSystem.Installed: Improve loging details

library/packages/src/modules/SlideShow.rb, package/yast2.changes, package/yast2.spec
- https://bugzilla.suse.com/show_bug.cgi?id=1136708
- https://trello.com/c/hirlFUmw
- see https://github.com/yast/yast-packager/pull/450
While showing the slideshow different YAST modules will be called:
Calling YaST client inst_prepareprogress
Calling YaST client wrapper_slideshow_callbacks
Calling YaST client inst_prepdisk
Calling YaST client inst_instsys_cleanup
Calling YaST client inst_kickoff
Calling YaST client inst_bootloader
Calling YaST client inst_rpmcopy
...
..
.
The problem is that not each of these modules handles UI callbacks. Switching to another tab like the release notes tab will not be supported there.
With this fix the release tab will be shown only while RPM packages will be installed. So it will be shown 3-4 seconds after starting the installation.
=> Sle 15 sp1 bsc 1136708

library/general/src/modules/Arch.rb, library/network/src/modules/NetworkInterfaces.rb, library/system/src/modules/Kernel.rb, package/yast2.changes
Itanium is last build for SLE11 code stream, so it is no longer used and should be removed from code.
=> Deprecate itanium

library/network/src/modules/DnsServerAPI.pm, package/yast2.changes, package/yast2.spec
- https://bugzilla.suse.com/show_bug.cgi?id=1138668
- Failing old testsuite in yast2-dns-server
- It depends on bind rpm installed.
- Do not depend on the package installed at all in Mode.test()
- 4.2.11
=> DnsServerAPI: skip 'bind' absence in mode test

library/packages/src/lib/y2packager/product_reader.rb, library/packages/test/y2packager/product_reader_test.rb, package/yast2.changes, package/yast2.spec
- During upgrade in some cases the "No base product found" error message is displayed and the upgrade fails.
- Found by openQA: https://openqa.opensuse.org/tests/987957#step/start_install/4
- It turned out that it depends on the product installed and depends on the order of the products as returned by libzypp, as we used the `.first` product found.
- This means the bug is more or less random, in some cases libzypp returns the products in the order which works, sometimes not.
- Fixed by preferring the data from the new selected or available product, that should contain newer data than the old installed product.
- Additionally switched to the new and more memory efficient `Yast::Pkg.Resolvables` call instead of the old `Yast::Pkg.ResolvableDependencies`.
- Tested manually in a VM, works …
=> Base product fix

library/packages/src/lib/y2packager/product.rb, library/packages/test/y2packager/product_test.rb, package/yast2.changes, package/yast2.spec
Recently, the `select_product` option was added to the control file to allow **forcing** the base product selection when having multiple products in a single repository (see https://github.com/yast/yast-installation/pull/790).
But seems that the feature was not fully implemented and the installer only avoids displaying the product selector, but not marking the forced product as selected, raising an internal error when trying to access to `#installation_package`.
* https://bugzilla.suse.com/show_bug.cgi?id=1143943
* https://trello.com/c/YuiJfYBt/1201-ostumbleweed-p1-1143943-build-20190801-undefined-method-installationpackage
To select the **foced** product properly.
* The _automatic product selection_ is being performed in the [`InstRepositoriesInitialization`](https://github.com/yast/yast- …
=> Fix the forced base product selection (1/3)

library/general/src/modules/Report.rb, library/general/test/report_test.rb, package/yast2.changes, package/yast2.spec
Fixes [bsc#1149776](https://bugzilla.suse.com/show_bug.cgi?id=1149776).
=> Fix Report.LongWarning method in command line

library/packages/test/test_helper.rb
- We need to mock the Yast::InstURL module completely to avoid circular yast2 <-> yast2-packager build dependency.
- Fix up for #958 which [failed in Jenkins](https://ci.opensuse.org/job/yast-yast-yast2-master/127/console)
=> Fixed build

library/packages/src/lib/y2packager/product.rb, library/packages/src/lib/y2packager/product_control_product.rb, library/packages/src/lib/y2packager/product_license_mixin.rb, library/packages/test/y2packager/product_control_product_test.rb, library/packages/test/y2packager/product_reader_test.rb, package/yast2.changes, package/yast2.spec
- Added support for reading the products from the `control.xml` file
- Needed for a repo-less online installation medium, that will not contain any repository (so no product there)
- https://jira.suse.com/browse/SLE-7104
- To share some parts I have moved some code to the `ProductLicenseMixin` module
- This code will be used by some other modules, it was added here into the base YaST package to avoid some circular dependencies between `yast2-packager` and `yast2-installation`.
The base product definition in the `control.xml` file would look like:
```xml
<base_products config:type="list">
<base_product>
<label>SUSE Linux Enterprise Server 15 SP2</label>
<name>SLES</name>
<version>15.2</version>
<register_target>sle-15-$arch</register_target>
</base_product>
</base_products>
```
Optionally …
=> Added support for reading products from control.xml file

library/packages/src/lib/y2packager/product_control_product.rb, library/packages/test/y2packager/product_control_product_test.rb, package/yast2.changes, package/yast2.spec
- "label" marks a translatable text (jsc#SLE-7214)
- Additionally convert some `Yast::Arch.architecture` to the value expected by the registration server
- 4.2.23
=> Use "display_name" tag for the product label

library/general/src/lib/cfa/sysctl.rb, library/general/test/cfa/sysctl_test.rb, package/yast2.changes, package/yast2.spec
In #967 we decided to simply update old values in `/etc/sysctl.conf` because the `.sysctl_conf` agent could empty the file when trying to remove the last entry. To work around this problem, this change simply uses a regular expression to drop the unwanted lines, keeping the comments.
=> Remove old sysctl.conf values

library/packages/src/lib/y2packager/package.rb, library/packages/test/y2packager/package_test.rb, package/yast2.changes, package/yast2.spec
- https://bugzilla.suse.com/show_bug.cgi?id=1151824
- https://openqa.suse.de/tests/3406978#step/resolve_dependency_issues/2
- Fixed a crash when trying to download a non-existing package
- The `PackageDownloader::FetchError` exception is raised when YaST wants to download a package from source `-1` (that actually means the package is installed in the system, not available on any medium)
- I could not reproduce locally, but checking the code I found that the problem is in using the `Pkg.PkgProperties` call which does not allow to specify the package more precisely, it can return the result for any package instance
- Tested manually, at least no regression was found
- Reported by openQA, we should see quickly if this fix helps
- Additionally I switched from memory hungry `Pkg.PkgProperties` …
=> Fixed evaluating the available package versions (bsc#1151824)

library/network/src/modules/NetworkService.rb, library/network/test/network_service_test.rb, library/systemd/src/lib/yast2/systemd/unit.rb, library/systemd/test/yast2/systemd_unit_test.rb, package/yast2.changes, package/yast2.spec
In general, YaST assumes wicked as the default network service for any kind of installation. But that is not the case for a live installation.
In a live installation systemd is already running and we can determine the backend checking the network.service link.
- https://trello.com/c/qvY7Oygp/1375-3-osdistribution-p1-1151291-build-1330-openqa-test-fails-in-awaitinstall-yast-breaks-network-during-install
Check whether `systemd` is running or not for determining the current network backend.
=> NetworkService: Check if systemd is running for determining the network backend

library/system/src/lib/yast2/fs_snapshot.rb, library/system/test/fixtures/empty-snapper-list.txt, library/system/test/fixtures/snapper-list.txt, library/system/test/fs_snapshot_test.rb, package/yast2.changes, package/yast2.spec
Class `FsSnapshot` is used to retrieve filesystem snapshots information. To achieve that, some *snapper* cli commands are directly used. Till now, *snapper* commands only generated a human-readable output. That output might change when some new information is displayed. And such changes might ruin scripts relying on the *snapper* cli output.
But now, *snapper* is also offering a machine-readable output that should be used by scripts. 
* Part of https://trello.com/c/YAhIvrHz/417-5-optional-non-default-machine-readable-output-from-snapper.
* Requires https://github.com/openSUSE/snapper/pull/494
Class `FsSnapshot` is adapted to use *snapper* machine-readable output (*CSV* output format in this case).
* Unit tests have been adapted.
=> Use snapper machine-readable output

library/general/src/lib/ui/text_helpers.rb, library/general/test/text_helpers_test.rb
The [`wrap_text`](https://github.com/yast/yast-yast2/blob/43753ef77843e1a43a691b59154e52efb966785c/library/general/src/lib/ui/text_helpers.rb#L31-L53) helper method [does not respect new lines already present](https://github.com/yast/yast-installation/pull/827#issuecomment-553808305) in the given text.
Just to preserve the already present new lines.
Now the method,  _slightly_ inspired in the [Rails' `word_wrap`](https://github.com/rails/rails/blob/dcaa388badf49423fb8613bc02652e448890f879/actionview/lib/action_view/helpers/text_helper.rb#L260-L264), is also a bit more efficient.
Additionally, the logic to extract only a few lines after wrap the text has been moved to a new [`head`](https://github.com/yast/yast-yast2/blob/ea2d2d304b234721aae82b91547a1593f50fee68/library/general/src/lib/ui/t …
=> Improve the #wrap_text helper

library/packages/src/lib/y2packager/license.rb, library/packages/src/lib/y2packager/licenses_fetchers/tarball.rb, library/packages/test/y2packager/license_test.rb, library/packages/test/y2packager/licenses_fetchers/tarball_test.rb, package/yast2.changes, package/yast2.spec
> YaST downloads the license from SCC, but then it tries to find the license on the installation medium as well. — [comment#13 at bsc#1153326](https://bugzilla.suse.com/show_bug.cgi?id=1153326#c13)
* Trello: https://trello.com/c/ORqk8sk7/1444-1-p1-yast-asks-for-media-because-of-a-license-to-show-but-the-license-is-missing
* Bugzilla: https://bugzilla.suse.com/show_bug.cgi?id=1153326
Because the installer is looking for a license fetcher even when the license content was already provided, which 
* seems to be a wrong behavior although _it will not fail_ most of times.
* is a consequence of changes made in #880, at the time to introduce a new license fetcher to get them from an .rpm _fallback repo_
Note: the provided license content is used only for the default language, which was already …
=> Skip license fetcher

library/general/src/modules/Linuxrc.rb, package/yast2.changes, package/yast2.spec
Linuxrc maintains the state of what was read from '/etc/install.inf' file. If for any reason the internal state is reset and the SCR root was already modified then, it is probably that we try to read the file from the target system instead of the local one, and if already unmounted that could be like shooting ourselves in the foot.
- https://bugzilla.suse.com/show_bug.cgi?id=1157476 (it also contains a long history of the problem itself)
For avoiding that problem we ensure to use "/" as SCR root before reading "/etc/install.inf"
=> Read installinf instsys

library/general/src/modules/Linuxrc.rb, library/system/test/fs_snapshot_store_test.rb, library/system/test/fs_snapshot_test.rb, package/yast2.changes, package/yast2.spec
in the previous PR #984 we opened a new SCR instance when reading the /etc/install.inf file, but we are not ensuring we close it in case of empty or not present.
Ensure we set back the original default and close the new instance.
- Tested the changes in a docker image running the tests in the same order that were failing.
=> Linuxrc: Ensure the new SCR instance is closed

library/general/src/lib/cfa/login_defs.rb, library/general/src/lib/cfa/login_defs_config.rb, library/general/src/lib/cfa/multi_file_config.rb, library/general/src/lib/cfa/shadow_config.rb, library/general/src/modules/LoginDefsConfig.rb, library/general/src/modules/ShadowConfig.rb, library/general/test/cfa/login_defs_config_test.rb, library/general/test/cfa/login_defs_test.rb, library/general/test/cfa/shadow_config_test.rb, library/general/test/data/login.defs-example, library/general/test/data/login.defs/custom/etc/login.defs, library/general/test/data/login.defs/custom/etc/login.defs.d/70-yast.conf, library/general/test/data/login.defs/custom/etc/login.defs.d/99-local.conf, library/general/test/data/login.defs/custom/usr/etc/login.defs, library/general/test/data/login.defs/vendor/usr/etc/login.defs, library/general/test/login_defs_config_test.rb, package/yast2.changes, package/yast2.spec
As reported in [bsc#1155735](https://bugzilla.suse.com/show_bug.cgi?id=1155735), the `login.defs` file now lives in `/usr/etc/login.defs`. However, YaST still tries to read its settings from `/etc/login.defs`. 
Instead of using the old `.etc.login_defs` agent, YaST will use a CFA based API. However, as the configuration can be now scattered through several files (`/usr/etc/login.defs`, `/usr/etc/login.defs.d/*`, `/etc/login.defs` and `/etc/login.defs.d`), this PR introduces a `ShadowConfig` class that takes care of those details. It is named `ShadowConfig` because it refers to the *shadow suite*  configuration (referring to the manpage).
As we expect many changes like this in the future, we have extracted the common behavior to a `MultiFileConfig` class (a better name is welcome). Let's …
=> Handle shadow configuration when it is split into `/etc` and `/usr/etc`

library/general/src/lib/cfa/multi_file_config.rb
Omitting the end of the range works in Ruby 2.6 but it looks like it is not allowed in 2.5.
=> Fix syntax for Ruby 2.5

library/general/src/modules/Arch.rb, library/general/test/arch_test.rb, package/yast2.changes, package/yast2.spec
This is a rebased and slightly improved version of #985 (it adds some simple unit tests and drops the use of `Builtins`).
The PR adds an `is_wsl` function to detect whether the system is running on WSL. See [boo#1154962](https://bugzilla.suse.com/show_bug.cgi?id=1154962) for further details.
=> Add is_wsl function to detect wsl

library/network/src/modules/NetworkInterfaces.rb, package/yast2.changes, package/yast2.spec
There are many network interfaces that are rarely used or the support in SUSE has been deprecated. As we do not plant to support them in network-ng we should remove them in order to not be offered when adding a new connection.
The current list is obtained by the 'Yast::NetworkInterfaces.GetDeviceTypes' method
https://github.com/yast/yast-network/blob/90bf250c3cd8becf7f7196dea1e83449adaac900/src/lib/y2network/widgets/interface_type.rb#L51
- https://trello.com/c/qg8k5n8y/1379-3-feature-jscsle-7753-drop-deprecated-network-technologies-in-yast2
By now, the interfaces requested in the feature have been removed from the list used for configuring a new connection.
The `NetworkInterfaces.GetDeviceTypes` dependency has been also removed from yast2-network but without depending on the specific …
=> Network: drop unsupported technologies

library/packages/test/product_test.rb
`yast2` package is failing to build because it is reusing the `DATA_PATH` const (that should not be redefined).
=> Fix packages tests

library/packages/src/lib/y2packager/product_reader.rb, package/yast2.changes, package/yast2.spec
It causes the yast2-packager test suite to crash.
=> Do not crash when no base product is found

doc/etc-and-usr-etc.md, library/general/src/lib/cfa/sysctl.rb, package/yast2.changes, package/yast2.spec
When writing sysctl related settings, YaST will use `70-yast.conf` instead of `30-yast.conf` to reduce the chance of getting its values overridden.
During the installation/upgrade of `yast2.rpm`, if a `30-yast.conf` is found, it will be renamed to `70-yast.conf`. If the `70-yast.conf` already exists, the `30-yast.conf` will be simply removed (this case should not happen).
=> Use 70-yast.conf instead of 30-yast.conf

library/packages/src/lib/y2packager/resolvable.rb, package/yast2.changes, package/yast2.spec
Related to changes introduced in https://github.com/yast/yast-update/pull/143, which raises the below internal error
Bugzilla: [#1157636](https://bugzilla.suse.com/show_bug.cgi?id=1157636) and [#1158056](https://bugzilla.suse.com/show_bug.cgi?id=1158056)
Trello: https://trello.com/c/pyqFurT6 and https://trello.com/c/Rhvu29XB
=> Backward compatible resolvable

library/cwm/src/lib/cwm/service_widget.rb, library/systemd/src/lib/yast2/service_widget.rb, package/yast2.changes, package/yast2.spec
The new service widget was [introduced]((https://trello.com/c/uAe4i9Ru/107-5-fate319428-allow-socket-activation-widget)) in SLE-15-SP1, and by default, the option **keep_current_state** is selected. Which means that, although the user made same changes in the configuration, the changes were not reflected in the service as the service itself was untouched. 
Reported in: https://bugzilla.suse.com/show_bug.cgi?id=1158946
The main problem is that the option is usually overlooked by the user, and it does not have the same `default` as it had in previous SLE versions. At least it is the case of yast2 dns-server as we can see in the images below.
| **SLE-12-SP4 dns** | **SLE-15-SP1** |
|       :---:                    |      :---:               |
| …
=> Service widget default

library/packages/src/lib/y2packager/product_reader.rb, library/packages/test/y2packager/product_reader_test.rb, package/yast2.changes, package/yast2.spec
See https://bugzilla.suse.com/show_bug.cgi?id=1160362 for details.
Some things have changed in the `ProductReader` class recently. We don't test the Live Installation (is not a supported scenario), but it looks like it follows a different workflow that ends up with an exception because `ProductReader` contains a call to `Y2Packager::ProductControlProduct.products` bit it does not require `y2packager/product_control_product`.
Likely, in the normal workflow it works by pure luck (because some other class requires `y2packager/product_control_product`).
This pull request adds the missing require together with a smoke test to prove it was indeed missing.
If fact, the whole situation is even worse at this moment.  The current code looks like this:
```ruby
if Yast::Stage.initial && …
```
=> Add missing require clause (bsc#1160362)

library/commandline/src/modules/CommandLine.rb, library/commandline/test/commandline_test.rb, package/yast2.changes, package/yast2.spec
prompted by the testing discussion in https://github.com/yast/yast-ruby-bindings/pull/237
because I wanted to test that fix with `yast2 lan unknowncommand` and it still did not work
=> Propagate an error status when a CommandLine module gets an   unknown command

library/system/src/lib/yast2/fs_snapshot_store.rb, library/system/test/fs_snapshot_store_test.rb, package/yast2.changes, package/yast2.spec
See https://bugzilla.suse.com/show_bug.cgi?id=1159562 for details.
When upgrading a system, YaST takes a previous snapshot and stores its id in the `/var/lib/YaST2` directory of the system being upgraded. That directory will always be there, as long as YaST is installed in the system being upgraded.
But when using YaST to upgrade a system in which YaST is not installed, the process fails because the directory is not there.
It's debatable whether upgrading a non-YaST system with YaST is a valid scenario, but the small change introduced in this pull request should be enough to make it work.
Tested manually. With this patch, the snapshot is correctly created in both situations (with and without a preexisting `/var/lib/YaST2`).
=> Do not fail during upgrade if `/var/lib/YaST2` is missing (bsc#1159562)

library/packages/src/modules/SlideShow.rb, library/packages/test/slide_show_test.rb, package/yast2.changes, package/yast2.spec
**Problem**
Reading Release Notes during installation is impossible because the installation switch to the
"Details" tab when the medium has been changed.
**Solution**
Do not refresh package installation overview if the medium has been changed and the user has switched to the release notes tab.
=> Do not refresh package installation overview if the medium has changed.

library/general/src/lib/ui/text_helpers.rb, library/general/src/lib/yast2/refinements.rb, library/general/src/lib/yast2/refinements/string_manipulations.rb, library/general/test/text_helpers_test.rb, package/yast2.changes, package/yast2.spec
While updating the [addons selection dialog](https://github.com/yast/yast-registration/blob/master/src/lib/registration/ui/addon_selection_registration_dialog.rb) to make use of the new [`CustomStatusItemSelector`](https://github.com/libyui/libyui/pull/152) widget ([bsc#1157780](https://bugzilla.suse.com/show_bug.cgi?id=1157780 )), it was found that their descriptions contain HTML tags, which are
* not compatible with the `#wrap_text` helper, which could break the tags and/or ends with lines of different widths.
* not fully supported by the `CustomStatusItemSelector` since in ncurses they are not _rendered_ but displayed as part of the description.
The simple solution would strip the HTML tags before wrapping the text. 
However, before realizing that the HTML was not being rendered in …
=> Add a new text helper to strip HTML tags

library/general/src/lib/ui/text_helpers.rb, library/general/src/lib/yast2/refinements/string_manipulations.rb
The `DEFAULT_HTML_TAGS_REPLACEMENTS` constant defined in #1011 was misplaced, according to the Ruby complain when running tests
> /usr/share/YaST2/lib/yast2/refinements/string_manipulations.rb:37: warning: not defined at the refinement, but at the outer class/module
Move it to out of the refinement.
* Also fixed the documentation comments referencing the refinement.
* No version bump / changelog updates required :question:
=> Fix refinements

library/systemd/src/modules/Systemd.rb, package/yast2.changes, package/yast2.spec
https://bugzilla.suse.com/show_bug.cgi?id=1160890
https://trello.com/c/3Y9HSV8m
`/bin/systemd` symlink is gone.
Don't use it.
=> don't use /bin/systemd compat symlink (bsc#1160890)

library/packages/src/lib/y2packager/product.rb, library/packages/src/modules/PackagesUI.rb, library/packages/test/y2packager/product_test.rb, package/yast2.changes, package/yast2.spec
Please, see the whole picture in https://github.com/yast/yast-registration/pull/467.
This PR adds support to `PackagesUI.RunPackageSelector` to enable the online search feature in the UI.
=>  [SLE-9109] Packages online search

library/packages/src/lib/y2packager/original_repository_setup.rb, library/packages/src/lib/y2packager/repository.rb, library/packages/src/lib/y2packager/service.rb, library/packages/test/product_factory.rb, library/packages/test/repository_test.rb, package/yast2.changes, package/yast2.spec
- Related to https://bugzilla.suse.com/show_bug.cgi?id=1159433
- We need to remember the original repositories just after mounting the partition selected to upgrade. This will allow us later to distinguish the new SP2 repositories from the old ones and do not display them in the "Previously used repositories" dialog.
- The old repository setup will be saved in the `yast2-update` package and used in `yast2-installation`, this just prepares the infrastructure for that.
- The second part of the move is in this PR: https://github.com/yast/yast-packager/pull/502
- New classes:
- The `OriginalRepositorySetup` is a singleton object holding the original configuration, then we can compare the original and the current repositories to find the old ones.
- The new `Y2Packager::Service` is similar to …
=> New classes for storing the old repositories (bsc#1159433)

library/packages/src/lib/y2packager/product_control_product.rb, library/packages/test/y2packager/product_control_product_test.rb, package/yast2.changes, package/yast2.spec
- The installer crashes when `software/base_products` is not defined in `control.xml` in the Live installer.
- See https://bugzilla.suse.com/show_bug.cgi?id=1161956
- Check the `ProductFeatures.GetFeature` returned value, if it not an `Array` then do not try using it.
- This is rather a workaround for the bug, there is another problem because the `ProductControlProduct` class should actually not be used on the Live medium at all... 
- Added an unit test
=> Do not crash when the "software/base_products" is not defined

library/cwm/src/lib/cwm/dynamic_progress_bar.rb, library/cwm/src/lib/cwm/progress_bar.rb, library/cwm/src/lib/cwm/rspec.rb, library/cwm/src/lib/cwm/widget.rb, library/cwm/test/dynamic_progress_bar_test.rb, library/cwm/test/progress_bar_test.rb, package/yast2.changes, package/yast2.spec
The Expert Partitioner needs a new dialog to show the progress when applying changes. This new dialog requires a progress bar.
* https://bugzilla.suse.com/show_bug.cgi?id=1135366
Add new classes `CWM::ProgresBar` and `CWM::DynamicProgressBar`.
* Manually tested
* Added unit tests.
<details>
<summary>Show/Hide</summary>
</details>
=> Add ProgressBar widget

library/desktop/src/clients/menu.rb, library/desktop/src/modules/Desktop.rb, library/desktop/test/data/usr/share/applications/YaST2/org.opensuse.yast.SWSingle.desktop, library/desktop/test/desktop_test.rb, package/yast2.changes, package/yast2.spec
reason: WSL is limited environment, so many modules does not make sense to show. So whitelisting only ones that has specific key in desktop file.
=> add ability for WSL desktop file whitelisting

library/packages/src/modules/Product.rb, package/yast2.changes, package/yast2.spec
- https://bugzilla.suse.com/show_bug.cgi?id=1165501 
- This is related to https://github.com/yast/yast-pkg-bindings/pull/125, restoring the sources during installation has a side effect of deselecting the selected products or patterns
- 4.2.68
=> Skip repository reloading (bsc#1165501)

library/cwm/src/lib/cwm/common_widgets.rb, library/cwm/test/common_widgets_test.rb, package/yast2.changes, package/yast2.spec
After changing/updating its content (aka value), a CWM::RichText is not able to restore the vertical scroll. This is specially annoying in those scenarios where that widget is being used to emulate complex interfaces, such as MultiSelection list.
* https://bugzilla.suse.com/show_bug.cgi?id=1049965
Add a flag to know if it will be necessary to save/restore the scroll before/after updating the value.
* Tested manually
* Added unit tests.
<details>
<summary>Click to show/hide</summary>
---
</details>
---
Related to 
* https://github.com/libyui/libyui/pull/149
* https://gist.github.com/shundhammer/1bc79af7d1a31892bd977678bc2af2c1#conservative-approach-save-scrollbar-values
* https://github.com/yast/yast-registration/pull/483#discussion_r385282607
=> Restore the CWM::RichText scroll after updating its content

library/packages/src/lib/y2packager/original_repository_setup.rb, package/yast2.changes, package/yast2.spec
- Do not remove the installation repositories in the "Previously Used Repositories" step
- https://bugzilla.suse.com/show_bug.cgi?id=1163081
- https://openqa.opensuse.org/tests/1194286#step/upgrade_select/3
- Tested manually
- 4.2.71
=> Do not remove the installation repositories (bsc#1163081)

library/cwm/src/lib/cwm/multi_status_selector.rb, library/cwm/test/multi_status_selector_test.rb, package/yast2.changes, package/yast2.spec
> Providing following features:
>
>  - Allow to select more than one item.
>  - Able to represent multiple statuses: no selected, selected, auto selected.
>  - Able to represent disabled items.
>  - Emit different events to distinguish the interaction through check box input or its label.
>  - Automatic text wrapping.
>  - Keep the vertical scroll.
---
Related to 
* https://trello.com/c/CmaNrDAw
* https://github.com/yast/yast-registration/pull/483#discussion_r385108398
=> [CWM] Add new widget to manage multi status selection lists

library/cwm/src/lib/cwm/multi_status_selector.rb, library/cwm/test/multi_status_selector_test.rb, package/yast2.changes, package/yast2.spec
There is not enough space between items when running in Qt
To surround items in `<p>` when not running in text mode.
<details>
<summary>Click to show/hide</summary>
---
</details>
---
See also https://github.com/yast/yast-yast2/pull/1029
=> [CWM] Minor improvements for the MultiStatusSelector widget

library/cwm/src/lib/cwm/multi_status_selector.rb, library/cwm/test/multi_status_selector_test.rb, package/yast2.changes, package/yast2.spec
- The help text icons were not displayed properly in installation (installed system was OK)
- The problem was that the `icon_for` method call did not pass the current mode and it used the default "normal" 
- Because the `help` method is a class method I had to change some helpers to be class methods as well
- 4.2.74
| Original | Fixed |
|-|-|
| ![Screenshot_sl5sp2_2020-03-13_01:13:38](https://user-images.githubusercontent.com/1691872/76581274-b28d5680-64ca-11ea-99b7-359ebf6b6811.png) | ![help_icons](https://user-images.githubusercontent.com/907998/76936794-d6e69a00-68f3-11ea-966a-5ba859e34cbe.png) |
=> Fixed CWM::MultiStatusSelector help text icons

library/network/src/lib/y2firewall/firewalld.rb, library/network/test/y2firewall/firewalld_test.rb, package/yast2.changes, package/yast2.spec
**firewalld auto** client runs before the **tftp server** one modifying the firewalld service state. The problem is that the firewalld **API** instance is cached and thus, the tftp server uses the **online cmd** instead of the **offline**.
- https://trello.com/c/oKLCTb39/1719-3-sle15-sp2-1166698-ay-failed-at-tftpserverauto-with-error-firewalld-not-working
- https://bugzilla.suse.com/show_bug.cgi?id=1166698
- Forcing a reset of the firewalld API instance after modifying the service state should be enough for fixing the bug (https://github.com/yast/yast-firewall/pull/128). But as the service state could be modified by other clients, forcing a reset before reading is safer and that is what also has been implemented.
<details>
<summary>Before the fix</summary>
</details>
<details> …
=> Reset firewall API instance when reading (bsc#1166698)

library/cwm/src/lib/cwm/multi_status_selector.rb, library/cwm/test/multi_status_selector_test.rb, package/yast2.changes, package/yast2.spec
- https://bugzilla.suse.com/show_bug.cgi?id=1167523
- I tried several approaches
- Adding `vertical-align: middle` styling did not work well, the text was moved up, but too much :worried: 
- Adding `padding-bottom: 3px` worked fine in 800x600 installation, but was broken in 1280x1024 (it uses bigger font so the 3px padding was not enough). Unfortunately Qt accepts only pixel units here, we would need some unit relative to the font size like `em` which is not accepted :worried: 
- Finally using a table works in all cases! :+1: 
- Some details can be found the Qt documentation: https://doc.qt.io/qt-5/richtext-html-subset.html
- Additionally I noticed some other broken `style` attributes with missing `=` character :scream: 
Full screen
1:1 crop
*Notice also a smaller space between the items, …
=> Fixed RichText multi-selection alignment (bsc#1167523)

.travis.yml, library/systemd/src/modules/Systemd.rb, package/yast2.changes, package/yast2.spec
YaST network does not show the global tab in the running system because it checks whether systemd is running or not and it is not properly detected since a change in the sysfs cgroup systemd hierarchy
- https://trello.com/c/9eYR4f6p/4042-tw-p2-1168307-lan-no-global-tab-sys-fs-cgroup-systemd-no-such-file-or-directory
Change the way YaST determines if systemd is running.
Tested manually in a running system running the **yast2 network** module and in WSL.
=> Change the way YaST determines if systemd is running or not

library/wizard/src/modules/Wizard.rb, package/yast2.changes, package/yast2.spec
https://bugzilla.suse.com/show_bug.cgi?id=1167224
The wizard "Help" button is not retranslated when changing the language.
This happens only in the NCurses wizard.
The Wizard.rb module is a wrapper around the YQWizard widget and an emulation of its functionality for NCurses.
For the Qt UI, this uses `RetranslateInternalButtons()` to retranslate the "static" buttons of the wizard such as "Help".
For the NCurses UI, this was completely missing; so while buttons like "Back", "Abort", "Next" were correctly retranslated, the "Help" button was not.
Set the label again for the "Help" button so the correctly translated text is now used.
Notice the Russian "Help" button (the leftmost one on the bottom: `[Справка]`)
That entire `Wizard::RetranslateButtons()` function turned out to be a giant NOP: …
=> Retranslate wizard help button in NCurses (bsc#1167224)

package/yast2.spec
The **CONTRIBUTING.md** file was removed (#1042) from the repository but the file is still referenced in the spec file
Remove the file from the spec file
=> Remove CONTRIBUTING.md from the spec file

library/network/src/modules/NetworkInterfaces.rb, library/network/test/network_interfaces_test.rb, package/yast2.changes, package/yast2.spec
Removed secondary IP addresses through the yast2-network dialog are marked to be deleted but are not removed from the ifcfg files since (https://github.com/yast/yast-yast2/pull/789)
- https://trello.com/c/xHnv0zCT/4047-osdistribution-p5-1146020-setting-additional-ip-addresses-in-eth-adapter-configurations-delete-of-additional-ip-address-not-poss
- https://bugzilla.suse.com/show_bug.cgi?id=1146020
Delete not only removed interfaces but also removed secondary IP addresses.
=> Remove deleted secondary IP addresses

library/systemd/src/lib/yast2/systemd/unit.rb, library/systemd/test/yast2/systemctl_test.rb, library/systemd/test/yast2/systemd_unit_test.rb, package/yast2.changes, package/yast2.spec
In case of a live installation, systemd is detected as running failing in case we try to show the properties of a systemd unit.
- https://bugzilla.suse.com/show_bug.cgi?id=1168849
- Check whether we are running inside a chroot in order to return the systemd unit properties.
=> Running chrooted fix

doc/desktop_file.md
Document `X-SuSE-DocTeamID` key seen while working on https://github.com/yast/yast-autoinstallation/pull/604.
=> Document X-SuSE-DocTeamID key for .desktop files

package/yast2.changes, package/yast2.spec
- Fixes build failure in `yast2-packager`
- It is needed for `anyxml` agent
- Related to [bsc#1170886](https://bugzilla.suse.com/show_bug.cgi?id=1170886)
- 4.3.1
=> Restore back the perl-XML-Simple dependency

library/xml/src/modules/XML.rb, library/xml/test/xml_test.rb, package/yast2.changes, package/yast2.spec
Check also that the XML is well formed. If there is a syntax error then raise the `XMLDeserializationError` exception.
The parsing method `XMLToYCPString` runs the Nokogiri parser in strict mode and raises the `XMLDeserializationError` exception on parse error. It should behave consistently so the validation should also check that the document is well formed. (Nokogiri by default uses the recovery mode which automatically adds missing closing tags, etc...)
=> Improve the XML validation

library/systemd/src/lib/yast2/system_service.rb, library/systemd/test/yast2/system_service_test.rb, package/yast2.changes, package/yast2.spec
When a systemd service is initially stopped, the `SystemService` object will always consider the service as stopped. But sometimes the service could be started later via its socket. In that case, if we set the service to be restarted, the systemd service would never be stopped because `SystemService` believes that the systemd service continues stopped.
Moreover, in case that the service is configured to be started on demand, `SystemService` tries to start the socket instead of the service. But it would fail to start the socket because the service is already running.
* https://bugzilla.suse.com/show_bug.cgi?id=1162514
* https://trello.com/c/gEHPeax1/1882-sles15-sp1-p5-1162514-iscsi-session-is-not-connected-after-successful-connection-via-yast2-iscsi-client
There are two possible solutions: …
=> Fix system service actions

library/xml/src/modules/XML.rb, library/xml/test/xml_test.rb, package/yast2.changes, package/yast2.spec
- https://bugzilla.suse.com/show_bug.cgi?id=1170886
- Distinguish between a `String` argument (containing a XML document/schema) and `Pathname` (path to a file)
- Avoid problems with file names containing a new line character (really unlikely, but still
possible...)
- The `Yast::XML.validate` method has been added recently and my [quick search](https://github.com/search?q=org%3Ayast+%22XML.validate%22+org%3Ayast&type=Code) did not found any usage in YaST. Which means we can safely change the type and meaning of the arguments.
=> Updated Yast::XML.validate arguments

library/general/src/lib/installation/auto_client.rb, library/general/test/auto_client_test.rb, package/yast2.changes, package/yast2.spec
The AutoClient#export method can receive a hash as an argument. The idea is to support getting arguments like the `target`. See https://github.com/yast/yast-autoinstallation/pull/631 for further information.
=> Reduce profile on-demand

library/packages/src/lib/y2packager/release_notes_fetchers/url.rb, library/packages/test/y2packager/release_notes_fetchers/url_test.rb, package/yast2.changes, package/yast2.spec
Logging crashes when trying to download release notes and the proxy was inoperative.
* https://bugzilla.suse.com/show_bug.cgi?id=1173447
Avoid failure when the proxy is inoperative.
Added new unit tests.
=> Avoid failure with release notes

library/packages/src/lib/y2packager/release_notes_fetchers/url.rb, library/packages/test/y2packager/release_notes_fetchers/url_test.rb, package/yast2.changes, package/yast2.spec
See https://github.com/yast/yast-yast2/pull/1068.
=> Avoid failure with release notes (forward-port)

library/packages/src/modules/Product.rb, package/yast2.changes, package/yast2.spec
Problem
=========
While checking the libzypp connection for products an unneeded solver run has been done BEFORE any module has been added. This case has reported errors in the logs because the complete package list has not been available at that moment.
Solution
========
The solver run has been removed because it is not needed at all.
=> Product: Do not solve dependencies while checking libzypp connection

library/types/src/modules/String.rb, package/yast2.changes, package/yast2.spec
- https://bugzilla.suse.com/show_bug.cgi?id=1173907
`SPACE_CHARS` https://github.com/yast/yast-yast2/blob/master/library/types/src/modules/String.rb#L42 doesn't include a space.
This makes it impossible to work with ESSIDs containing a space. See
https://github.com/yast/yast-network/blob/master/src/lib/y2network/widgets/wireless_essid.rb#L95-L97
Add it.
AFAICS `SPACE_CHARS` is only used in `Yast::String.CPrint` and that's only used in the ESSID dialog. So I wouldn't expect any evil fallout by this change.
=> add space to SPACE_CHARS (bsc#1173907)

library/general/src/lib/cfa/multi_file_config.rb, package/yast2.changes
The [CFA::MultiFileConfig](https://github.com/yast/yast-yast2/blob/5265884d711e68bd36e06aa4250eb71c50f85a35/library/general/src/lib/cfa/multi_file_config.rb) is not fully reusable because it is using `CFA::LoginDefs` for loading files. Most probably, a leftover during the [extraction of reusable code](https://github.com/yast/yast-yast2/commit/cdf92b82ac8b0030437e2be74f7abbed8fabf616) in #988.
Simply use the provided `file_class` instead.
=> Makes CFA::MultiFileConfig reusable

.github/workflows/tests.yml, README.md
- This is a proof of concept for using the GitHub actions as the CI
- Let's see how it compares with Travis
- You can see an example run here: https://github.com/yast/yast-yast2/runs/869651708
=> CI: Experimentally enable GitHub actions

library/packages/src/lib/y2packager/repository.rb, library/packages/src/lib/y2packager/zypp_url.rb, library/packages/test/repository_test.rb, package/yast2.changes, package/yast2.spec
Libzypp URLs can include the so-called [Repository Variables](https://doc.opensuse.org/projects/libzypp/HEAD/zypp-repovars.html) (repovars for the friends). They can have several formats like `$variable`, `${variable}`, `${variable-word}` or `${variable+word}`. They can appear in many parts of the URL, including the host, the path and even the port! (well, see some clarifications about the port below)
Of course, those vars are expanded before the URL is used for any real connection.
Before this pull request, the `Repository` class used two attributes to store the expanded and raw version of those URLs as [Ruby's URI](https://ruby-doc.org/stdlib-2.7.1/libdoc/uri/rdoc/URI.html) objects. Unfortunately, having curly brackets as part of the host, the path or the port of an URL does not conform …
=> Better management of libzypp repovars

library/general/src/modules/Arch.rb, library/general/test/arch_test.rb, package/yast2.changes
Microsoft kernels are named "4.0-19041-Microsoft" on WSL1 and
"4.19.104-microsoft-standard" on WSL2. Match on lowercase "-microsoft".
(boo#1174183)
=> Update is_wsl to match osrelease spellings under both WSL1 and WSL2

library/network/src/lib/y2firewall/firewalld.rb, library/network/test/data/etc/firewalld/zones/internal.xml, library/network/test/y2firewall/firewalld_test.rb, package/yast2.changes, package/yast2.spec
When the user ask about a reduced profile we export all the available zones even if not modified from the default values.
https://trello.com/c/bLXXJXbk/1904-5-reduce-firewall-section-size
Provide a method to check which zones have been modified from the default settings
Required by https://github.com/yast/yast-firewall/pull/134
=> Firewalld: Added method to check which zones have been modified from default settings

library/xml/src/modules/XML.rb, package/yast2.changes, package/yast2.spec
Do not export the system ID when it is not defined. It generates:
```xml
<!DOCTYPE profile>
```
instead of:
```xml
<!DOCTYPE profile SYSTEM "">
```
Trello: https://trello.com/c/WtDObsGz/1983-3-tw-1174424-build-20200720-autoyast-profile-doesnt-validate
Bug report: https://bugzilla.opensuse.org/show_bug.cgi?id=1174424
=> Fix XML system ID

library/general/doc/Hooks.md
Changes in *.changes, *.spec not needed because it is not in the RPM
=> autoimage removed in docu

.github/workflows/tests.yml
Advantages:
- Parallel builds are faster
- Get separate results for Rubocop, unit test, etc... you do not need to check the details in the logs, you can see directly where the problem is
=> Split the GitHub actions to run in parallel

library/packages/src/lib/y2packager/resolvable.rb, library/packages/test/y2packager/resolvable_test.rb, package/yast2.changes, package/yast2.spec
- Improved error handling - the `Pkg.Resolvables()` call can now return `nil` as an error result, we need to handle that case
- Related to https://bugzilla.suse.com/show_bug.cgi?id=1175317
- Related to https://github.com/yast/yast-pkg-bindings/pull/136
- Added more unit tests
=> Error handling in Y2Packager::Resolvable.find()

library/packages/test/y2packager/resolvable_test.rb, package/yast2.changes, package/yast2.spec
- Related to https://github.com/yast/yast-yast2/pull/1092
- The included testing repository contains only the x86_64 packages, on the other architectures they will be ignored (only noarch are visible). So we cannot check the exact number of found packages in the tests.
- 4.3.22
=> Fixed unit test failure on non x86_64 archs

package/yast2.changes, package/yast2.spec
- Caused by a copy&paste (without edit) mistake [here](https://github.com/yast/yast-yast2/commit/f276944b2bff049b557aa8b2eb3426489858ec3c#diff-9cf9a66e281d2c4515d6f3682dd152eb).
- 4.3.24
=> Fixed accidentaly broken dependencies

.rubocop.yml, library/packages/src/modules/PackageCallbacks.rb, package/yast2.changes, package/yast2.spec
- The download progress in the main window still shows the details about the previously downloaded file when an error pop up is displayed for a different file. That's quite confusing.
- See https://bugzilla.suse.com/show_bug.cgi?id=1175926
- Just reset the progress status before displaying the popup
- I wanted to display the URL of the failed file in the progress but unfortunately the URL parameter of the callback contains the repository URL (like `http://example.com`), not the failed file URL (like `http://example.com/repodata/repomd.xml`). That would be confusing so I decided to just clear the old label.
- For easier debugging I have added a debug log to all callbacks so we can see the order in which they were called. Activated only when `Y2DEBUG_CALLBACKS` is set to `1`.
=> Update progress status when an error pop up is displayed (bsc#1175926)

library/wizard/src/modules/Wizard.rb, package/yast2.changes, package/yast2.spec
A Wizard dialog always reserves space for its heading, even when the title is not set or it is set as empty. In the Expert Partitioner we want to remove the *Expert Partitioner* title and to place the menu bar at the very top. But, due to such reserved space for the heading, the menu bar starts just after some blank gap, which looks quite strange.
* Part of PBI: https://trello.com/c/dT7X5aC1/2045-menu-layout-rendering-improvements
_Keeping the heading text:_
_[Setting the header as empty](https://github.com/yast/yast-storage-ng/commit/ffa251b77884ae3e237e8f97133baf11bdb34ad6):_
The heading of the dialog is now managed by a `ReplacePoint` widget. The content of the heading is only added when the title is not empty. Take into account that the *Release Notes* button belongs to the header, so …
=> Allow to hide dialog heading

library/packages/src/modules/Slides.rb, package/yast2.changes, package/yast2.spec
- Fixes and error present in the y2log even in a successful installation
- See https://bugzilla.suse.com/show_bug.cgi?id=1176653
- There seems to be a different problem, the slideshow directory does not exist at that point. But I guess it's because we do not use slideshow anymore, it has been dropped.
- The code is more or less dead and needs a cleanup (complete removal) I'm doing just a simple and quick fix to ensure the openQA test passes.
=> Decrease error logging (bsc#1176653)

library/systemd/src/lib/yast2/systemctl.rb, package/yast2.changes, package/yast2.spec
- Fixes https://bugzilla.suse.com/show_bug.cgi?id=1176714
- It's related to https://github.com/systemd/systemd/commit/1cabd2d0c56b7de73e4a4fb645f3bbed4a528d2c, which says 
> The combination "--full --no-legend --no-pager --plain" is appropriate for  automated processing of systemctl output.
Tested manually (as suggested in https://bugzilla.suse.com/show_bug.cgi?id=1176714#c11):
- Run `yast2 users`
- Go to `Expert Options` -> `Encryption`
- This will display DES as the selected option
- With the fix it correctly selects the SHA-512 option
=> Fix systemctl command line options (bsc#1176714)

library/control/src/modules/WorkflowManager.rb, library/xml/src/modules/XML.rb, library/xml/test/xml_test.rb, package/yast2.changes, package/yast2.spec
- See https://bugzilla.suse.com/show_bug.cgi?id=1176593
- YaST crashed because it wanted to parse `nil` file
- Tested manually with the latest SP3 build
=> Do not crash when trying to parse "nil" XML file (bsc#1176593)

library/control/src/modules/InstError.rb
Display appropriate Bugzilla URL depending on the release name of the product on which the error occurred.
In case of an error, the error dialog will request the user to file a report on https://bugzilla.opensuse.org when the release name in `/etc/os-release` contains "openSUSE". For any other release name, the
Bugzilla URL displayed would be https://bugzilla.suse.com.
**Before**
**After (on openSUSE system)**
I tested this by commenting out **NAME=** attribute from `/etc/os-release` file. In this case, the `OSRelease.ReleaseName` method will return the default value of "SUSE Linux" and in that case, https://bugzilla.suse.com URL is displayed to the user.
Fixes [bsc#1081441](https://bugzilla.novell.com/show_bug.cgi?id=1081441)
=> Bnc#1081441

library/cwm/src/lib/cwm/common_widgets.rb, library/cwm/test/common_widgets_test.rb, package/yast2.changes, package/yast2.spec
Two small improvements after the first review of https://github.com/yast/yast-autoinstallation/pull/592.
* When setting the value of a `ComboBox` item, the new value will be added to the list of items if it was not already included and the combo is editable.
* A MenuButton listens to events from its children.
=> CWM improvements

library/cwm/src/lib/cwm/common_widgets.rb, library/cwm/test/common_widgets_test.rb, package/yast2.changes, package/yast2.spec
Fixes #1044 in case that the `opt` method is not defined.
=> Fix selector without opt

library/general/src/lib/installation/autoinst_profile/section_with_attributes.rb, library/general/test/installation/autoinst_profile/section_with_attributes_test.rb, package/yast2.changes, package/yast2.spec
Fixes [bsc#1177405](https://bugzilla.suse.com/show_bug.cgi?id=1177405). It does not try to import the information from a hash when it is not actually a hash.
```
<partition>
<raid_options/>
</partition>
```
Is exported to: 
```ruby
{ raid_options: "" }
```
because there is not enough information to determine whether it is should be a string or a hash (the `raid_options` is supposed to be a hash).
=> bsc#1177405: AutoYaST crashes with an empty <raid_options> section

library/wizard/src/modules/Wizard.rb, package/yast2.changes, package/yast2.spec
In https://github.com/yast/yast-yast2/pull/1098, `Yast::Wizard` was adapted to hide its heading when the title is set to empty. But in *ncurses*, the wizard heading always includes the *Release Notes* button. Such button must be preserved even though the title is set to empty.
* https://trello.com/c/ASQzhjTK/2102-sles15-sp3-p1-1176808-build-421-openqa-test-fails-in-releasenotes
* https://bugzilla.suse.com/show_bug.cgi?id=1176808
* See also https://trello.com/c/dT7X5aC1/2045-1-menu-layout-rendering-improvements.
The changes introduced by https://github.com/yast/yast-yast2/pull/1098 were reverted and the *Release Notes* button is shown again.
Note that hiding the heading is not needed at all in text mode because the heading has no height when its title is empty. With an empty title, the …
=> Revert hide dialog heading in text mode

library/cwm/examples/object_api_table.rb, library/cwm/src/lib/cwm/rspec.rb, library/cwm/src/lib/cwm/table.rb, library/cwm/test/table_test.rb
This replaces #1099.
Adds a new `TreeItem` class that can be used to specify nested items.
See https://trello.com/c/g0CpGq6T/1915-3-partitioner-nested-tables
This is how `examples/object_api_table.rb` looks like now, after adding a second table to it with nested elements:
=> Support for nested items in CWM::Table

library/cwm/src/lib/cwm/common_widgets.rb, library/cwm/test/common_widgets_test.rb, package/yast2.changes, package/yast2.spec
When the user scan the available WiFI networks, the ComboBox is not populated with the results but only offers the orginal selection.
- https://bugzilla.suse.com/show_bug.cgi?id=1177137
Query the list of items offered by the ComboBox in order to extend it with a new value.
=> CWM ComboBox: Query current items when extending the list with a new value.

library/cwm/src/lib/cwm/common_widgets.rb, library/cwm/test/common_widgets_test.rb, package/yast2.changes, package/yast2.spec
Last changes in CWM (see https://github.com/yast/yast-yast2/pull/1113) can make unit tests to fail. The method `#current_items` returns nil in unit tests, so the test will fail when `ComboBox#value=` tries to map over nil.
See https://github.com/yast/yast-yast2/pull/1113#pullrequestreview-525536006.
Ensure that `#current_items` always returns a list.
=> Fix #current_items

library/control/src/modules/ProductFeatures.rb, library/system/src/modules/Kernel.rb, library/system/test/kernel_test.rb, package/yast2.changes, package/yast2.spec
add option to allow product to specify if it should propose hibernation or not.
trello https://trello.com/c/ULBrtwpz/2144-3-couldhave-hibernation-proposed-by-installer-bootloader
jira https://jira.suse.com/browse/SLE-12280
related PR: https://github.com/yast/yast-installation-control/pull/104
=> Propose hibernation

library/cwm/src/lib/cwm/common_widgets.rb, library/cwm/test/common_widgets_test.rb, package/yast2.changes, package/yast2.spec
A [bug](https://bugzilla.suse.com/show_bug.cgi?id=1178832) was reported recently as consequence of #1044 . The problem is that when the ComboBox is editable and the value is not present in the list of items, the list of items is modified using `change_items` with the original items, a list that could have been modified like it is in the [yast-network essid widget](https://github.com/yast/yast-network/blob/941f20ab040e60fccbaf52bf7cf5261c629adcd3/src/lib/y2network/widgets/wireless_essid.rb#L83).
So, it was proposed to check the current widget items instead of the items list but as @shundhammer  pointed in https://bugzilla.suse.com/show_bug.cgi?id=1178832#c21, we created and inconsistency as we were not converting the list of `Items` to an `Array<string, string>`.
Revert the addition of the …
=> Revert current items

library/control/src/modules/WorkflowManager.rb, package/yast2.changes, package/yast2.spec
- Ensure the libzypp target is initialized when downloading the skelcd packages to verify the GPG signatures
- See https://bugzilla.suse.com/show_bug.cgi?id=1179773
- From the `y2log`:
```
2021-01-11 06:17:00 <1> install(8866) [Ruby] modules/PackageCallbacks.rb:199 DoneProvide: 3,
skelcd-control-SLES4SAP-15.2.2-3.3.2.x86_64 (SelfUpdate0): Signature verification failed [5-File
does not exist or signature can't be checked]
OOps. Target is not initialized!
```
- Libzypp needs the target for loading the known GPG keys
- I'm not sure whether the code can be used in installed system, I used `if Stage.initial` to apply this fix only in installation
- Tested manually, after patching the installer the error popup is not displayed anymore.
=> Ensure the libzypp target is initialized (bsc#1179773)

library/control/src/modules/WorkflowManager.rb, package/yast2.changes, package/yast2.spec
- This is a fix up for the previous PR #1127 
- The previous fix caused a regression in SP3, let's fix it also in SP2 (where it will be released as a maintenance update)
- https://bugzilla.suse.com/show_bug.cgi?id=1180858
=> Keep the libzypp target open to verify other packages (bsc#1180858)

library/control/src/modules/WorkflowManager.rb, package/yast2.changes, package/yast2.spec
- Just merging #1129 from SP2 to `master`
- https://bugzilla.suse.com/show_bug.cgi?id=1180858
=> [master] Keep the libzypp target open to verify other packages

.github/workflows/ci.yml, library/general/src/modules/Arch.rb, library/general/test/arch_test.rb, library/system/src/modules/Kernel.rb, library/system/test/kernel_test.rb, package/yast2.changes, package/yast2.spec
The method `Kernel#propose_hibernation?` was returning *true* when the system is running over certain virtualized setups like *hyper-v*. This makes to *yast2-bootloader* to propose the `resume=` kernel parameter in such scenarios, , but it should not do it according to https://jira.suse.com/browse/SLE-12280.
* https://bugzilla.suse.com/show_bug.cgi?id=1180982
* https://trello.com/c/VkjmNIRr/2279-3-yast-bootloader-adds-the-resume-parameter-when-it-shouldnt
Now `Kernel#propose_hibernation?` uses the new method `Arch#is_virtual?` to check whether the system is running on a virtualized setup, does not matter the specific virtualization technology. For now this is enough, but maybe in the future we might need a more fine grained detection. In that case, we could consider to use …
=> Do not propose hibernation on virtual setups

library/packages/src/lib/y2packager/product_upgrade.rb, package/yast2.changes, package/yast2.spec
- https://bugzilla.suse.com/show_bug.cgi?id=1181773
- In Leap 15.3 the product has been renamed from `openSUSE` to `Leap` :scream: 
- I'll keep also the old openSUSE migration (just in case :smiley:)
- Manually tested by Luboš (https://bugzilla.suse.com/show_bug.cgi?id=1181773#c2)
=> Added supported migration "openSUSE Leap 15.3" -> SLES

library/system/src/lib/yast2/fs_snapshot.rb, library/system/src/lib/yast2/fs_snapshot_store.rb, library/system/test/fs_snapshot_store_test.rb, library/system/test/fs_snapshot_test.rb, package/yast2.changes, package/yast2.spec
YaST uses an especial `installation-helper` binary to configure snapper and create snapshots during installation and offline upgrade. However, it does not work with LVM (at least not in all cases). This PR changes the `FsSnapshot` class to use the `snapper` binary (using the `--no-dbus` option) to create snapshots. The configuration phase is still done through `installation-helper`.
Additionally, it introduces a new kind of exception so errors when creating snapshots can be properly handled.
* Related to: https://github.com/yast/yast-update/pull/162 and https://github.com/yast/yast-installation/pull/901.
=> bsc#1180142: do not use 'installation-helper' to create snapshots

library/system/src/lib/yast2/fs_snapshot.rb, library/system/test/fs_snapshot_test.rb
Simplify #1125. While merging the changes to SP2, I realized that it uses the snapper version which is shipped with the DVD, so it is compatible with the `--disable-used-space` option.
=> Use the same command to list snapshots during installation

library/general/src/modules/Report.rb, package/yast2.changes, package/yast2.spec
#1122 introduced a bug in the Report module. See [here](https://github.com/yast/yast-yast2/pull/1122/files#diff-71d0b42ff18d870f2a798fdcfa236622d29ff278fb75e9a1a1d643e72d929d1cR445).
This should fix that bug.
=> Fix bug introduced while adding auto wrapping

library/control/src/modules/ProductControl.rb, package/yast2.changes, package/yast2.spec
> Yast-firstboot executes the clients enabled in its control file. But it shows an exception error when a client is not available (e.g., because the package is not installed). — _**extracted from https://trello.com/c/xA1YyIdv/ (internal link) description**_
**Do not crash**, by checking if the client exists and asking the user what to do (continue or not) when it does not.
* If user decides to continue, the workflow will continue to _:next_ or _:back_ client/step, depending on the previous result
* If not, the installation/firstboot workflow will be completely _:abort_
Only tested manually, since adding unit tests for this complex part of the code if out of the scope of this PR.
| Before | After |
|-|-|
| ![Screenshot_sle15sp3_2021-03-08_09:41:51](https://user-images.githubusercontent.com/ …
=> [ProductControl] Ask if user would like to continue when client is missing

package/yast2.changes, package/yast2.spec, scripts/save_y2logs
How it looks now ( easy to reproduce with Y2DEBUG=1 and slide show ):
=> handle save_y2logs when content modified when creating tarball

library/control/src/modules/ProductControl.rb, package/yast2.changes, package/yast2.spec
Related to #1143, just change buttons labels from `Yes`/`No` to `Continue`/`Abort`.
Also avoid a new crash by fixing a `log.warn` call :confused:
=> [Product Control] Use meaningful button labels

library/cwm/src/lib/cwm/abstract_widget.rb, library/cwm/src/lib/cwm/common_widgets.rb, library/cwm/test/abstract_widget_test.rb, package/yast2.changes, package/yast2.spec
This PR adds a method to determine whether a UI is actually present in the UI. We will use this code to fix [bsc#1184115](https://bugzilla.suse.com/show_bug.cgi?id=1184115), but it could be useful to fix other bugs as well.
[bsc#118411](https://bugzilla.suse.com/show_bug.cgi?id=1184115)
=> Determine whether a widget is present/displayed

doc/yast2.8, package/yast2.changes, package/yast2.spec
- https://bugzilla.suse.com/show_bug.cgi?id=1184681
- The man page was utterly outdated
- Removed Gtk UI
- The `--install` and `--remove` options are obsolete (`zypper` should be preferred)
- Removed list of modules which support command line mode
- Some minor improvements and fixes
<details>
<summary>Rendered Plain Text Version</summary>
```
YAST(8)                      System configuration                      YAST(8)
NAME
YaST  -  "Yet  another  Setup Tool", the installation and configuration
tool
SYNOPSIS
yast2 [ options ] [ module ] [ module specific options ]
DESCRIPTION
YaST can be used to configure the system. It  can  configure  a  common
hardware  (sound cards, printers), network connections (network cards),
network clients and services (like NFS, FTP), as well as a general sys- …
```
=> Updated manual page (bsc#1184681)

library/general/src/lib/y2issues/issue.rb, library/general/test/y2issues/issue_test.rb, package/yast2.changes
Fixes the `Y2Issue::Issue` constructor to accept the location as a string or as a `Location` object. We do not need to release the fix now, so it can wait to the next version.
=> Fix issue location

library/control/src/modules/ProductControl.rb, package/yast2.changes, package/yast2.spec
A call to `Convert.to_symbol` was wrongly changed in https://github.com/yast/yast-yast2/pull/1143, which makes the installation crash with a `NoMethodError (undefined method ``to_sym' for false:FalseClass)` when the result from a client is `false`
* https://bugzilla.suse.com/show_bug.cgi?id=1185561
* https://trello.com/c/Kq990Qba/4698-tw-p3-1185561-ruby-error-in-installation-after-partitioning
A kind of revert to previous code and keep using `result = Convert.to_symbol(result)` instead `result = result.to_sym`
The Bugzilla reference for version 4.3.59 has been fixed, switching from _bsc#1180**59**4_ to _bsc#1180**95**4_
=> [SLE-15-SP3] Do not convert result to sym directly

library/control/src/modules/ProductControl.rb, package/yast2.changes, package/yast2.spec
The same than #1161, but for `master` branch.
It restores a conversion to symbol using `Convert.to_symbol` instead of Ruby `#to_sym` method.
Related to https://bugzilla.suse.com/show_bug.cgi?id=1185561
=> Do not convert result to sym directly

library/general/src/data/country.ycp, library/general/src/data/country_long.ycp
- Remove Catalonia (duplicate for ES)
- Update ca_ES to Spain following other Spanish languages (gl_ES, eu_ES)
=> Fix entries for ES and ca_ES

library/general/src/lib/yast2/equatable.rb, library/general/test/yast2/equatable_test.rb, package/yast2.changes, package/yast2.spec
Objects redefining `#eql?` method should redefine `#hash` method too. These two methods must be paired, otherwise some actions like subtracting arrays could generate unexpected results.
* Related to https://bugzilla.suse.com/show_bug.cgi?id=1186082.
Add a `Equatable` mixin for keep `#eql?` and `#hash` paired.
=> Add Equatable mixin

library/general/src/lib/cfa/login_defs.rb, package/yast2.changes, package/yast2.spec
This is a pre-requisite for https://github.com/yast/yast-users/pull/284
This repository contains a CFA class to deal with login.defs. But it only handles a limited set of configuration parameters. This adds `umask` to that set, since it's needed in order to configure useradd (at some point, the `umask` configuration was part of `/etc/default/useradd` but now it's only present in login.defs).
Taking the opportunity, this PR also adds another parameters that influence the behavior of useradd.
=> CFA: recognize more fields from login.defs

library/general/src/lib/yast2/equatable.rb, library/general/test/yast2/equatable_test.rb, package/yast2.changes, package/yast2.spec
Added improvement already mentioned in:
https://github.com/yast/yast-yast2/pull/1165#discussion_r639537928
Which will be very useful for adopting it in yast2-netnetwork (see https://github.com/yast/yast-network/pull/1228)
=> Make Yast2::Equatable#hash to be fine tuned easelly

library/general/src/lib/installation/autoinst_profile/section_with_attributes.rb, library/general/test/installation/autoinst_profile/section_with_attributes_test.rb, package/yast2.changes, package/yast2.spec
Sometimes, an AutoYaST profile might contain blank values for some properties, for example:
~~~xml
<users config:type="list">
<user>
<username>tux</username>
<password_settings>
<expire/>
<mx>120</max>
<inact>5</inact>
</password_settings>
</user>
</user>
~~~
In the example above, *expire* is empty, which means that the account has no expiration. By default, the *SectionWithAttributes* class converts the empty values to *nil*, so there is no way to distinguish when a properly was set as blank or it was missing in the profile. Such a differentiation is important in some cases like the *expire* option, because in case of blank, an empty string should be written in the /etc/shadow file for the *Expiration Date* field in order to make the account to never expire. And in case of nil (missing …
=> AutoYaST: Allow blank values in SectionWithAttributes

library/general/src/lib/cfa/sysctl_config.rb, package/yast2.changes, package/yast2.spec
Ignore sysctl files that do not use the `.conf` exception. The only exception right now are `/boot/sysctl.conf-*` files.
Fixes https://bugzilla.suse.com/show_bug.cgi?id=1187018.
=> Filter sysctl files

library/general/src/lib/cfa/sysctl_config.rb, package/yast2.changes, package/yast2.spec
Backport #1171 to `SLE-15-SP3`.
=> Filter sysctl *.conf files

library/general/src/lib/y2issues/list.rb, library/general/test/y2issues/list_test.rb, package/yast2.changes, package/yast2.spec
Reason: For Y2Issue::List it is needed sometimes to concat more sources of issues and for such case it is useful to be able to concat Lists. Size is common convenient method too check amount of issues.
Related to work on y2users.
=> Extend issues

library/general/src/lib/installation/autoinst_issues/missing_value.rb, library/general/src/lib/y2issues.rb, library/general/src/lib/y2issues/issue.rb, library/general/src/lib/y2issues/list.rb, library/general/src/lib/y2issues/presenter.rb, library/general/src/lib/y2issues/reporter.rb, library/general/test/y2issues/issue_test.rb, library/general/test/y2issues/list_test.rb, library/general/test/y2issues/presenter_test.rb, library/general/test/y2issues/reporter_test.rb, package/yast2.changes, package/yast2.spec
- This replaces #1177 
- Adapt yast2-users (Y2Users branch): https://github.com/yast/yast-users/pull/314
- Adapt yast2-network: https://github.com/yast/yast-network/pull/1240
During the partial re-implementation of yast2-users, we found a couple of things to be improved in Y2Issues.
1) The Y2Issues severity levels were `:warn` and `:fatal`. But other parts of YaST use slightly different conventions for similar concepts[1]:
- In the module `Report` there are functions line, `Message`,  `Warning` and `Error`.
- In the `<report>` section of the AutoYaST profile, it's possible to define the behavior for the following categories: errors, warnings, messages, yesno_messages.
2) The current implementation of `Y2Issues.report` was too focused in a single use case - showing errors found while …
=> Small reorganization in Y2Issues

library/wizard/src/modules/Progress.rb, library/wizard/test/manual/progress_demo.rb, package/yast2.changes, package/yast2.spec
_**This is the fix for SLE-15-SP3. The merge to master will follow.**_
https://trello.com/c/wC5C2kRW
https://bugzilla.suse.com/show_bug.cgi?id=1187676
Under some circumstances, updating progress in the _Progress_ module can lead to a crash with a UI error "No widget with ID ...".
Another pop-up dialog may be in the way, e.g. during some libzypp callbacks. That will then be the topmost dialog, and of course that dialog does not have the expected widget tree, i.e. not the ReplacePoint that the _Progress_ module wants to modify with `UI.ReplaceWidget()`.
Be more defensive in that _Progress_ module: Check if the expected widget exists in the current dialog before trying to exchange its content.
There was no test environment for the _Progress_ module at all: The only way of testing it was with …
=> Prevent Crash if Replacing Content of Nonexistent Replace Point

library/wizard/src/modules/Progress.rb, library/wizard/test/manual/progress_demo.rb, package/yast2.changes, package/yast2.spec
_**This merges PR #1181 from SLE-15-SP3 to master.**_
https://trello.com/c/wC5C2kRW
https://bugzilla.suse.com/show_bug.cgi?id=1187676
Under some circumstances, updating progress in the _Progress_ module can lead to a crash with a UI error "No widget with ID ...".
Another pop-up dialog may be in the way, e.g. during some libzypp callbacks. That will then be the topmost dialog, and of course that dialog does not have the expected widget tree, i.e. not the ReplacePoint that the _Progress_ module wants to modify with `UI.ReplaceWidget()`.
Be more defensive in that _Progress_ module: Check if the expected widget exists in the current dialog before trying to exchange its content.
There was no test environment for the _Progress_ module at all: The only way of testing it was with a live YaST …
=> Prevent Crash if Replacing Content of Nonexistent Replace Point [merge to master]

library/types/src/modules/URLRecode.rb, library/types/test/urlrecode_test.rb, package/yast2.changes, package/yast2.spec
When editing a repository using the "Edit Parts of the URL" mode, YaST does not handle the dollar sign properly (escaping it to "%24").
* Trello (internal link): https://trello.com/c/BnMnGsu9/
* Bugzilla: https://bugzilla.suse.com/show_bug.cgi?id=1187581
Just include `$` into [`URLRecode.PATH_SAFE_CHARS`](https://github.com/yast/yast-yast2/blob/793a45380e65a642397b4e06bdf082b030702566/library/types/src/modules/URLRecode.rb#L12).
I evaluated (and discarded) the possibility to refactor [`URLRecode`](https://github.com/yast/yast-yast2/blob/793a45380e65a642397b4e06bdf082b030702566/library/types/src/modules/URLRecode.rb) for making it [RFC3986](https://datatracker.ietf.org/doc/html/rfc3986) compliant, but it does not pay off.
Having a look at skelcds it could be checked that `$releasever` was …
=> Do not escape $ in URI paths

library/types/src/modules/URLRecode.rb, library/types/test/urlrecode_test.rb, package/yast2.changes, package/yast2.spec
Fix [bsc#1187581](https://bugzilla.suse.com/show_bug.cgi?id=1187581) for SLE-15-SP2, not escaping "$" when producing the URI from it component parts. See https://github.com/yast/yast-yast2/pull/1183 for more information.
=> [SLE-15-SP2] Do not escape $ in URI paths

library/types/src/modules/URLRecode.rb, library/types/test/url_test.rb, library/types/test/urlrecode_test.rb, package/yast2.changes, package/yast2.spec
Fix bsc#1187581 for SLE-15-SP3, not escaping "$" when producing the URI from it component parts. See #1183 for more information.
=> [SLE-15-SP3] Do not escape $ in URI path

library/types/src/modules/URLRecode.rb, library/types/test/url_test.rb, library/types/test/urlrecode_test.rb, package/yast2.changes, package/yast2.spec
Fix [bsc#1187581](https://bugzilla.suse.com/show_bug.cgi?id=1187581) for SLE-15-SP3, not escaping "$" when producing the URI from it component parts. See #1183 for more information.
=> Do not escape $ in URI path

package/yast2.changes
This PR fix a changelog bug reference and also a typo introduced in https://github.com/yast/yast-yast2/pull/1167. The issue has been reported by @bmwiedemann
=> Fix bug reference and typo

library/types/src/modules/URL.rb, library/types/src/modules/URLRecode.rb
As suggested during the review of https://trello.com/c/BnMnGsu9/ (internal link), point developers to the right tools for dealing with (libzypp)URLs.
It mentions not only the [URI](https://ruby-doc.org/stdlib-3.0.2/libdoc/uri/rdoc/URI.html) Ruby standard module, but also the _recently_ added [`Y2Packager::ZyppUrl`](https://github.com/yast/yast-yast2/blob/SLE-15-SP3/library/packages/src/lib/y2packager/zypp_url.rb) (see #1071), which allows dealing with libzypp URLs.
=> [SLE-15-SP3] Discourage the use of old URL modules

library/types/src/modules/URL.rb, library/types/src/modules/URLRecode.rb
Same than https://github.com/yast/yast-yast2/pull/1190, but for `master` (future `SLE-15-SP4`) branch.
=> Discourages the use of old URL modules

library/systemd/src/lib/yast2/systemd/unit_properties.rb, package/yast2.changes, package/yast2.spec
- https://trello.com/c/8GYaBEp6/2606-2-new-systemd-states
- https://bugzilla.suse.com/show_bug.cgi?id=1190163
Related YaST PRs:
- https://github.com/yast/yast-services-manager/pull/214 (master)
- https://github.com/yast/yast-services-manager/pull/215 (check_systemd_states branch)
The relevant systemd commit is
https://github.com/systemd/systemd/pull/12176/commits/380dc8b0a25f544269fdff7d9fd0e488fb374031
Also, in src/core/unit.c, for the UNIT_MAINTENANCE state, unit_start returns -EAGAIN while unit_stop has no special case.
Therefore we treat "maintenance" as basically "active".
=> Added "maintenance" to Yast2::Systemd::UnitProperties::ACTIVE_STATES

package/yast2.changes
Follow-up of #1196. Replaces PM-2620 reference with the epic one.
=> Replace PM-2620 with the SLE-20563 reference

library/packages/src/modules/PackageSystem.rb, package/yast2.changes, package/yast2.spec
- https://bugzilla.suse.com/show_bug.cgi?id=1190228
- The products from addon modules are not selected to install, see the screenshot
- It turned out that the products actually *are* selected after adding the repositories
- But the selection is lost when reaching the installation summary
- Further debugging revealed the the selection is lost after calling `Pkg.SourceStartCache` which (re)loads the repositories
- That's actually not needed during installation, that code is mainly intended for installed system
- In the past this was OK, maybe some libzypp behavior has been changed...
- The code which loads the repositories was fixed to avoid reloads when at least one repository is defined
- During installation, where at least one repository is present, it will skip the repository load 
- In …
=> Fixed losing the product selection (bsc#1190228)

library/general/src/lib/ui/ui_extension_checker.rb, package/yast2.changes, package/yast2.spec
https://bugzilla.suse.com/show_bug.cgi?id=1192650
https://trello.com/c/bM1EFCcS
When clicking on a downloaded RPM in the desktop or in the web browser, there was a crash.
This uses a MIME association between MIME type _application/x-rpm_ and a YaST .desktop file that ultimately calls `y2start sw_single <mypackage.rpm>`.
But because this adds arguments to the command line, it does not create a UI immediately (i.e. it does not load and execute a libyui plug-in); it delays that as long as possible because normally, YaST in CLI (command line interface) mode is not supposed to open any windows if it can be avoided at all.
In this case, however, it always opens a window anyway: That's the whole point of using the `sw_single` YaST module instead of a zypper command line like `zypper in …
=> Force Creating the UI before Checking -pkg etc. UI Plug-ins

library/control/src/modules/WorkflowManager.rb, library/control/test/workflow_manager_test.rb, library/packages/src/lib/packages/package_downloader.rb, library/packages/src/lib/packages/package_extractor.rb, library/packages/src/lib/y2packager/exceptions.rb, library/packages/src/lib/y2packager/package.rb, library/packages/test/lib/package_downloader_test.rb, library/packages/test/lib/package_extractor_test.rb, library/packages/test/y2packager/package_test.rb, package/yast2.changes, package/yast2.spec
Related to [bsc#1193148](https://bugzilla.suse.com/show_bug.cgi?id=1193148).
Do not crash when it is not possible to fetch the release notes package. It does not fix the real issue (why is the release notes package missing?), but at least the installer does not crash.
The initial fix was rather easy: just catching `PackageDownloader::FetchError` and `PackageExtractor::ExtractionFailed`. However, these exceptions look like an implementation detail from the outside: the caller needs to know that `PackageExtractor` and `PackageDownloader` are used by `Product#download`.
So after a short discussion with @ancorgs, he suggested following the same approach as `Y2Storage`: define a set of [domain-specific errors](https://github.com/yast/yast-storage-ng/blob/master/src/lib/y2storage/exceptions.rb). …
=> Handle release notes error

library/packages/src/lib/y2packager/product.rb, library/packages/src/lib/y2packager/product_reader.rb, library/packages/test/y2packager/product_reader_test.rb, package/yast2.changes, package/yast2.spec
yast2.rpm counterpart to https://github.com/yast/yast-update/pull/175.
=> bsc#1193212: add Product#register_target

library/general/src/modules/Popup.rb, library/general/test/popup_test.rb, package/yast2.changes, package/yast2.spec
- Unify the internal button IDs
- The new [Yast2::Popup]() class use the `:yes` and `:no` IDs while the old `Popup` module uses the `:yes` and `:no_button` IDs
- That's inconsistent and makes testing via libyui REST API more difficult as you need to know which implementation is used to display a particular popup
- So let's use the same IDs everywhere :+1: 
- Additionally the code has been refactored and simplified
=> Popup.YesNo(): Unify the internal [No] button ID (bsc#1193326)

library/system/src/lib/yast2/fs_snapshot.rb, library/system/src/lib/yast2/fs_snapshot_store.rb, library/system/test/fs_snapshot_store_test.rb, library/system/test/fs_snapshot_test.rb, package/yast2.changes, package/yast2.spec
Backport fix for [bsc#1180142](https://bugzilla.suse.com/show_bug.cgi?id=1180142) to SLE 12 SP3. Please, check #1125 for details about the original fix.
Related to:
* https://github.com/yast/yast-installation/pull/1003
* https://github.com/yast/yast-update/pull/176
Manually tested upgrading from SLE 12 SP2 to SLE 12 SP4.
=> Backports fix for bsc#1180142 to SLE 12

package/yast2.changes
While merging #1211 into `SLE-12-SP4`, I found out that #893 was not mentioned in the changes file.
=> Add a missing entry in the changes file

library/commandline/test/commandline_test.rb
The command line does some assertions on the WFM and Report internals. So when they change, the test breaks. Asserting on a private method is not the ideal solution, but it moves the test one level up and it does not break so easily.
=> Do not check Report internals in the commandline test

library/general/src/lib/yast2/rel_url.rb, library/general/test/yast2/rel_url_test.rb, package/yast2.changes, package/yast2.spec
- Related to https://jira.suse.com/browse/SLE-22669
- This PR adds support for evaluating the `relurl://` URLs
- It will be used by other YaST modules (self-update)
- It internally uses the [File.expand_path](https://ruby-doc.org/core-2.5.0/File.html#method-c-expand_path) Ruby function to convert the relative path to absolute.
- The advantage is that it also supports going up in the tree using the parent directory notation (`../`)
- The disadvantage is that some corner cases must be handled specifically, e.g. it replaces `~` with the home directory path on the local system which is not what you would expect in URLs.
- Tested with unit tests with lots of corner cases.
=> Added RelURL class (jsc#SLE-22669)

library/general/src/lib/yast2/rel_url.rb, library/general/test/yast2/rel_url_test.rb, library/packages/test/test_helper.rb, package/yast2.changes, package/yast2.spec, test/test_helper.rb
- Fixes a [Jenkins crash](https://ci.suse.de/job/yast-yast-yast2-master/173/console) ("component cannot import namespace 'InstURL'").
- The problem was that the `Yast::InstURL` module is part of the `yast2-packager` package, but we cannot build depend on it to avoid circular dependecies.
- That module is mocked at some else unit tests so it depended on the order of executing the tests, if the RelURL test was executed too early the `Yast::InstURL` module was not mocked yet and it crashed.
- Fixed by moving the mock to the top level test helper.
=> Fixed RelURL unit test randomly crashing

library/general/src/lib/yast2/rel_url.rb, library/general/test/yast2/rel_url_test.rb, package/yast2.changes, package/yast2.spec, test/test_helper.rb
It turned out that the `URI` class processes FTP URL paths a bit differently. Normally you have to use an absolute path otherwise you get an exception:
```
irb(main):001:0> u = URI("http://example.com")
=> #<URI::HTTP http://example.com>
irb(main):002:0> u.path = "path"
Traceback (most recent call last):
4: from /usr/bin/irb:11:in `<main>'
3: from (irb):2
2: from /usr/lib64/ruby/2.5.0/uri/generic.rb:819:in `path='
1: from /usr/lib64/ruby/2.5.0/uri/generic.rb:771:in `check_path'
URI::InvalidComponentError (bad component(expected absolute path component): path)
irb(main):003:0> u.path = "/path"
=> "/path"
```
But FTP URL is escaped when the path starts with `/`:
```
irb(main):001:0> u = URI("ftp://example.com")
=> #<URI::FTP ftp://example.com/>
irb(main):002:0> u.path = "/path"
=> "/path" …
```
=> Fixed RelURL to work properly with the FTP URLs

library/control/src/modules/WorkflowManager.rb, package/yast2.changes, package/yast2.spec
Reinitializing the repositories during upgrade to `/` makes the process fail. The problem is that, in that case, we need to use repositories of the system we are updating too (`/mnt`) and, after that call, they are gone.
See [bsc#1193784](https://bugzilla.suse.com/show_bug.cgi?id=1193784) and [bsc#1192437](https://bugzilla.suse.com/show_bug.cgi?id=1192437).
=> bsc#1193784: do not reinitialize repos during upgrade

library/packages/src/lib/y2packager/resolvable.rb, library/packages/test/y2packager/resolvable_test.rb, package/yast2.changes, package/yast2.spec
We recently have updated rubocop to 0.71.0 version in **yast2-installation** renaming the **Y2Packager::Resolvable.any?** call to **Y2Packager::Resolvable.none?** automatically, but the **.none?** method is not implemented
- https://bugzilla.suse.com/show_bug.cgi?id=1194387
Added **Y2Packager::Resolvable.none?** method in order to fix the crash but also prevent future rubocop auto change issue.
https://github.com/yast/yast-installation/pull/1009/files#diff-9e5517485ccbd905e33ffea54a28ce8474b226e3faea35dc1893f28ee769b70aR244
=> Add Y2Packager::Resolvable.none? method

library/cwm/src/lib/cwm/dialog.rb, library/cwm/src/lib/cwm/popup.rb, library/general/test/ui/installation/layout_test.rb, package/yast2.changes, package/yast2.spec
- The fix for Ruby 3.0 (#1225) caused a regression in Ruby 2.5
- Also added missing `Stage.normal` mock, for me the tests failed when running locally
=> Fixed test failure in Ruby 2.5

library/cwm/src/lib/cwm/dialog.rb
- Fix up for #1228
- The super is actually not needed as the class does not inherit from any base class (besides implicit `Object`)
- Tested with `YAST_SUBMIT=sle_latest rake osc:build`, builds fine
=> Remove useless "super"

library/general/src/modules/Report.rb, library/general/test/report_test.rb, package/yast2.changes, package/yast2.spec
A hash was being passed to a method expecting the hash would be interpreted as a set of keyword params. That works in Ruby 2 as-is, but in Ruby 3 the `**` operator must be used.
The problem was detected by me when trying to open two instances of the Partitioner and also by the internal SUSE openQA instance during this test: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP4&build=Y.52.5&groupid=125
=> Adapt Report.yesno_popup to Ruby 3 (bsc#1193192)

library/cwm/src/lib/cwm/dialog.rb, library/cwm/test/dialog_test.rb, package/yast2.changes, package/yast2.spec
Method `Dialog#run` delegates arguments to `Dialog.new`. Argument delegation is handled differently in ruby 2.6 and before, see [explanation here](https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/):
In ruby 2.7 or later, an empty Hash argument is automatically converted and absorbed into **kwargs, and the delegation call removes the empty keyword hash, so no argument is passed to target:
~~~
def target(*args, **kwargs)
end
def foo(*args, **kwargs, &block)
target(*args, **kwargs, &block)
end
foo(1)       #=> Ruby 2.7: calls target(1)
foo(1)       #=> Ruby 2.6: calls target(1, {})
~~~
https://bugzilla.suse.com/show_bug.cgi?id=1194984
Do not pass empty `**kwargs` to the target method.
* Added unit test, and checked in different ruby …
=> Fix CWM dialog

library/general/src/modules/PackagesProposal.rb, library/general/test/packages_proposal_test.rb, library/packages/src/include/packages/common.rb, library/packages/src/modules/Package.rb, library/packages/src/modules/PackageAI.rb, library/packages/src/modules/PackageSystem.rb, library/packages/test/package_ai_test.rb, library/packages/test/package_system_test.rb, library/packages/test/package_test.rb, package/yast2.changes, package/yast2.spec
This PR is part of the plan to unify `Package.rb`, `PackageSystem.rb`, and `PackageIA.rb` and, by the way, get rid of `PackagesCommonInclude`. See https://trello.com/c/GnnQQcDa for further details.
Once we merge this code, we should avoid calling `PackageSystem` methods and use `Package` instead. This module should know whether to forward the call to `PackageSystem` or `PackageAI`. 
The following changes are included:
* `CheckAndInstallPackages*` are now implemented in the `Package` module. For backward compatibility reasons, the `PackageSystem` implements those methods too (although it forwards those calls to the `Package` module).
* Add support for packages to uninstall (taboos) to the `PackagesProposal`, so `PackageAI` does not keep its list of packages anymore.
* Drop the …
=> Unify `Package`, `PackageSystem` and `PackageAI`

package/yast2.changes, package/yast2.spec, scripts/yast2
On aarch64 installer/YaST sometimes failed to load libsuseconnect.so
with "cannot allocate memory in static TLS block" error.
Loading the library before others solves the problem until a better
solution is found.
=> Preload libsuseconnect.so if avaiable (bsc#1194996)

library/packages/src/lib/y2packager/new_repository_setup.rb, library/packages/test/y2packager/new_repository_setup_test.rb, package/yast2.changes, package/yast2.spec
- Related to https://bugzilla.suse.com/show_bug.cgi?id=1194453
- Added Y2Packager::NewRepositorySetup class to track new repositories
- Similar to the already existing [Y2Packager::OriginalRepositorySetup](https://github.com/yast/yast-yast2/blob/4f0560a55f0b4ece41ed50063fd7baf00cd8eedc/library/packages/src/lib/y2packager/original_repository_setup.rb#L28) class 
- This class will used from other packages (y2-registration and y2-installation)
- 4.4.42
During upgrade YaST removes the old repository services (e.g. SLE12) from the system. Unfortunately when upgrading via RMT it returns the same name for the new service (SLE15), YaST did not expected that and removed the "old" service from the system. But this accidentally removed the new service and that made troubles during upgrade.
- Added …
=> Added Y2Packager::NewRepositorySetup class (bsc#1194453)

package/yast2.changes, package/yast2.spec, scripts/yast2-funcs
- Setting the `Y2STYLE` environment variable to `installation-light.qss` before starting the installer does not take effect, the variable is always set to `installation.qss`.
- Related to [jsc#SLE-20547](https://jira.suse.com/browse/SLE-20547)
- Set the default value only when not set already. 
- Handle the `XCURSOR_THEME` value the same way.
Tested manually, with `Y2STYLE=installation-light.qss` and the manually added `installation-light.qss` file it looks like this:
=> Keep the user defined $Y2STYLE and $XCURSOR_THEME environment variables

library/xml/src/modules/XML.rb, library/xml/test/xml_test.rb, package/yast2.changes, package/yast2.spec
Port https://github.com/yast/yast-yast2/pull/1244 to SLE15-SP4/TW.
- https://bugzilla.suse.com/show_bug.cgi?id=1195910
- https://trello.com/c/1uUwxpq6
Surrounding white space in some elements may be desired. Like in scripts or other file content.
Do not strip surrounding white space when reading XML CDATA elements. And create CDATA elements when generating XML if an element contains surrounding white space.
This reworks https://github.com/yast/yast-yast2/pull/1243.
I did some checks and prior to SLE15-SP3 we did preserve all white space in CDATA elements. This also does not pose a problem in script elements. Leading white space is ok there.
So, this pull request fully restores the old behavior.
=> do not strip surrounding white space in CDATA XML elements (bsc#1195910)

doc/yast-invoking-external-commands.md, package/yast2.changes
This is a more permanent place than the initial [Gist](https://gist.github.com/shundhammer/382faaae5371087e7afb13007510c6d5).
This documents how calling an external command in YaST works, how it should be used, and it covers security aspects.
This does not have a version bump since there is no code change, so it can wait to be submitted until there is a code change.
- https://github.com/yast/yast-iscsi-client/issues/111
- https://bugzilla.suse.com/show_bug.cgi?id=1196086
- https://trello.com/c/vySWWKUv/2727-3-security-research-iscsi-the-iscsi-commands-are-moving-from-sbin-to-usr-sbin
- https://github.com/yast/yast.github.io/issues/172
=> New Doc: Invoking External Commands

package/yast2.changes, package/yast2.spec, scripts/yast2
https://bugzilla.suse.com/show_bug.cgi?id=1196326
https://trello.com/c/YlPWQ3YP/
PR #1236 added a workaround for a long-standing problem on the aarch64 platform: An error
_Can't load libsuseconnect.so_  due to an error  _cannot allocate memory in static TLS block_.
A well-known workaround in the aarch64 Linux world is to force-load the affected library with `LD_PRELOAD`. That is what that PR did.
But since that is inherited by child processes, it also affects them, considerably adding to their memory footprint since now it force-links (!) _libsuseconnect.so_ to every binary started that way, and YaST starts a lot of external binaries; for example for storage probing.
Don't use `LD_PRELOAD`; revert that first workaround.
Use `LD_PRELOAD`, but sanitize it immediately after starting the YaST …
=> Revert LD_PRELOAD Change

library/network/src/lib/network/susefirewall.rb, library/network/src/lib/y2firewall/firewalld.rb, library/network/src/lib/y2firewall/firewalld/api.rb, library/network/src/modules/DnsServerAPI.pm, library/network/src/modules/NetworkService.rb, library/network/test/y2firewall/firewalld_test.rb, library/packages/src/modules/Package.rb, library/packages/src/modules/Product.rb, library/packages/test/package_test.rb, library/packages/test/product_test.rb, package/yast2.changes, package/yast2.spec
In the recent past, we decided to merge `Package`, `PackageSystem` and `PackageAI`. The idea was to use `Package` as the entry point and rely on `PackageAI` and `PackageSystem`, depending on the situation. However, we found out later that things are not that easy. See [bsc#1196963](https://bugzilla.suse.com/show_bug.cgi?id=1196963).
There might a scenario where you want to force Package to work with the real packages. For instance, while reading the configuration during a `clone_system` operation: the mode is still `autoinst_config` but you are dealing with the underlying system. In those cases, you can force `Package` to work with `PackageSystem`. `Package` to work with `PackageSystem`.
As an escape hatch, we have decided to add an option to Package to override the decision about which …
=> Force package backend

library/general/src/lib/ui/delayed_progress_popup.rb, library/general/src/lib/ui/examples/delayed_progress_1.rb, library/general/src/lib/ui/examples/delayed_progress_2.rb, library/general/src/lib/ui/examples/delayed_progress_almost_done.rb, library/packages/src/lib/packages/file_conflict_callbacks.rb, library/packages/test/file_conflict_callbacks_test.rb, package/yast2.changes, package/yast2.spec
**_This is for SLE-15-SP4._**
Version for master: _TBD_
https://bugzilla.suse.com/show_bug.cgi?id=1195608
https://trello.com/c/38oLzang/
During package installation with the new unified single progress bar that handles downloads as well as installing the packages, after the download phase, there is a very disruptive new progress bar that overlays the previous one (in the main window wizard) and usually just flashes by.
Only when watching an installation video in slow motion, it becomes apparent that this is the progress of libzypp checking for file conflicts. Usually that happens so fast it just flickers shortly, i.e. this whole file conflict check could simply be ignored; but even then the flickering is disruptive.
But it doesn't get better one bit if it takes longer, so the user can …
=> DelayedProgressPopup for File Conflicts Progress during Package Installation

library/general/src/lib/ui/delayed_progress_popup.rb, library/general/src/lib/ui/examples/delayed_progress_1.rb, library/general/src/lib/ui/examples/delayed_progress_2.rb, library/general/src/lib/ui/examples/delayed_progress_almost_done.rb, library/packages/src/lib/packages/file_conflict_callbacks.rb, library/packages/test/file_conflict_callbacks_test.rb, package/yast2.changes, package/yast2.spec
**_This is for master / Factory / Tumbleweed._**
This merges https://github.com/yast/yast-yast2/pull/1250 to master / Factory / Tumbleweed.
https://bugzilla.suse.com/show_bug.cgi?id=1195608
https://trello.com/c/38oLzang/
During package installation with the new unified single progress bar that handles downloads as well as installing the packages, after the download phase, there is a very disruptive new progress bar that overlays the previous one (in the main window wizard) and usually just flashes by.
Only when watching an installation video in slow motion, it becomes apparent that this is the progress of libzypp checking for file conflicts. Usually that happens so fast it just flickers shortly, i.e. this whole file conflict check could simply be ignored; but even then the flickering is …
=> DelayedProgressPopup for File Conflicts Progress during Package Installation [master]

library/packages/test/slide_show_test.rb, library/packages/test/test_helper.rb, package/yast2.spec
Autobuild for this package fails with unit tests:
```
Failed to load Module 'SlideShow' due to: cannot load such file -- y2packager/product_spec
```
https://ci.suse.de/job/yast-yast-yast2-SLE-15-SP4/4/console
The .spec file of this package (yast2.spec) does not _require_ or _buildrequire_ yast2-packager, so AutoBuild does not install it in the build environment. But adding it would mean a cyclic dependency between packages _yast2_ (this package) and _yast2-packager_.
This adds a workaround for the real-world problem, disregarding the academic problem that a system using the SlideShow does indeed not install _yast2-packager_:
This overrides Ruby `Kernel::require` with a custom version that skips loading some few predefined Ruby libraries; like the one that could not be loaded here.
Not in …
=> Fix Unit Tests in AutoBuild

library/packages/src/modules/SlideShow.rb, library/packages/test/slide_show_test.rb, library/packages/test/test_helper.rb, package/yast2.changes, package/yast2.spec
https://trello.com/c/CeYLzrD1/
https://bugzilla.suse.com/show_bug.cgi?id=1196674
Users installing many machines, especially with AutoYaST, might not be sure which product they are installing when almost everything is automated. They (or some automatism) might or might not have picked the correct AutoYaST profile, but they can't verify that.
Show the name of the base product while packages are being installed in the new unified installation progress step, but only during system installation or upgrade (no matter if using AutoYaST or not); not in the installed system.
Only the _base_ product is shown, not any add-on products. This is in line with the reduction of this progress reporting to one single progress bar with only the overall progress, not individual packages.
Notice that many …
=> Show what Product is Being Installed [master / Factory]

library/packages/src/modules/SlideShow.rb, library/packages/test/test_helper.rb, package/yast2.changes, package/yast2.spec
pull request https://github.com/yast/yast-yast2/pull/1253 cause several build failures when module even transitively need SlideShow, but does not need packager to build itself.
Load packager library only dynamic and handle if it is not available.
- adapted unit tests to demonstrate that mocking of packager is not needed
not affected
=> Fix packager dep

library/packages/src/modules/PackageSystem.rb, package/yast2.changes, package/yast2.spec
When running dns-server in container it wants to install bind. But install it to container and not machine itself, so named cannot run.
Init properly PackageSystem when root is changed.
=> Package system container

library/desktop/src/clients/menu.rb, package/yast2.changes, package/yast2.spec
- Always display the YaST modules installed in the system root
- When running in a container display the modules installed in the container (originally it displayed the modules from the host system which might not contain any YaST module)
- 4.5.7
- The Qt control center is not affected, it always loads the files from the system root.
- The started YaST modules run in a new separate process so they use the chrooting as expected, they correctly manage the host system
=> Fixed text mode control center in container (bsc#1199840)

library/packages/src/modules/PackageSystem.rb, package/yast2.changes, package/yast2.spec
- YaSt when running in a container fails installing the needed packages
- The problem is that it uses the repositories configured in the container, not the repositories from the host
It turned out that the problem is in the `Pkg.GetSolverFlags` call which is called *before* initializing libzypp. In that case libzypp automatically initializes itself, but it uses by default the system root (`/`) which is the container. The libzypp initialization later done from YaST does not change anything as libzypp is already initialized.
Also it initialized the libzypp in a wrong order. The libzypp target always needs to be initialized *before* initializing the libzypp sources. The reason is that the target defines which GPG keys and config file (`zypp.conf`) are used. When initializing in wrong order …
=> Fixed libzypp initialization (related to bsc#1199840)

library/packages/src/modules/Package.rb, package/yast2.changes, package/yast2.spec
The feature was not supported. Some packages do not have "default" placeholder but uses versions in name instead (php8), so simple patterns comes handy.
- https://bugzilla.suse.com/show_bug.cgi?id=1200016
implemented simple wrapper which uses y2packager/resolvable
=> Added method to find a package according to a pattern

library/packages/src/lib/packages/file_conflict_callbacks.rb, library/packages/test/file_conflict_callbacks_test.rb, package/yast2.changes, package/yast2.spec
YaST crash when checking file conflicts because of a `Yast::UI.PollInput` call when there is no UI (the requirements for displaying the [Yast::DelayedProgressPopup](https://github.com/yast/yast-yast2/blob/c43b61f0fbb7c9a981f66de3b1c547e191552527/library/general/src/lib/ui/delayed_progress_popup.rb) were not fulfilled)
- https://bugzilla.suse.com/show_bug.cgi?id=1201924
- https://openqa.suse.de/tests/9223678#step/yast2_apparmor/11 (internal and temporary link)
- https://trello.com/c/JijjL7Fx (internal link)
Fix the [Yast::FileConflictCallbacks#progress method](https://github.com/yast/yast-yast2/blob/161f0cc260acbc8d810657f380510e2c2be3f02d/library/packages/src/lib/packages/file_conflict_callbacks.rb#L127-L140) for polling user input only if the delayed progress popup dialog is open.
- …
=> Do not crash when checking file conflicts and delayed progress popup is not shown

library/network/src/modules/NetworkService.rb, library/network/test/network_service_test.rb, package/yast2.changes, package/yast2.spec
During installation, if apparently the selected network service has not been modified (wicked is default backend) the service is not enabled explicitly in the target system which could end with it disabled. 
- https://bugzilla.suse.com/show_bug.cgi?id=1202479
Added a parameter in order to force an enablement of the selected network service even when if has not been modified.
- *Added a new unit test*
=> NetworkService enforce selected network service is enabled during installation (bsc#1202479)

library/packages/src/modules/Package.rb, package/yast2.changes, package/yast2.spec
```by_pattern``` moved into http-server module as it currently is the only user.
revokes https://github.com/yast/yast-yast2/pull/1262
see also https://github.com/yast/yast-http-server/pull/58
=> Moved by_pattern into http-server module

library/system/src/lib/yast2/clients/view_anymsg.rb, library/system/test/clients/view_anymsg_test.rb, package/yast2.changes, package/yast2.spec
When trying to open certain deprecated log files, the `view_anymsg` client may suggest to install `yast2-journal`. It basically does the following:
- It asks the user whether `journal` should be called instead.
- In case `journal` is not installed, it installs it (if possible).
- Open `journal` unless is not there and installation failed.
That mechanism is quite broken when `view_anymsg` is containerized. The root of the problem is that `view_anymsg` relies on `Package.Install("yast2-journal")` without previously checking whether the client is already there. Since YaST's package manager checks for packages in the host system, it concludes `yast2-journal` is not available and the whole process fails even if the `journal` client is actually part of the same container.
Check for the …
=> Container-compatible check for the journal client

library/general/src/lib/installation/proposal_client.rb
In theory, the different proposal clients displayed in the installation summary have the option to incorporate their own help texts to the general help of the summary screen. The mechanism, which BTW was broken (fixed in a separate pull request, see below), is based on the hashes provided by the corresponding proposal clients. But the documentation at `Installation::ProposalClient` was wrong. The "help" element should be part of the "description" hash, not of the "make_proposal" one.
Fix the documentation by moving the "help" keyword to the right place.
- https://github.com/yast/yast-installation/pull/1060 fixes the broken mechanism, which has always used the "description" hash (the pull request does not change that).
=> Small fix in documentation of ProposalClient

library/system/src/lib/yast2/execute.rb, library/system/test/execute_test.rb, package/yast2.changes, package/yast2.spec
Cheetah by default logs all input and output from commands and also arguments. It can contain sensitive information.
- https://bugzilla.suse.com/show_bug.cgi?id=1201962
Add specific cheetah logger class that can filter out certain streams.
- *Added a new unit test*
=> Reduced recorder

library/general/src/lib/yast2/rel_url.rb, library/general/test/yast2/rel_url_test.rb, package/yast2.changes, package/yast2.spec
- https://trello.com/c/CAytlL3W
- https://jira.suse.com/browse/SLE-22578
- https://jira.suse.com/browse/SLE-24584
`Yast2::RelURL` does a nice handling of relative URLs. But `#postprocess_url` messes up the results and always returns URLs starting with `//` (exactly two slashes). This is wrong.
Ruby's URI class works just fine. Just leave it at that. If YaST really relies on something like `file://foo/bar` this should be fixed in YaST (but I don't think this is the case).
- https://github.com/openSUSE/linuxrc/pull/299
- https://github.com/yast/yast-installation/pull/1063
- https://github.com/yast/yast-autoinstallation/pull/852
=> remove #postprocess_url from RelURL class

library/cwm/test/cwm_test.rb, library/system/test/execute_test.rb, package/yast2.changes, package/yast2.spec
- https://bugzilla.opensuse.org/show_bug.cgi?id=1204871 "- [Staging] rubygem-rspec-* 3.12 breaks various yast modules build"
- this description is copied from https://github.com/yast/yast-registration/pull/584 as this is a base library. Further PRs will just link here
New rspec-mocks distinguish between hash and keyword arguments passed to `with`.
The tested code does use hashes but we've used keywords in tests because
it's shorter to write. Fixed.
rspec-mocks 3.11.2 / 2022-10-25:
> Bug Fixes: Support keyword argument semantics when constraining argument
> expectations using with on Ruby 3.0+ with instance_double
> https://github.com/rspec/rspec-mocks/pull/1473
Use hashes in tests instead of keywords
Not affected
=> Fix hash vs keyword arguments in RSpec expectations (bsc#1204871)

library/general/src/lib/yast2/arch_filter.rb, library/general/test/yast2/arch_filter_test.rb, package/yast2.changes, package/yast2.spec
There are multiple places where we need to specify in text form condition to apply only to certain hardware architectures and it is not unified so far.
Related to https://trello.com/c/C3apZtHv/3231-d-installer-support-for-dynamic-configuration
Unified solution is based on specification of  subvolume handling https://github.com/yast/yast-storage-ng/blob/master/src/lib/y2storage/subvol_specification.rb#L119
There are some improvements to it:
- allowing white spaces
- case insensitivity
- support for 'all' method
- raise exception when invalid element of string  is used
- new unit tests are added
There is one more place which define architecture filtering - in workflows https://github.com/yast/yast-yast2/blob/master/library/control/src/modules/WorkflowManager.rb#L209 Question is if we want …
=> add arch filter class to unify architectures specification

library/desktop/src/clients/menu.rb, package/yast2.changes, package/yast2.spec
With ncurses UI, the YaST Control Center shows a help button which opens an empty popup (help texts provided by the client are missing).
Note: this problem only affects to the ncurses UI because the help button is not offered in the Qt UI.
* https://bugzilla.suse.com/show_bug.cgi?id=1206919
The help button's option `:helpButton` was used in a wrong way: if it is used, the click/activate event of that button is handled purely internal in libyui. In that case, libyui traverses up the widget hierarchy to find the next widget that has a property `:helpText` set and uses that text for a (UI internal) help window's content.
In this case, the button has that option, but the application wants to handle the event itself (there is no widget with`:helpText` property in the hierarchy).
Removing the …
=> Fix help button in YaST Control Center

library/packages/src/lib/y2packager/zypp_url.rb, library/packages/test/y2packager/zypp_url_test.rb, package/yast2.changes, package/yast2.spec
Since Ruby 3.2, URI("dir:///foo").to_s no longer returns "dir:/foo" and it makes tests fail in yast2-packager:
If we route the 3-slash form via C++ zypp::Url, it gets normalized to a single slash, see also
https://github.com/openSUSE/libzypp/issues/441
- https://trello.com/c/jRe5bWVE
- https://bugzilla.suse.com/show_bug.cgi?id=1207239
In the class that wraps zypp::Url, consider those equal
It fixes a comparison in PkgFinishClient#added_by_installer?
- Added a new unit test
N/A
=> Allow dir:///foo to equal dir:/foo (bsc#1207239)

library/network/src/modules/DnsServerAPI.pm, package/yast2.changes, package/yast2.spec
_**This is for the SLE-15-SP5 branch.**_
https://bugzilla.suse.com/show_bug.cgi?id=1208833
https://trello.com/c/s0A0v2gw/
Build failure in SLE-15-SP5 for yast2-dns-server and yast2-http-server:
https://build.suse.de/package/live_build_log/Devel:YaST:Head/yast2-dns-server/SUSE_SLE-15-SP5_GA/x86_64
```
[sh @ balrog] ...yast/yast-dns-server/test 24 % rake test:unit 
(in /work/src/yast/yast-dns-server)
rspec --color --format doc 'test/dns_server_ui_test.rb' 'test/main_test.rb' 'test/service_widget_helpers_test.rb' 'test/dns_server_cmdline_test.rb' 'test/dns_server_test.rb' 'test/etc_named_parsing_test.rb' 'test/masterzone_test.rb'
Traceback (most recent call last):
20: from /usr/bin/rspec:23:in `<main>'
19: from /usr/bin/rspec:23:in `load'
18: from …
```
=> Restore Missing DnsServerAPI.pm

library/system/src/modules/Initrd.rb, package/yast2.changes, package/yast2.spec
SLE 15 SP6 branch is based on SLE15 SP5 maintenance branch. So fixes done in master can be sometimes useful also for SP6.
Skip reapply of DNS drop as it is needed in SLE15. Backport mkinitrd drop (#1289).
=> Backport sp6

library/network/src/lib/y2firewall/firewalld/zone_reader.rb, library/network/test/y2firewall/firewalld/zone_reader_test.rb, package/yast2.changes, package/yast2.spec
A recent change in firewall-cmd --list-all-zones output is breaking the zones reader as the default zone is not read properly and therefore it is considered to be deleted.
- https://bugzilla.suse.com/show_bug.cgi?id=1216534
Adapted the firewalld zones reader ignoring anything after the zone name.
- *Adapted current unit test*
=> Fix zones reader (bsc#1216534)

library/packages/src/lib/y2packager/repository.rb, library/packages/test/repository_test.rb, package/yast2.changes, package/yast2.spec
- Just extend the `Repository` class to allow refreshing the repository
- To be used elsewhere, related to https://bugzilla.suse.com/show_bug.cgi?id=1215884 fix
=> Added Repository#refresh method (related to bsc #1215884)

library/system/src/modules/Kernel.rb, library/system/test/kernel_test.rb, package/yast2.changes, package/yast2.spec
In agama there are no /etc/install.inf, but kernel parsing depends on it. Result is that kernel parameters are not properly passed to installed system.
Read /proc/cmdline when /etc/install.inf is not available.
=> Adapt kernel

library/types/src/modules/Hostname.rb, package/yast2.changes, package/yast2.spec
**This is the original PR for SLE-15-SP5.** Merge PRs for SLE-15-SP6 and master will follow
https://bugzilla.suse.com/show_bug.cgi?id=1219920
Modern DNS setups require using a leading underscore for hostnames in some situations, e.g. `_mydomain.example.com`. But that is not possible to enter in the YaST DNS Server module: Underscores are generally rejected.
Allow a leading underscore for host and domain names. Not just anywhere, just as the leading character.
Since the check is in `Hostname.rb` which belongs to the _yast2_ package (repo _yast-yast2_), this is not in the `yast2-dns-server` package where it might be expected.
This allows a leading underscore for _all_ components of a FQDN in all circumstances. Users need to have some expertise to know when that is suitable.
The error …
=> Allow Host / Domain Names starting with an Underscore [SLE-15-SP5]

library/types/src/modules/Hostname.rb, package/yast2.changes, package/yast2.spec
**This is the merge PR for SLE-15-SP6** of PR #1301 .
https://bugzilla.suse.com/show_bug.cgi?id=1219920
Modern DNS setups require using a leading underscore for hostnames in some situations, e.g. `_mydomain.example.com`. But that is not possible to enter in the YaST DNS Server module: Underscores are generally rejected.
Allow a leading underscore for host and domain names. Not just anywhere, just as the leading character.
Since the check is in `Hostname.rb` which belongs to the _yast2_ package (repo _yast-yast2_), this is not in the `yast2-dns-server` package where it might be expected.
This allows a leading underscore for _all_ components of a FQDN in all circumstances. Users need to have some expertise to know when that is suitable.
The error message quoted in the bug remains the same; …
=> Allow Host / Domain Names starting with an Underscore [SLE-15-SP6]

library/types/src/modules/Hostname.rb, package/yast2.changes, package/yast2.spec
**This is the merge PR for master** of PR #1301 / PR #1302.
https://bugzilla.suse.com/show_bug.cgi?id=1219920
Modern DNS setups require using a leading underscore for hostnames in some situations, e.g. `_mydomain.example.com`. But that is not possible to enter in the YaST DNS Server module: Underscores are generally rejected.
Allow a leading underscore for host and domain names. Not just anywhere, just as the leading character.
Since the check is in `Hostname.rb` which belongs to the _yast2_ package (repo _yast-yast2_), this is not in the `yast2-dns-server` package where it might be expected.
This allows a leading underscore for _all_ components of a FQDN in all circumstances. Users need to have some expertise to know when that is suitable.
The error message quoted in the bug remains the …
=> Allow Host / Domain Names starting with an Underscore [master]

package/yast2.changes, package/yast2.spec, scripts/save_y2logs
https://github.com/yast/yast-yast2/issues/978 - Permissions/ownership of the resulting file. Leaded to this [yast-devel thread](https://lists.opensuse.org/yast-devel/2020-02/msg00005.html)
https://github.com/yast/yast-yast2/issues/970 Missing journalctl -b.
added journalctl -b instead of journalctl --dmesg and a note about resulting archive permissions
=> Sle 15 sp6

package/yast2.changes, package/yast2.spec, scripts/save_y2logs
Follow up of https://github.com/yast/yast-yast2/pull/1304
=> Merged SLE-15-SP6

library/packages/src/modules/PackageCallbacks.rb, package/yast2.changes, package/yast2.spec
- https://bugzilla.suse.com/show_bug.cgi?id=1223281
- After deleting the old repositories a progress popup stays open and blocks the following UI calls
- The problem happens only when the self-update is enabled, with disabled self-update it works fine
-  It turned out that with updated libzypp the start and end callbacks are called twice:
```
modules/PackageCallbacks.rb(ProgressStart):2338 ProgressStart: 992
modules/PackageCallbacks.rb(ProgressStart):2338 ProgressStart: 992
modules/PackageCallbacks.rb(ProgressEnd):2391 ProgressFinish: 992
modules/PackageCallbacks.rb(ProgressEnd):2391 ProgressFinish: 992
```
- The code is actually prepared for this situation, it counts the nesting level for the start and end calls
- But unfortunately there was a bug when closing the nested callback, it …
=> Properly close popups for nested progress callbacks (bsc#1223281)

library/packages/src/modules/PackageCallbacks.rb, package/yast2.changes, package/yast2.spec, scripts/save_y2logs
- Merging #1310 from SP6 to master
=> [master] Properly close popups for nested progress callbacks (bsc#1223281)

library/systemd/src/lib/yast2/systemd/target.rb, package/yast2.changes, package/yast2.spec
https://bugzilla.suse.com/show_bug.cgi?id=1227580
yast2-services-manager fails to build in its unit tests with the latest systemd V256.
A very rare error condition was met, and it turned out that a refactoring in August 2018, 6 years ago (!), removed an error class; an error that was raised only once in all the YaST code, so the unit tests didn't cover it.
That happens when the `systemctl get-default` command fails.
https://github.com/yast/yast-yast2/commit/e4ab10035ba30f739175009344872c4062c26db6#diff-8ddc7418f9da5ef96888a536c77c9e4c3330414a4b9a14f4ad95830dd00547ae
part of #799 
This only fixes the unit tests failing because of the Ruby `NameError`: It adds the missing error class again. This does **not** fix the part that this problem appears in the first place: That the `systemctl …
=> Re-add Missing Error class

library/general/src/lib/cfa/login_defs.rb, library/general/test/cfa/login_defs_test.rb, library/general/test/cfa/shadow_config_test.rb, library/general/test/data/login.defs-example, library/general/test/data/login.defs/custom/etc/login.defs.d/70-yast.defs, library/general/test/data/login.defs/custom/etc/login.defs.d/99-local.defs, library/general/test/data/login.defs/custom/usr/etc/login.defs, library/general/test/data/login.defs/vendor/usr/etc/login.defs, package/yast2.changes, package/yast2.spec
https://bugzilla.suse.com/show_bug.cgi?id=1231006
https://github.com/yast/yast-security/pull/160
This removes obsolete parameters from `/etc/login.defs`:
- USERADD_CMD
- USERDEL_PRECMD
- USERDEL_POSTCMD
- USERADD_CMD
More details at the [main PR](https://github.com/yast/yast-security/pull/160).
=> Drop Obsolete login.defs Scripts USERADD_CMD, USERDEL_PRECMD, USERDEL_POSTCMD, USERADD_CMD

library/xml/test/xml_test.rb, package/yast2.changes, package/yast2.spec
Ruby 3.4 use nicer formatting in inspect. And Yast2.rpm tests failing. with something like
```
expected Yast::XMLSerializationError with message matching /represent nil, part of .*"c"=>nil/, got #<Yast::XMLSerializationError: Cannot represent nil, part of {"a" => "b", "b" => "c", "c" => nil, "d" => "e", "e" => "f"}>
```
Do not test exact wording in yast exception and test just that exception is properly raised with proper type.
=> do not test exact wording in xml exception

library/system/src/modules/Kernel.rb, library/system/test/kernel_test.rb, package/yast2.changes, package/yast2.spec
Agama do not use linuxrc for kernel parameters filtering. Result is that even installation parameters are proposed to target system.
bsc: 
- [1234678](https://bugzilla.suse.com/show_bug.cgi?id=1234678)
- https://bugzilla.suse.com/show_bug.cgi?id=1237390
Read kernel parameters from agama file if it is available.
=> Respect Agama kernel parameters

library/general/src/modules/Arch.rb, library/general/test/arch_test.rb, package/yast2.changes, package/yast2.spec
Encryptions with LUKS2 should also be supported by TPM2 devices. Further steps will be done in yast-storage-ng and yast-bootloader.
We need a general call which evaluates if TPM2 is available at all.
New Call "Arch.has_tpm2"
- Added a new unit test
- Tested manually
=> Checking for valid TPM2 devices

library/general/src/modules/Arch.rb, library/general/test/arch_test.rb, package/yast2.changes, package/yast2.spec
*Short description of the original problem.*
- bsc#1245247
- /sys/module/tpm/version includes the version of the kernel module only.
Checking /sys/class/tpm/tpm0/tpm_version_major instead of /sys/module/tpm/version
- *Updated unit test*
=> Improve recognition of TPM devices
