yast/yast-yast2

library/general/test/SCRStub.rb
library/general/test/agents_test/netd_agent_test.rb
library/general/test/agents_test/proc_meminfo_agent_test.rb
library/general/test/agents_test/test_root/etc/xinetd.conf
library/general/test/agents_test/test_root/etc/xinetd.d/echo
library/general/test/agents_test/test_root/etc/xinetd.d/services
library/general/test/scr_stub.rb
library/general/test/test_helper.rb
library/runlevel/test/service_test.rb
library/system/test/hw_detection_test.rb
library/system/test/kernel_test.rb
library/system/test/proc_cmdline_test.rb
library/system/test/test_helper.rb

Let's start fixing it in the SLE12 branch:
* First, sync the tests with the ones in master (i.e. adding new tests for agents)
* Then add the needed fixes. I didn't wanted to go too far in refactoring, just the minimum subset of fixes that makes SLE12 and master branch (and 13.2 I assume) work again.
Once merged, I'll create PR to merge the fixes to the other branches.

Robust tests for SLE12 branch

---

library/general/src/modules/Popup.rb
package/yast2.changes
package/yast2.spec

Did not do any other code cleanups although they are necessary.

Removed icons from all kinds of popups (bnc#875201)

---

library/control/src/modules/InstError.rb
library/control/src/modules/ProductControl.rb
library/general/doc/Hooks.md

I decide to use the simpliest approach as there is only another instance in yast2-registration, so do not spend too much time in it.

use suse bugzilla url (bnc#924427)

---

library/network/src/modules/SuSEFirewall.rb
library/network/src/modules/SuSEFirewallProposal.rb
library/network/test/Makefile.am
library/network/test/load_ipv6_cfg_test.rb
library/network/test/network_interfaces_helpers_test.rb
library/network/test/network_service_test.rb
library/network/test/susefirewall_proposal_test.rb
library/network/test/susefirewall_services_test.rb
library/network/test/susefirewall_test.rb
library/network/test/test_helper.rb
package/yast2.changes
package/yast2.spec

- Propose SuSEfirewal2 to fully initialize (e.g. open ports) already in the init phase to allow using iSCSI (bsc#916376)

iSCSI firewall proposal for SLE 12 (L3/Maintenance Update)

---

library/network/src/modules/SuSEFirewall.rb
library/network/src/modules/SuSEFirewallProposal.rb
library/network/test/Makefile.am
library/network/test/network_service_test.rb
library/network/test/susefirewall_proposal_test.rb
library/network/test/susefirewall_services_test.rb
library/network/test/susefirewall_test.rb
package/yast2.changes
package/yast2.spec

iSCSI firewall proposal for master / SLE 12

---

library/network/src/modules/SuSEFirewallProposal.rb
library/network/test/susefirewall_proposal_test.rb
package/yast2.changes
package/yast2.spec

This is port of https://github.com/yast/yast-yast2/pull/354 from `SLE 12` to `master`

Make iscsi proposal public also in master

---

library/network/src/modules/SuSEFirewallProposal.rb
library/network/test/susefirewall_proposal_test.rb
package/yast2.changes
package/yast2.spec

Fixed firewall proposal in installation (iSCSI-related) [master]

---

library/system/src/lib/yast2/fs_snapshot.rb
library/system/test/fs_snapshot_test.rb

* It assumes that its id is '0'.

FsSnapshot ignores current snapshot

---

library/types/src/modules/Hostname.rb
library/types/testsuite/tests/Hostname.out
package/yast2.changes
package/yast2.spec

bnc#923990
Also a fix for bnc#858908 (use /etc/hostname instead of /etc/HOSTNAME)

Fixed proposing TLD

---

library/general/src/fillup/sysconfig.yast2
package/yast2.changes
package/yast2.spec

https://bugzilla.opensuse.org/show_bug.cgi?id=902394 and https://bugzilla.opensuse.org/show_bug.cgi?id=900853, part of https://fate.suse.com/318099

Recommended pkgs: +PKGMGR_RECOMMENDED -PKGMGR_REEVALUATE_RECOMMENDED

---

library/system/src/lib/yast2/fs_snapshot.rb
library/system/test/fs_snapshot_test.rb
package/yast2.changes
package/yast2.spec

Huha snapshot cleanup

---

library/system/src/lib/yast2/fs_snapshot.rb
library/system/test/fs_snapshot_test.rb
package/yast2.changes
package/yast2.spec

Remove references to snapper extension

---

library/network/src/modules/SuSEFirewall.rb
library/network/test/susefirewall_test.rb
package/yast2.changes
package/yast2.spec

obsoletes https://github.com/yast/yast-yast2/pull/371
minor fix + changelog + rebased

Keep routing state when disabling/stopping firewall

---

library/network/src/modules/SuSEFirewall.rb
library/network/test/susefirewall_test.rb
package/yast2.changes
package/yast2.spec

backport of https://github.com/yast/yast-yast2/pull/388

Backport from master branch

---

library/system/src/modules/Kernel.rb
library/system/test/kernel_test.rb
package/yast2.changes
package/yast2.spec

* efa8443 packaging
* 027b583 checking cpuinfo_flags correctly

[Review] Request from 'schubi2' @ 'yast/yast-yast2/review_150826_checking_cpuinfo_flags_correctly'

---

library/system/src/modules/Kernel.rb
library/system/test/kernel_test.rb
package/yast2.changes
package/yast2.spec

checking cpuinfo_flags correctly

---

library/types/src/modules/Hostname.rb
package/yast2.changes
package/yast2.spec

Hotfix. Propose correct default hostname / domain when network is set by linuxrc

---

library/network/src/modules/SuSEFirewall.rb
package/yast2.changes
package/yast2.spec

Fixes [bsc#955400](https://bugzilla.suse.com/show_bug.cgi?id=955400).

Set default value for FW_BOOT_FULL_INIT

---

package/yast2.changes
package/yast2.spec

Dependency fix - fixes Puny code processing in YaST
- 3.1.157

The idnconv tool has been moved to the idnkit package (bsc#953442)

---

package/yast2.changes
package/yast2.spec

Fixed idnkit dependency to allow building YaST HEAD in SLE12

---

library/general/src/lib/ui/service_status.rb
library/general/test/service_status_test.rb
package/yast2.changes
package/yast2.spec

To address the concerns expressed in https://github.com/yast/yast-yast2/pull/416

UI::ServiceStatus: rename reload and enabled to xxx_flag

---

library/network/src/modules/SuSEFirewall.rb
package/yast2.changes
package/yast2.spec

This fix is taken from SLE-12-GA. As it's the only difference, I've also merged the SLE-12-GA branch into SLE-12-SP1.

Set a default value for FW_BOOT_FULL_INIT

---

library/network/src/modules/SuSEFirewall.rb
package/yast2.changes
package/yast2.spec

This is a port of #412 for `master`. It was merged already for SP1 (#422).

Merge SLE 12 SP1 into master

---

library/general/src/Makefile.am
library/general/src/lib/ui/dialog.rb
library/general/src/lib/ui/installation_dialog.rb
library/general/test/installation_dialog_test.rb
package/yast2.changes
package/yast2.spec

The unit tests are still missing. I'll update the PR tomorrow.

New UI::InstallationDialog class

---

library/types/src/modules/Hostname.rb
package/yast2.changes
package/yast2.spec

AY profile generated at the end of installation contains valid hostname

---

library/control/src/modules/ProductFeatures.rb
library/control/test/Makefile.am
library/control/test/ProductFeatures_test.rb
package/yast2.changes
package/yast2.spec

https://fate.suse.com/317481 Add 'System Role' capabilities to installer

System Role (FATE#317481)

---

library/Makefile.am
library/mail/Makefile.am
library/mail/src/Makefile.am

- Not added make files so new folders weren't created.

Added missing make files to tarball generation. (FATE#319711)

---

library/network/src/modules/PortRanges.rb

Tests are still missing.
FlattenServices is a poorly understood beast.

Reviewed and fixed docs for PortRanges.

---

package/yast2.spec

Used [spec-cleaner](https://github.com/openSUSE/spec-cleaner), no further changes seemed to be necessary.
First commit from me, more packages to be expected.

Spec file cleanup

---

library/control/src/modules/Installation.rb
package/yast2.changes
package/yast2.spec

- This PR is related to yast/yast-installation#367

Added restarting flag/state to installation (bsc#974409)

---

package/yast2.changes

This PR is part of #463 and related to:
yast/yast-installation#367
yast/yast-packager#155

Added reference to related bsc (bsc#974409)

---

.travis.yml
library/general/src/lib/installation/auto_client.rb

Related to https://github.com/yast/yast-bootloader/pull/350

improve documentation of auto client workflow

---

library/general/src/modules/Popup.rb
library/general/test/popup_test.rb
package/yast2.changes
package/yast2.spec

Trello: https://trello.com/c/97LUpJYA
P1 bug: https://bugzilla.suse.com/show_bug.cgi?id=988739
Found by Ilya when developing an addon for a Major Partner

Fixed ArgumentError in Popup.AnyTimedMessage (P1 bsc#988739)

---

library/network/src/lib/network/susefirewall.rb
library/network/src/lib/network/susefirewalld.rb
library/network/src/lib/network/susefirewalldservices.rb
library/network/src/lib/network/susefirewallservices.rb
package/yast2.changes
package/yast2.spec

Declare textdomain to fix untranslated texts

---

package/yast2.changes
package/yast2.spec
scripts/save_y2logs

Same as https://github.com/yast/yast-yast2/pull/498 but for SLE-12-SP2 branch.

save_y2logs: use canonical path (bsc#1001454)

---

package/yast2.changes
package/yast2.spec
scripts/yast2-funcs

Related to https://github.com/libyui/libyui-qt/pull/60 and https://github.com/libyui/libyui-qt/pull/61 but for textmode installation.
We have several themes for libyui-ncurses and one of them is called `highcontrast`.

Set screenmode for textmode installation

---

library/system/src/modules/Kernel.rb
package/yast2.changes
package/yast2.spec

* 6efa46c added needed include

[Review] Request from 'schubi2' @ 'yast/yast-yast2/review_161116_missing_include'

---

doc/desktop_file.md

Merge document resource aliases

---

library/control/src/modules/WorkflowManager.rb
library/control/test/Makefile.am
library/control/test/workflow_manager_test.rb
package/yast2.changes
package/yast2.spec

Fix [bsc#1011869](https://bugzilla.suse.com/show_bug.cgi?id=1011869). This bug was introduced during a [rubocop update](https://github.com/yast/yast-yast2/pull/478/files#diff-ee72b5fab6634396aa4067ae6b3800afR751).

Fix workflow module replacement (bsc#1011869)

---

library/general/src/modules/OSRelease.rb
library/general/test/os_release_test.rb
package/yast2.changes
package/yast2.spec

Needed for https://github.com/yast/yast-country/pull/104.

Add ID to OSRelease

---

library/network/src/modules/NetworkInterfaces.rb
library/network/test/data/etc/sysconfig/network/ifcfg-
library/network/test/network_interfaces_helpers_test.rb
package/yast2.changes
package/yast2.spec

Do not cache ifcfgs with emtpy device name part

---

library/general/src/lib/installation/proposal_client.rb

https://trello.com/c/XDgl2dj7/816-13-casp-new-all-in-one-dialog
Main PR: https://github.com/yast/yast-installation/pull/487
For context, here is the [rendered documentation for `Installation::ProposalClient#make_proposal`](http://www.rubydoc.info/github/yast/yast-yast2/Installation%2FProposalClient:make_proposal) (before this PR)

Declare simple_mode for make_proposal (FATE#322328)

---

.travis.yml
Dockerfile
library/commandline/test/commandline_test.rb
library/general/test/mode_test.rb
library/packages/test/file_conflict_callbacks_test.rb

- Use Docker at Travis
- Fixed the tests - the tests failed in Travis but passed locally, it turned out that that some tests are order dependent
- Do not change the Mode in some tests
- Mock accessing Mode to not use the real value

Docker at travis

---

library/cwm/src/lib/cwm/widget.rb
package/yast2.changes
package/yast2.spec

See also https://lists.opensuse.org/yast-devel/2017-01/msg00035.html

Fix replace widget

---

library/systemd/src/lib/yast2/systemd_unit.rb
package/yast2.changes
package/yast2.spec

* e5bb075 fixed version
* b351fc8 Merge pull request #550 from yast/SLE-12-SP2-bnc-1012047
* 00522d5 making rubocop happy
* ad92262 merged with SLES12-SP2
* ef170f2 checking UnitFileState value

[Review] Request from 'schubi2' @ 'yast/yast-yast2/review_170316_bnc_1012047_master'

---

library/cwm/src/lib/cwm/widget.rb
library/cwm/test/widgets_test.rb
package/yast2.changes
package/yast2.spec

See https://github.com/yast/yast-installation/pull

Extra spacing support for CWM::RadioButtons

---

library/control/src/modules/WorkflowManager.rb
library/control/test/workflow_manager_test.rb
package/yast2.changes
package/yast2.spec

- Enhanced and improved the PoC by @jsrain 
- Changed the RPM `Provides` from `installerupdate()` to `installerextension()` ("installerupdate" sounds rather self-update related and might be confusing).
- Added tests

Download addons installation.xml from RPM package

---

library/packages/src/modules/SlideShow.rb
package/yast2.changes
package/yast2.spec

- merge SLE-12SP2 #561 which backported #560 from SP3

Merge SLE-12-SP2 into CASP

---

library/commandline/src/modules/CommandLine.rb
library/control/src/modules/InstExtensionImage.rb
library/control/src/modules/WorkflowManager.rb
library/cwm/doc/CWM.md
library/cwm/src/lib/cwm/widget.rb
library/general/src/lib/installation/auto_client.rb
library/general/src/modules/UIHelper.rb
library/network/src/lib/network/susefirewall2services.rb
library/network/src/lib/network/susefirewalld.rb
library/network/src/lib/network/susefirewalldservices.rb
library/network/src/modules/CWMFirewallInterfaces.rb
library/network/src/modules/NetworkInterfaces.rb
library/network/src/modules/SuSEFirewallExpertRules.rb
library/network/src/modules/SuSEFirewallProposal.rb
library/packages/src/lib/packages/dummy_callbacks.rb
library/packages/src/lib/packages/update_messages_view.rb
library/packages/src/modules/SignatureCheckDialogs.rb
library/wizard/src/modules/Wizard.rb

it does not fix all issues, but it makes sense alone and I do not want to create to big pull requests.

fix yardoc tags

---

library/cwm/src/lib/cwm/widget.rb
library/cwm/src/modules/CWM.rb

As I answered @ls-zhu's questions it became apparent that the CWM documentation only helps if you already know how it works. This should help to explain it to beginners.

Explain CWM usage better.

---

library/cwm/examples/object_api_table.rb
library/cwm/src/Makefile.am
library/cwm/src/lib/cwm/table.rb
library/cwm/test/Makefile.am
library/cwm/test/table_test.rb
package/yast2.changes
package/yast2.spec

[bsc#1039901](https://bugzilla.suse.com/show_bug.cgi?id=1039901)
for https://trello.com/c/9HhmcdOP

implement cwm table

---

library/general/src/lib/ui/event_dispatcher.rb
library/general/test/event_dispatcher_test.rb
package/yast2.changes
package/yast2.spec

Add EventDispatcher#event_handler method to allow custom event management.

Event handler

---

package/yast2.changes

to make this go further in the OBS
This is an amendment to #592

Added a bug number

---

library/system/src/clients/view_anymsg.rb
package/yast2.changes
package/yast2.spec
test/yast2_test.rb

Add `/var/log/YaST2/y2log` to the list of files when System Log is used.

Add y2log to system logs

---

library/packages/src/Makefile.am
library/packages/src/lib/packages/product.rb
library/packages/src/lib/packages/repository.rb
library/packages/test/Makefile.am
library/packages/test/lib/product_test.rb
library/packages/test/lib/repository_test.rb
package/yast2.changes
package/yast2.spec

See [bsc#1055677](https://bugzilla.opensuse.org/show_bug.cgi?id=1055677).

Restore Product and Repository classes

---

library/systemd/src/lib/yast2/systemd_unit.rb
package/yast2.changes
package/yast2.spec

Revert to using separate property options to keep old tests working

---

package/yast2.changes
package/yast2.spec
scripts/yast2

Fix running gnome center

---

library/general/src/modules/Linuxrc.rb
library/general/test/linuxrc_test.rb
package/yast2.changes
package/yast2.spec

* 560cb7d1 disable vnc, shh,... installation if it is not supported

[Review] Request from 'schubi2' @ 'yast/yast-yast2/review_170928_disable_remote_installation'

---

library/network/src/lib/network/susefirewall.rb
library/network/src/lib/network/susefirewall2.rb
library/network/test/susefirewall_test.rb
library/network/test/susefirewalld_test.rb
package/yast2.changes
package/yast2.spec

- It merges #630 
Fixes the same issue in SLE-12-SP3

Merge SLE-12-SP2 into SLE-12-SP3

---

library/control/src/modules/ProductFeatures.rb

I needed to know for reviewing https://github.com/yast/yast-services-manager/pull/134

doc: what if ProductFeatures.GetFeature does not find it

---

.travis.yml
Dockerfile

WIP, Tackling https://trello.com/c/CyuJDYsJ/338-dedicated-yast-integrator
I am breaking the usual rule of "comment the WHY but not the WHAT" because the Docker CI mechanism is not a "core competency"

Make docs about Travis+Docker discoverable

---

library/network/src/lib/y2firewall/firewalld.rb
library/network/src/lib/y2firewall/firewalld/api.rb
library/network/test/y2firewall/firewalld_test.rb
package/yast2.changes
package/yast2.spec

Better method naming and tests (also a litle issue calling Service.Enabled)

Firewalld: Added change_interface api method and tests for firewalld 

---

library/network/src/lib/network/susefirewalld.rb
library/network/test/susefirewalld_test.rb
package/yast2.changes
package/yast2.spec

- Workaround for: https://bugzilla.suse.com/show_bug.cgi?id=1067193

SuSEFirewall: Export minimal AY firewalld configuration (bsc#1067193)

---

library/cwm/src/lib/cwm/rspec.rb
package/yast2.changes
package/yast2.spec

- Related to: https://github.com/yast/yast-firewall/pull/39#discussion_r152500910

Added RSpec shared example for CWM::CheckBox

---

library/network/src/Makefile.am
package/yast2.changes
package/yast2.spec

- Raised in: https://travis-ci.org/yast/yast-network/builds/308885709?utm_source=github_status&utm_medium=notification

Added missing y2firewall/firewalld/zone.rb file to Makefile

---

package/yast2.changes
package/yast2.spec

Document fillup-templates path change

---

library/network/src/modules/NetworkInterfaces.rb
library/network/test/network_interfaces_helpers_test.rb
package/yast2.changes
package/yast2.spec

API improvement

---

library/cwm/src/lib/cwm/pager.rb
library/cwm/src/lib/cwm/rspec.rb
package/yast2.changes
package/yast2.spec

Necessary for PBI: https://trello.com/c/kE0SSbi5/698-0-partitioner-plain-partitioning-hard-disks-overview-add-edit-buttons

Make #current_page public

---

library/cwm/src/lib/cwm/rspec.rb
package/yast2.changes
package/yast2.spec

See https://trello.com/c/9C5f4JJN/801-0-important-fix-building-yast2-storage-ng

Improve tests for CWM::Pager#current_page 

---

library/control/src/modules/AutoinstData.rb
package/yast2.changes
package/yast2.spec

* ea1b15e7 packaging
* 23005c6d added @autoyast_second_stage_error to AutoinstData

[Review] Request from 'schubi2' @ 'yast/yast-yast2/review_171211_bnc_1061754'

---

library/network/src/Makefile.am
library/network/src/lib/y2firewall/firewalld.rb
library/network/src/lib/y2firewall/firewalld/relations.rb
library/network/src/lib/y2firewall/firewalld/zone.rb
library/network/src/lib/y2firewall/firewalld/zone_parser.rb
library/network/test/y2firewall/firewalld/zone_parser.rb
library/network/test/y2firewall/firewalld/zone_test.rb
package/yast2.changes
package/yast2.spec

- [Trello Card](https://trello.com/c/jL8fhEKw/1091-5-firewall-firewalld-is-the-new-susefirewall-autoyast-support)

Firewalld: Added zone handling for AutoYaST support

---

library/network/src/lib/y2firewall/firewalld.rb
library/network/src/lib/y2firewall/firewalld/api.rb
library/network/src/lib/y2firewall/firewalld/zone.rb
library/network/test/y2firewall/firewalld/zone_test.rb
library/network/test/y2firewall/firewalld_test.rb
package/yast2.changes
package/yast2.spec

Trello Card: https://trello.com/c/jL8fhEKw/1091-5-firewall-firewalld-is-the-new-susefirewall-autoyast-support

Firewalld: Allow to modify the default zone

---

library/control/src/modules/WorkflowManager.rb
library/control/test/workflow_manager_test.rb
package/yast2.changes
package/yast2.spec

* 6bb1cb90 packaging
* 3723e63c adding a worklow with append_modules value only

[Review] Request from 'schubi2' @ 'yast/yast-yast2/review_180110_append_modules_handling'

---

library/cwm/examples/object_api.rb
library/cwm/src/modules/CWM.rb
package/yast2.changes
package/yast2.spec

Tested manually using modified example.

Abort handler

---

library/network/src/lib/y2firewall/firewalld.rb
library/network/src/lib/y2firewall/firewalld/service.rb
library/network/src/lib/y2firewall/firewalld/zone.rb
library/network/src/modules/CWMFirewallInterfaces.rb
library/network/src/modules/firewalld_wrapper.rb
library/network/test/cwm_firewall_interfaces_test.rb
library/network/test/firewalld_wrapper_test.rb
package/yast2.changes
package/yast2.spec

- Needed by https://github.com/yast/http-server
- Also solve a small issue.

Firewalld: Added methods for opening ports by YaPI modules.

---

library/packages/src/modules/Product.rb
package/yast2.changes
package/yast2.spec

- Just fixed a typo introduced in #672

Fixed logging typo

---

library/network/src/lib/y2firewall/firewalld.rb
package/yast2.changes
package/yast2.spec

- [Trello Card](https://trello.com/c/99OkErr6/1093-8-firewall-firewalld-is-the-new-susefirewall-cwm)

Cache whether the configuration has been read or not

---

library/network/src/lib/y2firewall/firewalld.rb
library/network/src/lib/y2firewall/firewalld/api/zones.rb
library/network/src/lib/y2firewall/firewalld/relations.rb
library/network/src/lib/y2firewall/firewalld/service.rb
library/network/src/lib/y2firewall/firewalld/zone.rb
library/network/src/lib/y2firewall/firewalld/zone_parser.rb
library/network/test/y2firewall/firewalld/zone_test.rb
library/network/test/y2firewall/firewalld_test.rb
package/yast2.changes
package/yast2.spec

- Goes after #674 and add some improvements for modification comparisons and also add permanent to almost all the api options to avoid mistakes between running & persistent config.

Cache modified

---

.gitignore

Merge SLE-12-SP1 into SLE-12-SP2

---

library/network/src/lib/y2firewall/firewalld.rb
library/network/test/y2firewall/firewalld_test.rb
package/yast2.changes
package/yast2.spec

- https://bugzilla.suse.com/show_bug.cgi?id=1082827
* 1ee398d5 packaging
* 29c57748 taking correct value for --set-log-denied

Firewalld: Verify that the configuration has been read before writing

---

package/yast2.changes

Fixed the changes file (somehow I skipped 4.0.57).

Fix changes file

---

library/general/example/old_popup.rb
library/general/src/lib/yast2/popup.rb
library/general/src/modules/Popup.rb
library/general/test/popup_test.rb
package/yast2.changes
package/yast2.spec

tested manually. example can be also used to test old behavior if used without Y2DIR.

Fix timed error any question

---

library/wizard/src/modules/Wizard.rb
package/yast2.changes
package/yast2.spec

This PR replaces #616 using a branch from the same repository for being able to collaborate pushing to it.
https://bugzilla.suse.com/show_bug.cgi?id=1087224

Fallback hicolor (bsc#1087224)

---

library/packages/src/modules/PackageCallbacks.rb
library/packages/test/package_callbacks_test.rb
package/yast2.changes
package/yast2.spec

Fixes [bsc#1088682](https://bugzilla.suse.com/show_bug.cgi?id=1088682).

Handle I/O errors in DoneProvide callback

---

library/general/src/lib/ui/text_helpers.rb
library/general/test/text_helpers_test.rb
package/yast2.changes
package/yast2.spec

Related pull requests:
* https://github.com/yast/yast-packager/pull/348
* https://github.com/yast/yast-installation/pull/687

Helper to wrap text into direction markers

---

library/cwm/examples/object_api.rb
library/cwm/src/lib/cwm/dialog.rb
library/cwm/src/modules/CWM.rb
library/cwm/test/dialog_test.rb
package/yast2.changes
package/yast2.spec

Needed for PBI https://trello.com/c/Lqos3IvN/238-2-partitioner-fix-abort-and-back-buttons

Add handlers

---

library/system/src/desktop/messages.desktop
package/yast2.changes
package/yast2.spec

* 116b134a Added additional searchkeys to desktop file (#746)

[Review] Request from 'schubi2' @ 'yast/yast-yast2/review_180629_merged_with_sles15'

---

library/network/src/modules/NetworkInterfaces.rb
package/yast2.changes
package/yast2.spec

- https://bugzilla.suse.com/show_bug.cgi?id=1098919

Prevent from crashing when deleting ip aliases (bsc#1098919)

---

library/network/src/lib/network/susefirewall2.rb
library/network/src/modules/NetworkInterfaces.rb
package/yast2.changes
package/yast2.spec

Merges SLE-15-GA into master

---

.rubocop.yml
library/systemd/examples/comparison_of_widgets.rb
library/systemd/examples/service_widget.rb
library/systemd/src/lib/yast2/service_configuration.rb
library/systemd/src/lib/yast2/service_widget.rb
library/systemd/test/Makefile.am
library/systemd/test/yast2/Makefile.am
library/systemd/test/yast2/service_configuration.rb

Old Service Status
Old CWM AutoStart
new one with all values

[RFC] Socket widget

---

library/system/src/lib/yast2/system_service.rb
library/systemd/src/lib/yast2/systemd_unit.rb

Part of PBI: https://trello.com/c/fZC7vbpA/108-3-fate319428-mu-display-correct-status-information-on-services-list
Needed for https://github.com/yast/yast-services-manager/pull/147

Add methods to read the service state

---

library/system/src/lib/yast2/system_service.rb
library/system/test/yast2/system_service_test.rb

* Add changed_value?
* Alias SystemService#active? to SystemService#active.

Add a SystemService#changed_value?

---

library/network/src/lib/y2firewall/firewalld/api.rb
package/yast2.changes

Those changes were not included in SLE-15-GA, but they should. See original PR https://github.com/yast/yast-yast2/pull/736.

Backport changes

---

library/system/src/lib/yast2/system_service.rb
library/system/test/yast2/system_service_test.rb
library/systemd/src/lib/yast2/systemd_unit.rb
library/systemd/src/modules/systemd_service.rb

* Add an API to query about errors when changing system services settings.

Add errors support to SystemService

---

library/types/src/modules/Punycode.rb
library/types/test/Makefile.am
library/types/test/punycode_test.rb
package/yast2.changes
package/yast2.spec

Trello card: https://trello.com/c/3c9gw00k
It backport #685 for fixing https://bugzilla.suse.com/show_bug.cgi?id=1101851

Backport simpleidn

---

library/types/src/modules/Punycode.rb

Merge SLE-12-SP4 into SLE-15-GA

---

package/yast2.spec

Merge 'SLE-15-GA' into master

---

doc/examples/ask_resize_windows_partition.rb
doc/examples/popups2.rb

Some more inconsequential grammar fixes so I can learn Ruby and learn how to fit into the workflow.  When comfortable with this process, maybe I can make more important/significant commits.

Fix grammar

---

library/systemd/src/lib/yast2/system_service.rb
library/systemd/test/yast2/system_service_test.rb

- Return whether the service was saved
- Raise exception when service cannot be refreshed

Fix save method

---

library/systemd/src/lib/yast2/system_service.rb
library/systemd/src/modules/systemd_service.rb
library/systemd/test/systemd_service_test.rb
library/systemd/test/yast2/system_service_test.rb
package/yast2.changes
package/yast2.spec

Needed to support handling services during 1st stage. Needed for https://github.com/yast/yast-services-manager/pull/164.

Add a SystemdService.build method

---

library/systemd/src/lib/yast2/system_service.rb
library/systemd/src/lib/yast2/systemd_unit.rb
library/systemd/test/systemd_unit_test.rb
library/systemd/test/yast2/system_service_test.rb
package/yast2.changes
package/yast2.spec

Fixes [bsc#1104568](https://bugzilla.suse.com/show_bug.cgi?id=1104568).

Add support for on-demand only services

---

library/systemd/src/lib/yast2/system_service.rb
library/systemd/src/lib/yast2/systemd_unit.rb
library/systemd/test/systemd_unit_test.rb
library/systemd/test/yast2/system_service_test.rb
package/yast2.changes
package/yast2.spec

Add support for on-demand only services (master)

---

library/packages/src/modules/PackageCallbacks.rb
package/yast2.changes
package/yast2.spec

- This is just a backport of #787 to SLE12-SP4
- 3.2.48

SLE12-SP4: Do not display "download failed" error (bsc#1096027)

---

package/yast2.changes

Do not include the author's name

Fix changelog

---

package/yast2.changes

Merge sle 15 ga fix changelog

---

library/systemd/src/lib/yast2/compound_service.rb
library/systemd/test/yast2/compound_service_test.rb
package/yast2.changes
package/yast2.spec

Fixes [bsc#1106591](https://bugzilla.suse.com/show_bug.cgi?id=1106591).

Add support start on boot

---

.yardopts
library/system/doc/system_services.md
library/systemd/doc/services_and_sockets.md
library/systemd/src/lib/yast2/compound_service.rb
library/systemd/src/lib/yast2/system_service.rb
library/systemd/src/lib/yast2/systemd/unit_properties.rb

Add some documentation about the new system services API.

System services documentation

---

library/cwm/examples/object_api.rb
library/cwm/src/lib/cwm/dialog.rb
library/cwm/src/modules/CWM.rb
library/cwm/test/dialog_test.rb
package/yast2.changes
package/yast2.spec

Needed for PBI https://trello.com/c/e1TpNp2Y/213-5-partitioner-handle-on-the-fly-unmounting-in-installed-system

Add next handler

---

library/network/src/lib/network/susefirewalld.rb
library/network/src/modules/SuSEFirewallProposal.rb
library/network/test/susefirewall_proposal_test.rb
package/yast2.changes
package/yast2.spec

It was dropped in #818, we will wait for https://github.com/yast/yast-network/pull/668 and should be dropped in master only.

Bring back susefirewall proposal

---

library/network/src/lib/network/susefirewalld.rb
library/network/src/modules/SuSEFirewallProposal.rb
library/network/test/susefirewall_proposal_test.rb
package/yast2.changes
package/yast2.spec

Merge SLE-15-GA into master

---

library/network/src/Makefile.am
library/network/test/Makefile.am
package/yast2.changes
package/yast2.spec

Makefile susefirewall proposal

---

library/network/src/lib/y2firewall/firewalld.rb
library/network/test/y2firewall/firewalld_test.rb
package/yast2.changes
package/yast2.spec

Needed by https://github.com/yast/yast-firewall/pull/79

Firewalld: Added system_service convenience method

---

library/network/src/modules/NetworkInterfaces.rb
library/network/test/network_interfaces_test.rb
package/yast2.changes
package/yast2.spec

caused by a cleanup here https://github.com/yast/yast-yast2/pull/789/commits/27b496df69b15af1f4a3002b4837ec325dd8e249

Fixed internal error

---

library/network/src/lib/y2firewall/firewalld.rb
library/network/src/lib/y2firewall/firewalld/interface.rb
library/network/src/lib/y2firewall/firewalld/zone.rb
library/network/src/lib/y2firewall/helpers/interfaces.rb
library/network/test/y2firewall/firewalld/interface_test.rb
library/network/test/y2firewall/firewalld/zone_test.rb
library/network/test/y2firewall/firewalld_test.rb
package/yast2.changes
package/yast2.spec

- [Trello card](https://trello.com/c/afBwY7Rc/345-sle-15-ga-as-mu-firewall-ui-support-for-autoyast)
- Needed by yast/yast-firewall#92

Added changes needed for autoyast configuration support

---

library/network/src/lib/y2firewall/firewalld.rb
library/network/src/lib/y2firewall/firewalld/interface.rb
library/network/src/lib/y2firewall/firewalld/zone.rb
library/network/src/lib/y2firewall/helpers/interfaces.rb
library/network/test/y2firewall/firewalld/interface_test.rb
library/network/test/y2firewall/firewalld/zone_test.rb
library/network/test/y2firewall/firewalld_test.rb
library/system/src/clients/view_anymsg.rb
package/yast2.changes
package/yast2.spec

- Just merging #843 to master
- Includes an additional change by @teclator

[master] Log viewer: replace invalid UTF-8 characters (bsc#1110549)

---

library/network/src/lib/y2firewall/firewalld/api/zones.rb
library/network/test/y2firewall/firewalld/api/zones_test.rb
package/yast2.changes
package/yast2.spec

- https://bugzilla.suse.com/show_bug.cgi?id=1112547

Added zone modify_masquerade method (bsc#1112547)

---

library/packages/test/y2packager/licenses_fetchers/rpm_test.rb
package/yast2.changes
package/yast2.spec

Related to fate#325482 (see #880)

Fix rpm license fetcher test

---

library/general/src/modules/Report.rb
library/general/test/report_test.rb
package/yast2.changes
package/yast2.spec

Used in https://github.com/yast/yast-ruby-bindings/pull/227

Made Report.LongError to use adjustable Popup's *LongError methods

---

library/general/src/modules/Report.rb
package/yast2.changes
package/yast2.spec

- Related to #900, fixing even more `Report` methods to support the command line mode
- 4.1.59

Command line support in Report module (related to bnc#1127685)

---

library/general/src/modules/Label.rb
package/yast2.changes
package/yast2.spec

added "Modify" button label

---

library/systemd/src/lib/yast2/service_widget.rb

- Just accidentally found a missing translation
- No version update, it's enough to release it with the next change (the translations are extracted directly from GitHub so it does not matter)

Fixed missing translation

---

library/network/src/modules/NetworkService.rb
library/network/test/network_service_test.rb
package/yast2.changes
package/yast2.spec

Do not crash with internal error when activating network service

---

package/yast2.changes

See https://github.com/yast/yast-yast2/pull/912#issuecomment-475534963

Fix changelog adding missing bug number

---

library/network/src/lib/y2firewall/firewalld/zone.rb
library/network/test/network_service_test.rb
package/yast2.changes
package/yast2.spec

- https://bugzilla.suse.com/show_bug.cgi?id=1130354

Do not consider Zone's name as a normal attribute (bsc#1130354)

---

package/yast2.changes
package/yast2.spec

Use an improved write style for package descriptions.

spec: use noun phrase

---

library/system/src/lib/yast2/clients/view_anymsg.rb
library/system/test/clients/view_anymsg_test.rb
package/yast2.changes
package/yast2.spec

https://bugzilla.suse.com/show_bug.cgi?id=1132658
Give more verbose feedback when system log files cannot be read as expected.
https://trello.com/c/xO25c7am
https://github.com/yast/yast-journal/pull/41

give more verbose feedback in 'view_anymsg' client (bsc#1132658)

---

library/wizard/src/modules/Wizard.rb
package/yast2.changes
package/yast2.spec

This merges PR #926 to master.

Merge SLE-15-SP1 branch to master

---

library/control/src/modules/ProductControl.rb
library/control/src/modules/WorkflowManager.rb
library/general/src/Makefile.am
library/general/src/lib/yast2/control_log_dir_rotator.rb
library/general/src/lib/yast2/log_dir_rotator.rb
library/general/test/control_log_dir_rotator_test.rb
library/xml/src/modules/XML.rb
package/yast2.changes
package/yast2.spec

For https://trello.com/c/xKoN23o3/906-2-include-the-controlxml-to-be-collected-by-savey2logs.

create log directory with control.xml and merged installation.xml

---

package/yast2.changes
package/yast2.spec
scripts/yast2

- https://bugzilla.suse.com/show_bug.cgi?id=1128032 (L3)
- https://trello.com/c/yd33svSH

Stop "ls: write error: Broken pipe" messages (bsc#1128032)

---

package/yast2.changes
package/yast2.spec
scripts/yast2

- forward-porting #922 
- https://bugzilla.suse.com/show_bug.cgi?id=1128032 (was-L3)
- https://trello.com/c/yd33svSH

Stop "ls: write error: Broken pipe" messages (SP3)

---

package/yast2.changes
package/yast2.spec
scripts/yast2

- forward-porting #922 
- https://bugzilla.suse.com/show_bug.cgi?id=1128032 (was-L3)
- https://trello.com/c/yd33svSH

Stop "ls: write error: Broken pipe" messages (SP4)

---

library/packages/src/modules/PackageSystem.rb
library/packages/test/package_system_test.rb
package/yast2.changes
package/yast2.spec

Use Yast::Execute as suggested in https://bugzilla.suse.com/show_bug.cgi?id=1137992#c16

PackageSystem.Installed: Use Yast::Execute instead of SCR

---

library/network/src/Makefile.am
library/network/src/lib/network/firewall_chooser.rb
library/network/test/Makefile.am
library/network/test/firewall_chooser_test.rb
library/network/test/susefirewall2_test.rb
library/network/test/susefirewalld_test.rb
package/yast2.changes
package/yast2.spec
scripts/yast2

It just does a sync merge.
The SuSEFirewall2 code is not relevant at all as the support has been drop in SLE-15 and we will drop the classes in master. But it should not be a problem to have them until completely drop.

Merge 'SLE-12-SP4' into 'SLE-15-GA'

---

package/yast2.changes
package/yast2.spec
scripts/yast2

Following up on #922 (Broken pipe)

Merge SLE-15-GA to SLE-15-SP1

---

library/desktop/src/modules/Desktop.rb
library/desktop/test/data/usr/share/applications/YaST2/org.opensuse.yast.AddOn.desktop
library/desktop/test/data/usr/share/applications/YaST2/org.opensuse.yast.LAN.desktop
library/desktop/test/data/usr/share/applications/YaST2/services-manager.desktop
library/desktop/test/desktop_test.rb
library/desktop/test/test_helper.rb
package/yast2.changes
package/yast2.spec

Fixes https://bugzilla.opensuse.org/show_bug.cgi?id=1140233.

Fix desktop modules reading

---

library/general/test/text_helpers_test.rb

Looks like copypasta from the preceding stanza, could happen to anyone.  :smile:
As this is my first pull-request to Yast2, i'm open to pointers on how to improve.  Please help me help you!  (I tried to create a bugzilla account, but ran into some problems, hence the GitHub approach.)

Fix typo in test-helpers test

---

library/control/src/modules/WorkflowManager.rb
package/yast2.changes
package/yast2.spec

- Similar to https://github.com/yast/yast-add-on/pull/82
- I tested the same scenario also in normal manual installation (originally the problem was reported for AutoYaST) and found a similar problem there
- Tested manually with an FTP server configured with max. 3 connections from the same IP

Release the sources to avoid using up all server connections (bsc#1141127)

---

package/yast2.changes
package/yast2.spec
scripts/yast2

(not sp2 as the branch name wrongly says)

Merge SLE 15 SP1

---

package/yast2.changes
package/yast2.spec

Fixes [bsc#1142595](https://bugzilla.opensuse.org/show_bug.cgi?id=1142595).

Add hostname dependency

---

library/general/src/modules/Report.rb
library/general/test/report_test.rb
package/yast2.changes
package/yast2.spec

Merge SLE-15-SP1 branch into master

---

library/packages/src/modules/PackageCallbacks.rb
package/yast2.changes
package/yast2.spec

https://bugzilla.suse.com/show_bug.cgi?id=1153297

Fix showing details

---

library/packages/src/lib/y2packager/product.rb
library/packages/src/lib/y2packager/product_reader.rb
library/packages/test/y2packager/product_test.rb
package/yast2.changes
package/yast2.spec

related pr https://github.com/yast/yast-registration/pull/454

read products from control file in online medium

---

library/general/src/lib/cfa/sysctl.rb
package/yast2.changes
package/yast2.spec

Found by QA
Tested manually
~~TODO: bug number + changes + version~~

Do not modify /etc/sysctl.conf in inst-sys

---

library/cwm/src/lib/cwm/table.rb
package/yast2.changes
package/yast2.spec

Added helper to easy use of new libyui sort-key (see https://github.com/libyui/libyui/pull/156).

added helper to create UI sort-key term

---

library/cwm/src/lib/cwm/service_widget.rb
library/systemd/src/lib/yast2/service_widget.rb
package/yast2.changes
package/yast2.spec

This PR cherry pick from master the changes done in #999

Service widget: propose default when active

---

library/general/src/lib/ui/text_helpers.rb
package/yast2.changes
package/yast2.spec

- Similar to https://github.com/libyui/libyui-qt/pull/121
- 4.2.50

Farsi is also an RTL language (related to bsc#1156437)

---

library/general/src/modules/OSRelease.rb
library/general/test/data/os-release-SLES-15-SP2
library/general/test/os_release_test.rb
package/yast2.changes
package/yast2.spec

**Problem**
Getting information VERSION="15-SP2" from /etc/os-release
**Solution**
new API call

Master fate 325834

---

library/general/src/lib/cfa/sysctl.rb
library/general/src/lib/cfa/sysctl_config.rb
library/general/test/cfa/sysctl_test.rb
package/yast2.changes
package/yast2.spec

/etc/sysctl.d/70-yast.conf (bsc#1151649).

Reinitializing Augeas parser again before writing data to

---

library/general/src/modules/Popup.rb
library/general/test/popup_test.rb
package/yast2.changes
package/yast2.spec

needed for trello: https://trello.com/c/AyGNkbK3/1708-3-sle15-sp2-p1-1165705-not-able-to-setup-network-when-connection-with-registration-server-failed-a-blocking-popupfeedback

Add Popup.SuppressFeedback method

---

library/network/src/modules/NetworkInterfaces.rb
library/network/test/data/etc/sysconfig/network/ifcfg-eth1
library/network/test/data/etc/sysconfig/network/single_quote.test
library/network/test/network_interfaces_test.rb
package/yast2.changes
package/yast2.spec

merge 'SLE-15-SP1' into 'master'

---

library/systemd/src/lib/yast2/service_widget.rb

Just a minor typo fix. I don't think it's worth a changelog entry or version bump (this module is updated frequently enough, a new version will come soon for sure).

Fix a typo

---

library/general/src/lib/installation/autoinst_issues.rb
library/general/src/lib/installation/autoinst_issues/invalid_value.rb
library/general/src/lib/installation/autoinst_issues/list.rb
library/general/src/lib/installation/autoinst_issues/missing_value.rb
library/general/test/autoinst_issues/invalid_value_test.rb
library/general/test/autoinst_issues/issues_presenter_test.rb
library/general/test/autoinst_issues/list_test.rb
library/general/test/autoinst_issues/missing_value_test.rb
package/yast2.changes
package/yast2.spec

- https://trello.com/c/vAZPOYpg/1838-8-better-error-handling
- https://bugzilla.suse.com/show_bug.cgi?id=1171335 "AutoYaST: improve error reporting mechanism "
- autoinst_issues/list.add : Changed first parameter from tag to  classes
- Added general AY issue classes: InvalidValue, MissingValue

autoinst_issues/list.add : Changed first parameter from tag to classes

---

library/systemd/src/lib/yast2/system_service.rb
library/systemd/test/yast2/system_service_test.rb
package/yast2.changes
package/yast2.spec

See https://github.com/yast/yast-yast2/pull/1059.

Fix system service actions (forward port to SP2)

---

library/systemd/src/lib/yast2/system_service.rb
library/systemd/test/yast2/system_service_test.rb
package/yast2.changes
package/yast2.spec

See https://github.com/yast/yast-yast2/pull/1059.

Fix system service actions (forward port to master)

---

library/network/src/modules/NetworkService.rb
library/network/test/network_service_test.rb
package/yast2.changes
package/yast2.spec

Convenience method to select the network service to be used
Related to yast/yast-network#1077

Add NetworkService.use method

---

library/general/src/lib/installation/autoinst_profile/section_with_attributes.rb

Add documentation for Installation::AutoinstProfile::SectionWithAttributes.

Add documentation for SectionWithAttributes class

---

library/desktop/src/modules/Desktop.rb
package/yast2.changes
package/yast2.spec

A merge with https://github.com/yast/yast-yast2/pull/1074

Sle 15 sp2 bsc 1173133

---

library/desktop/src/modules/Desktop.rb
package/yast2.changes
package/yast2.spec

Merge with https://github.com/yast/yast-yast2/pull/1075

Master bsc 1173133

---

doc/desktop_file.md

trello: https://trello.com/c/bev3V41K/1966-2-tw-1174119-network-section-will-not-be-created-while-calling-yast-clonesystem

specify default for resource

---

library/general/src/modules/Arch.rb
library/general/test/arch_test.rb
package/yast2.changes
package/yast2.spec

It backports #1084 for https://bugzilla.opensuse.org/show_bug.cgi?id=1174183

Backport WSL2 detection to SLE-15-SP2

---

library/packages/test/y2packager/resolvable_test.rb
package/yast2.changes
package/yast2.spec

- Hopefully the last fix :angry: 
- Added a big warning to avoid this
- 4.3.23

Yet another unit test architecture fix

---

library/cwm/src/lib/cwm/table.rb

Part of the dirty prototype at `partitioner-ui-03`. This requires new libyui features that are not ready yet, see https://github.com/libyui/libyui/pull/171.
This PR is not intended to go to master yet.

Add support for nesting tables

---

library/general/src/lib/installation/autoinst_profile/section_with_attributes.rb
library/general/test/installation/autoinst_profile/section_with_attributes_test.rb
package/yast2.changes
package/yast2.spec

Extend #1108 solution to do support an enumerable.

bsc#1177405: SectionWithAttributes#new_from_hashes accepts an Enumerable

---

package/yast2.changes
package/yast2.spec

The changes introduced in #1111 missed the version bump and the changelog entry
Add what was missing.

Update spec file and changelog

---

library/packages/src/lib/y2packager/resolvable.rb
package/yast2.changes
package/yast2.spec

- Related to https://bugzilla.suse.com/show_bug.cgi?id=1176276
- See https://github.com/yast/yast-update/pull/160 for more details

Added more logging (for bsc#1176276)

---

library/control/src/modules/ProductFeatures.rb
package/yast2.changes
package/yast2.spec

see https://bugzilla.suse.com/show_bug.cgi?id=1169874
will fix default hibernation proposal on opensuse.

Fix hibernation typo

---

library/packages/test/y2packager/resolvable_test.rb
library/system/src/lib/yast2/fs_snapshot.rb
library/system/src/lib/yast2/fs_snapshot_store.rb
library/system/test/fs_snapshot_store_test.rb
library/system/test/fs_snapshot_test.rb
package/yast2.changes
package/yast2.spec

Merge #1125 and #1138 into the `SLE-15-SP2` branch.

Merge SLE-15-SP1

---

library/system/src/lib/yast2/fs_snapshot.rb
library/system/src/lib/yast2/fs_snapshot_store.rb
library/system/test/fs_snapshot_store_test.rb
library/system/test/fs_snapshot_test.rb
package/yast2.changes
package/yast2.spec

Merge SLE-15-SP2

---

library/control/src/modules/ProductControl.rb

Fix translation introduced in #1143
No version bump required, it can wait until next change.

[Product Control] Fix translation

---

library/system/src/lib/yast2/fs_snapshot.rb
library/system/src/lib/yast2/fs_snapshot_store.rb
library/system/test/fs_snapshot_store_test.rb
library/system/test/fs_snapshot_test.rb
package/yast2.changes
package/yast2.spec

Backports the fix for [bsc#1180142](bugzilla.suse.com/show_bug.cgi?id=1180142). See https://github.com/yast/yast-yast2/pull/1125.

Backport fix for bsc#1180142

---

library/general/src/modules/Linuxrc.rb
library/general/test/linuxrc_test.rb
library/system/test/fs_snapshot_store_test.rb
library/system/test/fs_snapshot_test.rb
package/yast2.changes
package/yast2.spec

Backport linuxrc option reboot_timeout to 15 SP1
https://progress.opensuse.org/issues/89716
See https://github.com/yast/yast-installation/pull/950 && https://github.com/openSUSE/installation-images/pull/505

Use linuxrc option reboot_timeout to configure the timeout before reboot

---

library/system/src/modules/Kernel.rb
library/system/test/kernel_test.rb
package/yast2.changes
package/yast2.spec

trello: https://trello.com/c/ZWHbojhc/2498-%F0%9F%98%A2%F0%9F%98%B5-2-urgent-p1-total-revert-no-hibernation-feature-please
bzilla: https://bugzilla.suse.com/show_bug.cgi?id=1184470

Revert hibernation sp3

---

library/system/src/modules/Kernel.rb
library/system/test/kernel_test.rb
package/yast2.changes
package/yast2.spec

merge of https://github.com/yast/yast-yast2/pull/1168

Revert hibernation

---

library/general/src/lib/cfa/sysctl_config.rb
package/yast2.changes
package/yast2.spec

Backport #1171 to `SLE-15-SP2`.

Filter sysctl *.conf files

---

library/general/src/lib/installation/auto_client.rb
library/general/test/auto_client_test.rb
package/yast2.changes
package/yast2.spec

bsc: https://bugzilla.suse.com/show_bug.cgi?id=1187233
found during manual testing.

Return value auto client

---

library/general/src/modules/Arch.rb
package/yast2.changes
package/yast2.spec

This can be used for riscv64 specific handling elsewhere.

Add riscv64 architecture helper

---

README.md
doc/README_Template.md

- https://trello.com/c/0s5EUrbE

Update the IRC links to point to libera.chat

---

library/types/test/url_test.rb

See https://github.com/yast/yast-yast2/pull/1183 for details

Fix test broken in 8aab555bb

---

library/types/test/url_test.rb

[SLE-15-SP2] Fix test broken in 8aab555bb

---

library/general/src/lib/y2issues/with_issues.rb
package/yast2.changes
package/yast2.spec

Add *WithIssues* mixin, which makes easier to work with a list of issues.
Needed for https://github.com/yast/yast-users/pull/326.

Add Y2Issues::WithIssues mixin

---

package/yast2.changes

The changelog should reference jsc#SLE- ticket numbers.

Avoid jsc#PM-1998 and jsc#PM-2612 references

---

library/system/src/lib/yast2/fs_snapshot.rb
library/system/src/lib/yast2/fs_snapshot_store.rb
library/system/test/fs_snapshot_store_test.rb
library/system/test/fs_snapshot_test.rb
package/yast2.changes
package/yast2.spec

Merge #1211 and #1212 into `SLE-12-SP4`.

Merge bsc#1180142 fix into `SLE-12-SP4`

---

library/commandline/test/commandline_test.rb

Merge #1216 into `SLE-12-SP4`.

Do not check report internals in the commandline test

---

library/commandline/test/commandline_test.rb
library/system/src/lib/yast2/fs_snapshot.rb
library/system/src/lib/yast2/fs_snapshot_store.rb
library/system/test/fs_snapshot_store_test.rb
library/system/test/fs_snapshot_test.rb
package/yast2.changes
package/yast2.spec
scripts/save_y2logs

Merge #1211, #1212, #1213, #1216, #1217 into `SLE-12-SP5`.

Merge bsc#1180142 fix into SLE-12-SP5

---

library/control/src/modules/WorkflowManager.rb
package/yast2.changes
package/yast2.spec

bsc#1193784: do not reinitialize repos during upgrade (master)

---

package/yast2.spec
test/test_helper.rb

- Let's use the new helper everywhere

Unify YaST module mocking

---

library/packages/src/modules/PackageAI.rb
library/packages/test/package_ai_test.rb
package/yast2.changes
package/yast2.spec

[bsc#1195137](https://bugzilla.suse.com/show_bug.cgi?id=1195137)
Fix a wrong call to PackagesProposal.GetResolvables.

Fix wrong call to PackagesProposal.GetResolvables

---

library/packages/src/modules/PackageSystem.rb
package/yast2.changes
package/yast2.spec

- Fixed initializing the old repositories during system upgrade
- This a backport of #1198 to SLE15-SP3

Fixed initializing the old repositories (bsc#1196120)

---

library/packages/src/modules/SlideShow.rb
library/packages/test/slide_show_test.rb
package/yast2.changes
package/yast2.spec

https://trello.com/c/CeYLzrD1/
https://bugzilla.suse.com/show_bug.cgi?id=1196674
Users installing many machines, especially with AutoYaST, might not be sure which product they are installing when almost everything is automated. They (or some automatism) might or might not have picked the correct AutoYaST profile, but they can't verify that.
Show the name of the base product while packages are being installed in the new unified installation progress step, but only during system installation or upgrade (no matter if using AutoYaST or not); not in the installed system.
Only the _base_ product is shown, not any add-on products. This is in line with the reduction of this progress reporting to one single progress bar with only the overall progress, not individual packages.
Notice that many …

Show what Product is Being Installed [SLE-15-SP4]

---

library/packages/src/modules/SlideShow.rb
library/packages/test/test_helper.rb
package/yast2.changes
package/yast2.spec

Merge of https://github.com/yast/yast-yast2/pull/1256

Packager fix sp4 merge

---

library/packages/src/modules/Package.rb
library/packages/test/package_test.rb
package/yast2.changes
package/yast2.spec

YaST failed to install any additional package on transactional system.
Inform user which packages are needed and let them install it.
- *Added a new unit test*

Transaction packages

---

library/packages/test/package_test.rb

fixes test that cause failure in jenkins from https://github.com/yast/yast-yast2/pull/1265

fix test for package dialog

---

library/packages/src/lib/packages/file_conflict_callbacks.rb
library/packages/test/file_conflict_callbacks_test.rb
package/yast2.changes
package/yast2.spec

See https://github.com/yast/yast-yast2/pull/1264/commits/3f84711a0cc0182e92d3aa796134049b3e9ed7a1
- *Bugzilla link*
https://bugzilla.suse.com/show_bug.cgi?id=1202892
backported from master

Backported fix for no dialog issue

---

library/network/src/modules/NetworkService.rb
library/network/test/network_service_test.rb
package/yast2.changes
package/yast2.spec

NetworkService enforce selected network service is enabled during installation (bsc#1202479) (master)

---

library/general/src/modules/Arch.rb
package/yast2.changes
package/yast2.spec
scripts/yast2-funcs

See https://github.com/yast/yast.github.io/pull/336 for details

Replaced egrep with grep -E

---

package/yast2.changes
package/yast2.spec

Replace transitional %usrmerged macro with regular version check (boo#1206798)

Replace transitional %usrmerged macro with regular version check (boo#1206798)

---

library/system/src/modules/Initrd.rb
package/yast2.changes
package/yast2.spec

mkinitrd will be removed from TW/ALP.
Replace call to it with dracut. And when touching module also do a bit cleanup.

clean and adapt initrd module

---

package/yast2.changes
package/yast2.spec
scripts/save_y2logs

Followup of https://github.com/yast/yast-yast2/pull/1304

journalctl --dmesg not needed anymore

---

library/packages/src/modules/PackageCallbacks.rb
package/yast2.changes
package/yast2.spec

- Merging #1309 from SP5 to SP6

[SLE15-SP6] Properly close popups for nested progress callbacks (bsc#1223281)

---

library/packages/src/modules/Package.rb
package/yast2.changes
package/yast2.spec

[master] Do not install packages to inst-sys (bsc#1240867)
